[build]
  command = "npm run build"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://dazzling-smile-production-1014.up.railway.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"
