services:
  - type: web
    name: ai-fitting-tool
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 80
      - key: ALLOWED_ORIGINS
        value: https://lumiafricca.netlify.app,http://localhost:3000
      - key: BACKEND_API_URL
        value: https://dazzling-smile-production-1014.up.railway.app
