// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type CartReservationsStatus string

const (
	CartReservationsStatusReserved  CartReservationsStatus = "reserved"
	CartReservationsStatusCompleted CartReservationsStatus = "completed"
	CartReservationsStatusAbandoned CartReservationsStatus = "abandoned"
)

func (e *CartReservationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CartReservationsStatus(s)
	case string:
		*e = CartReservationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CartReservationsStatus: %T", src)
	}
	return nil
}

type NullCartReservationsStatus struct {
	CartReservationsStatus CartReservationsStatus `json:"cart_reservations_status"`
	Valid                  bool                   `json:"valid"` // Valid is true if CartReservationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCartReservationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CartReservationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CartReservationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCartReservationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CartReservationsStatus), nil
}

type OrdersStatus string

const (
	OrdersStatusPending    OrdersStatus = "pending"
	OrdersStatusProcessing OrdersStatus = "processing"
	OrdersStatusShipped    OrdersStatus = "shipped"
	OrdersStatusDelivered  OrdersStatus = "delivered"
	OrdersStatusCancelled  OrdersStatus = "cancelled"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus `json:"orders_status"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

type ProductsGender string

const (
	ProductsGenderMen    ProductsGender = "men"
	ProductsGenderWomen  ProductsGender = "women"
	ProductsGenderKids   ProductsGender = "kids"
	ProductsGenderUnisex ProductsGender = "unisex"
)

func (e *ProductsGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductsGender(s)
	case string:
		*e = ProductsGender(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductsGender: %T", src)
	}
	return nil
}

type NullProductsGender struct {
	ProductsGender ProductsGender `json:"products_gender"`
	Valid          bool           `json:"valid"` // Valid is true if ProductsGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductsGender) Scan(value interface{}) error {
	if value == nil {
		ns.ProductsGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductsGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductsGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductsGender), nil
}

type ProductsStatus string

const (
	ProductsStatusActive   ProductsStatus = "active"
	ProductsStatusPending  ProductsStatus = "pending"
	ProductsStatusHidden   ProductsStatus = "hidden"
	ProductsStatusArchived ProductsStatus = "archived"
)

func (e *ProductsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductsStatus(s)
	case string:
		*e = ProductsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductsStatus: %T", src)
	}
	return nil
}

type NullProductsStatus struct {
	ProductsStatus ProductsStatus `json:"products_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProductsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductsStatus), nil
}

type UsersRole string

const (
	UsersRoleCUSTOMER UsersRole = "CUSTOMER"
	UsersRoleVENDOR   UsersRole = "VENDOR"
	UsersRoleADMIN    UsersRole = "ADMIN"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type VendorApplicationsStatus string

const (
	VendorApplicationsStatusPending  VendorApplicationsStatus = "pending"
	VendorApplicationsStatusApproved VendorApplicationsStatus = "approved"
	VendorApplicationsStatusRejected VendorApplicationsStatus = "rejected"
)

func (e *VendorApplicationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorApplicationsStatus(s)
	case string:
		*e = VendorApplicationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorApplicationsStatus: %T", src)
	}
	return nil
}

type NullVendorApplicationsStatus struct {
	VendorApplicationsStatus VendorApplicationsStatus `json:"vendor_applications_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if VendorApplicationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorApplicationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VendorApplicationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorApplicationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorApplicationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorApplicationsStatus), nil
}

type VendorSubscriptionsPlan string

const (
	VendorSubscriptionsPlanMonthly   VendorSubscriptionsPlan = "monthly"
	VendorSubscriptionsPlanQuarterly VendorSubscriptionsPlan = "quarterly"
	VendorSubscriptionsPlanBiannual  VendorSubscriptionsPlan = "biannual"
	VendorSubscriptionsPlanYearly    VendorSubscriptionsPlan = "yearly"
)

func (e *VendorSubscriptionsPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorSubscriptionsPlan(s)
	case string:
		*e = VendorSubscriptionsPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorSubscriptionsPlan: %T", src)
	}
	return nil
}

type NullVendorSubscriptionsPlan struct {
	VendorSubscriptionsPlan VendorSubscriptionsPlan `json:"vendor_subscriptions_plan"`
	Valid                   bool                    `json:"valid"` // Valid is true if VendorSubscriptionsPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorSubscriptionsPlan) Scan(value interface{}) error {
	if value == nil {
		ns.VendorSubscriptionsPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorSubscriptionsPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorSubscriptionsPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorSubscriptionsPlan), nil
}

type Address struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Label     string       `json:"label"`
	Street    string       `json:"street"`
	City      string       `json:"city"`
	State     string       `json:"state"`
	Country   string       `json:"country"`
	ZipCode   string       `json:"zip_code"`
	IsDefault sql.NullBool `json:"is_default"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type CartReservation struct {
	ID            string                 `json:"id"`
	UserID        string                 `json:"user_id"`
	ProductID     string                 `json:"product_id"`
	Quantity      int32                  `json:"quantity"`
	ReservedAt    sql.NullTime           `json:"reserved_at"`
	ReservedUntil time.Time              `json:"reserved_until"`
	Status        CartReservationsStatus `json:"status"`
	OrderID       sql.NullString         `json:"order_id"`
	CreatedAt     sql.NullTime           `json:"created_at"`
	UpdatedAt     sql.NullTime           `json:"updated_at"`
}

type Order struct {
	ID              string          `json:"id"`
	UserID          string          `json:"user_id"`
	Items           json.RawMessage `json:"items"`
	Subtotal        string          `json:"subtotal"`
	ShippingCost    string          `json:"shipping_cost"`
	Total           string          `json:"total"`
	PaymentMethod   string          `json:"payment_method"`
	Status          OrdersStatus    `json:"status"`
	DeliveryAddress string          `json:"delivery_address"`
	Notes           sql.NullString  `json:"notes"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	DeliveredAt     sql.NullTime    `json:"delivered_at"`
}

type Product struct {
	ID          string          `json:"id"`
	VendorID    string          `json:"vendor_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Brand       string          `json:"brand"`
	Category    string          `json:"category"`
	Subcategory string          `json:"subcategory"`
	Gender      ProductsGender  `json:"gender"`
	Price       string          `json:"price"`
	Discount    sql.NullString  `json:"discount"`
	Images      json.RawMessage `json:"images"`
	Colors      json.RawMessage `json:"colors"`
	Sizes       json.RawMessage `json:"sizes"`
	Sku         string          `json:"sku"`
	Stock       int32           `json:"stock"`
	Rating      sql.NullString  `json:"rating"`
	ReviewCount sql.NullInt32   `json:"review_count"`
	Status      ProductsStatus  `json:"status"`
	Bestseller  sql.NullBool    `json:"bestseller"`
	NewArrival  sql.NullBool    `json:"new_arrival"`
	Featured    sql.NullBool    `json:"featured"`
	Trending    sql.NullBool    `json:"trending"`
	CreatedAt   sql.NullTime    `json:"created_at"`
	UpdatedAt   sql.NullTime    `json:"updated_at"`
}

type Review struct {
	ID            string         `json:"id"`
	ProductID     string         `json:"product_id"`
	VendorID      string         `json:"vendor_id"`
	UserID        string         `json:"user_id"`
	OrderID       string         `json:"order_id"`
	Rating        int32          `json:"rating"`
	Comment       string         `json:"comment"`
	VendorReply   sql.NullString `json:"vendor_reply"`
	VendorReplyAt sql.NullTime   `json:"vendor_reply_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID        string         `json:"id"`
	FullName  string         `json:"full_name"`
	Email     string         `json:"email"`
	Phone     string         `json:"phone"`
	Password  string         `json:"password"`
	Role      UsersRole      `json:"role"`
	Avatar    sql.NullString `json:"avatar"`
	Disabled  sql.NullBool   `json:"disabled"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Vendor struct {
	ID            string           `json:"id"`
	UserID        string           `json:"user_id"`
	StoreName     string           `json:"store_name"`
	Slug          string           `json:"slug"`
	Description   sql.NullString   `json:"description"`
	Logo          string           `json:"logo"`
	Banner        sql.NullString   `json:"banner"`
	ContactPhone  string           `json:"contact_phone"`
	BusinessEmail string           `json:"business_email"`
	Country       string           `json:"country"`
	City          string           `json:"city"`
	SocialLinks   *json.RawMessage `json:"social_links"`
	Categories    json.RawMessage  `json:"categories"`
	Rating        sql.NullString   `json:"rating"`
	TotalSales    sql.NullString   `json:"total_sales"`
	ProductCount  sql.NullInt32    `json:"product_count"`
	Suspended     sql.NullBool     `json:"suspended"`
	IsFeatured    sql.NullBool     `json:"is_featured"`
	CreatedAt     sql.NullTime     `json:"created_at"`
	UpdatedAt     sql.NullTime     `json:"updated_at"`
}

type VendorApplication struct {
	ID                  string                   `json:"id"`
	UserID              string                   `json:"user_id"`
	StoreName           string                   `json:"store_name"`
	BusinessDescription string                   `json:"business_description"`
	Logo                string                   `json:"logo"`
	BusinessEmail       string                   `json:"business_email"`
	ContactPhone        string                   `json:"contact_phone"`
	Country             string                   `json:"country"`
	City                string                   `json:"city"`
	RegistrationNumber  string                   `json:"registration_number"`
	Categories          json.RawMessage          `json:"categories"`
	RiskStatus          sql.NullString           `json:"risk_status"`
	Status              VendorApplicationsStatus `json:"status"`
	ReviewNote          sql.NullString           `json:"review_note"`
	SubmittedAt         sql.NullTime             `json:"submitted_at"`
	ReviewedAt          sql.NullTime             `json:"reviewed_at"`
	CreatedAt           sql.NullTime             `json:"created_at"`
	UpdatedAt           sql.NullTime             `json:"updated_at"`
}

type PasswordResetToken struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type VendorSubscription struct {
	ID            string                  `json:"id"`
	VendorID      string                  `json:"vendor_id"`
	Plan          VendorSubscriptionsPlan `json:"plan"`
	AmountPaid    string                  `json:"amount_paid"`
	PaymentMethod string                  `json:"payment_method"`
	StartedAt     time.Time               `json:"started_at"`
	ExpiresAt     time.Time               `json:"expires_at"`
	Active        sql.NullBool            `json:"active"`
	CreatedAt     sql.NullTime            `json:"created_at"`
	UpdatedAt     sql.NullTime            `json:"updated_at"`
}
