// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
)

const archiveProduct = `-- name: ArchiveProduct :exec
UPDATE products SET status = 'archived' WHERE id = ? AND vendor_id = ?
`

type ArchiveProductParams struct {
	ID       string `json:"id"`
	VendorID string `json:"vendor_id"`
}

func (q *Queries) ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error {
	_, err := q.db.ExecContext(ctx, archiveProduct, arg.ID, arg.VendorID)
	return err
}

const countAllProducts = `-- name: CountAllProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountAllProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutOfStockByVendor = `-- name: CountOutOfStockByVendor :one
SELECT COUNT(*) FROM products WHERE vendor_id = ? AND stock = 0
`

func (q *Queries) CountOutOfStockByVendor(ctx context.Context, vendorID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOutOfStockByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingProducts = `-- name: CountPendingProducts :one
SELECT COUNT(*) FROM products WHERE status = 'pending'
`

func (q *Queries) CountPendingProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminProducts = `-- name: CountAdminProducts :one
SELECT COUNT(*) FROM products WHERE status != 'archived'
`

func (q *Queries) CountAdminProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByVendor = `-- name: CountProductsByVendor :one
SELECT COUNT(*) FROM products WHERE vendor_id = ?
`

func (q *Queries) CountProductsByVendor(ctx context.Context, vendorID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT COUNT(*) FROM products
WHERE status = 'active'
  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%') OR description LIKE CONCAT('%', ?, '%') OR brand LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR category = ?)
  AND (? IS NULL OR subcategory = ?)
  AND (? IS NULL OR brand = ?)
  AND (? IS NULL OR gender = ?)
  AND (? IS NULL OR vendor_id = ?)
  AND (? IS NULL OR JSON_CONTAINS(sizes, JSON_QUOTE(?)))
  AND (? IS NULL OR JSON_SEARCH(colors, 'one', ?, NULL, '$[*].name') IS NOT NULL)
  AND (? IS NULL OR price >= ?)
  AND (? IS NULL OR price <= ?)
  AND (? IS NULL OR rating >= ?)
  AND (? = false OR featured = true)
  AND (? = false OR trending = true)
  AND (? = false OR discount > 0)
`

type CountSearchProductsParams struct {
	Q            interface{}        `json:"q"`
	Category     sql.NullString     `json:"category"`
	Subcategory  sql.NullString     `json:"subcategory"`
	Brand        sql.NullString     `json:"brand"`
	Gender       NullProductsGender `json:"gender"`
	VendorID     sql.NullString     `json:"vendor_id"`
	Size         sql.NullString     `json:"size"`
	Color        sql.NullString     `json:"color"`
	MinPrice     sql.NullString     `json:"min_price"`
	MaxPrice     sql.NullString     `json:"max_price"`
	MinRating    sql.NullString     `json:"min_rating"`
	FeaturedOnly interface{}        `json:"featured_only"`
	TrendingOnly interface{}        `json:"trending_only"`
	OnSaleOnly   interface{}        `json:"on_sale_only"`
}

func (q *Queries) CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchProducts,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Category,
		arg.Category,
		arg.Subcategory,
		arg.Subcategory,
		arg.Brand,
		arg.Brand,
		arg.Gender,
		arg.Gender,
		arg.VendorID,
		arg.VendorID,
		arg.Size,
		arg.Size,
		arg.Color,
		arg.Color,
		arg.MinPrice,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MaxPrice,
		arg.MinRating,
		arg.MinRating,
		arg.FeaturedOnly,
		arg.TrendingOnly,
		arg.OnSaleOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVendorProducts = `-- name: CountVendorProducts :one
SELECT COUNT(*) FROM products WHERE vendor_id = ?
`

func (q *Queries) CountVendorProducts(ctx context.Context, vendorID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVendorProducts, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (
  id, vendor_id, name, description, brand, category, subcategory, gender,
  price, discount, images, colors, sizes, sku, stock, status,
  bestseller, new_arrival, featured, trending
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?, ?)
`

type CreateProductParams struct {
	ID          string          `json:"id"`
	VendorID    string          `json:"vendor_id"`
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Brand       string          `json:"brand"`
	Category    string          `json:"category"`
	Subcategory string          `json:"subcategory"`
	Gender      ProductsGender  `json:"gender"`
	Price       string          `json:"price"`
	Discount    sql.NullString  `json:"discount"`
	Images      json.RawMessage `json:"images"`
	Colors      json.RawMessage `json:"colors"`
	Sizes       json.RawMessage `json:"sizes"`
	Sku         string          `json:"sku"`
	Stock       int32           `json:"stock"`
	Bestseller  sql.NullBool    `json:"bestseller"`
	NewArrival  sql.NullBool    `json:"new_arrival"`
	Featured    sql.NullBool    `json:"featured"`
	Trending    sql.NullBool    `json:"trending"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.VendorID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Category,
		arg.Subcategory,
		arg.Gender,
		arg.Price,
		arg.Discount,
		arg.Images,
		arg.Colors,
		arg.Sizes,
		arg.Sku,
		arg.Stock,
		arg.Bestseller,
		arg.NewArrival,
		arg.Featured,
		arg.Trending,
	)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE id = ? AND status != 'archived' LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Category,
		&i.Subcategory,
		&i.Gender,
		&i.Price,
		&i.Discount,
		&i.Images,
		&i.Colors,
		&i.Sizes,
		&i.Sku,
		&i.Stock,
		&i.Rating,
		&i.ReviewCount,
		&i.Status,
		&i.Bestseller,
		&i.NewArrival,
		&i.Featured,
		&i.Trending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRandomRelatedProducts = `-- name: ListRandomRelatedProducts :many
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active' AND id != ?
ORDER BY RAND()
LIMIT ?
`

type ListRandomRelatedProductsParams struct {
	ID    string `json:"id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListRandomRelatedProducts(ctx context.Context, arg ListRandomRelatedProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listRandomRelatedProducts, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Gender,
			&i.Price,
			&i.Discount,
			&i.Images,
			&i.Colors,
			&i.Sizes,
			&i.Sku,
			&i.Stock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByIDAny = `-- name: GetProductByIDAny :one
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE id = ? LIMIT 1
`

func (q *Queries) GetProductByIDAny(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByIDAny, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Category,
		&i.Subcategory,
		&i.Gender,
		&i.Price,
		&i.Discount,
		&i.Images,
		&i.Colors,
		&i.Sizes,
		&i.Sku,
		&i.Stock,
		&i.Rating,
		&i.ReviewCount,
		&i.Status,
		&i.Bestseller,
		&i.NewArrival,
		&i.Featured,
		&i.Trending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByVendor = `-- name: GetProductByVendor :one
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE id = ? AND vendor_id = ? LIMIT 1
`

type GetProductByVendorParams struct {
	ID       string `json:"id"`
	VendorID string `json:"vendor_id"`
}

func (q *Queries) GetProductByVendor(ctx context.Context, arg GetProductByVendorParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByVendor, arg.ID, arg.VendorID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Category,
		&i.Subcategory,
		&i.Gender,
		&i.Price,
		&i.Discount,
		&i.Images,
		&i.Colors,
		&i.Sizes,
		&i.Sku,
		&i.Stock,
		&i.Rating,
		&i.ReviewCount,
		&i.Status,
		&i.Bestseller,
		&i.NewArrival,
		&i.Featured,
		&i.Trending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductPriceRange = `-- name: GetProductPriceRange :one
SELECT COALESCE(MIN(price), 0) AS min_price, COALESCE(MAX(price), 0) AS max_price
FROM products WHERE status = 'active'
`

type GetProductPriceRangeRow struct {
	MinPrice interface{} `json:"min_price"`
	MaxPrice interface{} `json:"max_price"`
}

func (q *Queries) GetProductPriceRange(ctx context.Context) (GetProductPriceRangeRow, error) {
	row := q.db.QueryRowContext(ctx, getProductPriceRange)
	var i GetProductPriceRangeRow
	err := row.Scan(&i.MinPrice, &i.MaxPrice)
	return i, err
}

const listDistinctBrands = `-- name: ListDistinctBrands :many
SELECT DISTINCT brand FROM products WHERE status = 'active' ORDER BY brand
`

func (q *Queries) ListDistinctBrands(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var brand string
		if err := rows.Scan(&brand); err != nil {
			return nil, err
		}
		items = append(items, brand)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCategories = `-- name: ListDistinctCategories :many
SELECT DISTINCT category FROM products WHERE status = 'active' ORDER BY category
`

func (q *Queries) ListDistinctCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctColors = `-- name: ListDistinctColors :many
SELECT DISTINCT jt.color_name AS color_name
FROM products p
JOIN JSON_TABLE(
  COALESCE(p.colors, '[]'),
  '$[*]' COLUMNS (color_name VARCHAR(100) PATH '$.name')
) AS jt
WHERE p.status = 'active' AND jt.color_name IS NOT NULL AND jt.color_name != ''
ORDER BY color_name
`

func (q *Queries) ListDistinctColors(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctColors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var colorName string
		if err := rows.Scan(&colorName); err != nil {
			return nil, err
		}
		items = append(items, colorName)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSizes = `-- name: ListDistinctSizes :many
SELECT DISTINCT jt.size_val AS size_val
FROM products p
JOIN JSON_TABLE(
  COALESCE(p.sizes, '[]'),
  '$[*]' COLUMNS (size_val VARCHAR(20) PATH '$')
) AS jt
WHERE p.status = 'active' AND jt.size_val IS NOT NULL AND jt.size_val != ''
ORDER BY size_val
`

func (q *Queries) ListDistinctSizes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var sizeVal string
		if err := rows.Scan(&sizeVal); err != nil {
			return nil, err
		}
		items = append(items, sizeVal)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSubcategories = `-- name: ListDistinctSubcategories :many
SELECT DISTINCT subcategory FROM products WHERE status = 'active' ORDER BY subcategory
`

func (q *Queries) ListDistinctSubcategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctSubcategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var subcategory string
		if err := rows.Scan(&subcategory); err != nil {
			return nil, err
		}
		items = append(items, subcategory)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockByVendor = `-- name: ListLowStockByVendor :many
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE vendor_id = ? AND stock > 0 AND stock <= 10
`

func (q *Queries) ListLowStockByVendor(ctx context.Context, vendorID string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listLowStockByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Gender,
			&i.Price,
			&i.Discount,
			&i.Images,
			&i.Colors,
			&i.Sizes,
			&i.Sku,
			&i.Stock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProducts = `-- name: ListPendingProducts :many
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE status = 'pending'
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPendingProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingProducts(ctx context.Context, arg ListPendingProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listPendingProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Gender,
			&i.Price,
			&i.Discount,
			&i.Images,
			&i.Colors,
			&i.Sizes,
			&i.Sku,
			&i.Stock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminProducts = `-- name: ListAdminProducts :many
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE status != 'archived'
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAdminProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdminProducts(ctx context.Context, arg ListAdminProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listAdminProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Gender,
			&i.Price,
			&i.Discount,
			&i.Images,
			&i.Colors,
			&i.Sizes,
			&i.Sku,
			&i.Stock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductIDsByVendor = `-- name: ListProductIDsByVendor :many
SELECT id FROM products WHERE vendor_id = ?
`

func (q *Queries) ListProductIDsByVendor(ctx context.Context, vendorID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProductIDsByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByVendor = `-- name: ListProductsByVendor :many
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE vendor_id = ?
`

func (q *Queries) ListProductsByVendor(ctx context.Context, vendorID string) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Gender,
			&i.Price,
			&i.Discount,
			&i.Images,
			&i.Colors,
			&i.Sizes,
			&i.Sku,
			&i.Stock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorProducts = `-- name: ListVendorProducts :many
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE vendor_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListVendorProductsParams struct {
	VendorID string `json:"vendor_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListVendorProducts(ctx context.Context, arg ListVendorProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listVendorProducts, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Gender,
			&i.Price,
			&i.Discount,
			&i.Images,
			&i.Colors,
			&i.Sizes,
			&i.Sku,
			&i.Stock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderateProduct = `-- name: ModerateProduct :exec
UPDATE products SET status = ? WHERE id = ?
`

type ModerateProductParams struct {
	Status ProductsStatus `json:"status"`
	ID     string         `json:"id"`
}

func (q *Queries) ModerateProduct(ctx context.Context, arg ModerateProductParams) error {
	_, err := q.db.ExecContext(ctx, moderateProduct, arg.Status, arg.ID)
	return err
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, vendor_id, name, description, brand, category, subcategory, gender, price, discount, images, colors, sizes, sku, stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active'
  AND (? IS NULL OR name LIKE CONCAT('%', ?, '%') OR description LIKE CONCAT('%', ?, '%') OR brand LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR category = ?)
  AND (? IS NULL OR subcategory = ?)
  AND (? IS NULL OR brand = ?)
  AND (? IS NULL OR gender = ?)
  AND (? IS NULL OR vendor_id = ?)
  AND (? IS NULL OR JSON_CONTAINS(sizes, JSON_QUOTE(?)))
  AND (? IS NULL OR JSON_SEARCH(colors, 'one', ?, NULL, '$[*].name') IS NOT NULL)
  AND (? IS NULL OR price >= ?)
  AND (? IS NULL OR price <= ?)
  AND (? IS NULL OR rating >= ?)
  AND (? = false OR featured = true)
  AND (? = false OR trending = true)
  AND (? = false OR discount > 0)
ORDER BY
  CASE WHEN ? = 'popular' THEN review_count END DESC,
  CASE WHEN ? = 'rating' THEN rating END DESC,
  CASE WHEN ? = 'trending' THEN trending END DESC, review_count DESC, rating DESC,
  CASE WHEN ? = 'bestsellers' THEN review_count END DESC,
  CASE WHEN ? = 'price-asc' THEN price END ASC,
  CASE WHEN ? = 'price-desc' THEN price END DESC,
  created_at DESC
LIMIT ? OFFSET ?
`

type SearchProductsParams struct {
	Q            interface{}        `json:"q"`
	Category     sql.NullString     `json:"category"`
	Subcategory  sql.NullString     `json:"subcategory"`
	Brand        sql.NullString     `json:"brand"`
	Gender       NullProductsGender `json:"gender"`
	VendorID     sql.NullString     `json:"vendor_id"`
	Size         sql.NullString     `json:"size"`
	Color        sql.NullString     `json:"color"`
	MinPrice     sql.NullString     `json:"min_price"`
	MaxPrice     sql.NullString     `json:"max_price"`
	MinRating    sql.NullString     `json:"min_rating"`
	FeaturedOnly interface{}        `json:"featured_only"`
	TrendingOnly interface{}        `json:"trending_only"`
	OnSaleOnly   interface{}        `json:"on_sale_only"`
	SortBy       interface{}        `json:"sort_by"`
	Limit        int32              `json:"limit"`
	Offset       int32              `json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Category,
		arg.Category,
		arg.Subcategory,
		arg.Subcategory,
		arg.Brand,
		arg.Brand,
		arg.Gender,
		arg.Gender,
		arg.VendorID,
		arg.VendorID,
		arg.Size,
		arg.Size,
		arg.Color,
		arg.Color,
		arg.MinPrice,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MaxPrice,
		arg.MinRating,
		arg.MinRating,
		arg.FeaturedOnly,
		arg.TrendingOnly,
		arg.OnSaleOnly,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.Subcategory,
			&i.Gender,
			&i.Price,
			&i.Discount,
			&i.Images,
			&i.Colors,
			&i.Sizes,
			&i.Sku,
			&i.Stock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = COALESCE(?, name),
    description = COALESCE(?, description),
    brand = COALESCE(?, brand),
    category = COALESCE(?, category),
    subcategory = COALESCE(?, subcategory),
    gender = COALESCE(?, gender),
    price = COALESCE(?, price),
    stock = COALESCE(?, stock),
    discount = COALESCE(?, discount),
    sizes = COALESCE(?, sizes),
    colors = COALESCE(?, colors),
    images = COALESCE(?, images)
WHERE id = ? AND vendor_id = ?
`

type UpdateProductParams struct {
	Name        sql.NullString         `json:"name"`
	Description sql.NullString         `json:"description"`
	Brand       sql.NullString         `json:"brand"`
	Category    sql.NullString         `json:"category"`
	Subcategory sql.NullString         `json:"subcategory"`
	Gender      NullProductsGender     `json:"gender"`
	Price       sql.NullString         `json:"price"`
	Stock       sql.NullInt32          `json:"stock"`
	Discount    sql.NullString         `json:"discount"`
	Sizes       json.RawMessage        `json:"sizes"`
	Colors      json.RawMessage        `json:"colors"`
	Images      json.RawMessage        `json:"images"`
	ID          string                 `json:"id"`
	VendorID    string                 `json:"vendor_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Category,
		arg.Subcategory,
		arg.Gender,
		arg.Price,
		arg.Stock,
		arg.Discount,
		arg.Sizes,
		arg.Colors,
		arg.Images,
		arg.ID,
		arg.VendorID,
	)
	return err
}

const updateProductRating = `-- name: UpdateProductRating :exec
UPDATE products SET rating = ?, review_count = ? WHERE id = ?
`

type UpdateProductRatingParams struct {
	Rating      sql.NullString `json:"rating"`
	ReviewCount sql.NullInt32  `json:"review_count"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateProductRating, arg.Rating, arg.ReviewCount, arg.ID)
	return err
}
