// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"
)

const countAllVendors = `-- name: CountAllVendors :one
SELECT COUNT(*) FROM vendors
`

func (q *Queries) CountAllVendors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllVendors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM users WHERE role = 'CUSTOMER'
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listTopVendorsForAnalytics = `-- name: ListTopVendorsForAnalytics :many
SELECT id, user_id, store_name, slug, description, logo, banner, contact_phone, business_email, country, city, shipping_cost, free_shipping_threshold, social_links, commission_rate, rating, verified, suspended, is_featured, created_at, updated_at FROM vendors ORDER BY rating DESC, created_at DESC LIMIT ?
`

func (q *Queries) ListTopVendorsForAnalytics(ctx context.Context, limit int32) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listTopVendorsForAnalytics, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.Slug,
			&i.Description,
			&i.Logo,
			&i.Banner,
			&i.ContactPhone,
			&i.BusinessEmail,
			&i.Country,
			&i.City,
			&i.ShippingCost,
			&i.FreeShippingThreshold,
			&i.SocialLinks,
			&i.CommissionRate,
			&i.Rating,
			&i.Verified,
			&i.Suspended,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
