// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const addWishlistItemForSession = `-- name: AddWishlistItemForSession :exec
INSERT IGNORE INTO wishlists (id, user_id, session_key, product_id, expires_at)
VALUES (?, NULL, ?, ?, ?)
`

type AddWishlistItemForSessionParams struct {
	ID         types.BinaryUUID `json:"id"`
	SessionKey sql.NullString   `json:"session_key"`
	ProductID  types.BinaryUUID `json:"product_id"`
	ExpiresAt  sql.NullTime     `json:"expires_at"`
}

func (q *Queries) AddWishlistItemForSession(ctx context.Context, arg AddWishlistItemForSessionParams) error {
	_, err := q.db.ExecContext(ctx, addWishlistItemForSession,
		arg.ID,
		arg.SessionKey,
		arg.ProductID,
		arg.ExpiresAt,
	)
	return err
}

const addWishlistItemForUser = `-- name: AddWishlistItemForUser :exec
INSERT IGNORE INTO wishlists (id, user_id, session_key, product_id, expires_at)
VALUES (?, ?, NULL, ?, NULL)
`

type AddWishlistItemForUserParams struct {
	ID        types.BinaryUUID  `json:"id"`
	UserID    *types.BinaryUUID `json:"user_id"`
	ProductID types.BinaryUUID  `json:"product_id"`
}

func (q *Queries) AddWishlistItemForUser(ctx context.Context, arg AddWishlistItemForUserParams) error {
	_, err := q.db.ExecContext(ctx, addWishlistItemForUser, arg.ID, arg.UserID, arg.ProductID)
	return err
}

const assignGuestCartToUser = `-- name: AssignGuestCartToUser :exec
UPDATE carts
SET user_id = ?, session_key = NULL, expires_at = NULL, updated_at = NOW()
WHERE session_key = ?
`

type AssignGuestCartToUserParams struct {
	UserID     *types.BinaryUUID `json:"user_id"`
	SessionKey sql.NullString    `json:"session_key"`
}

func (q *Queries) AssignGuestCartToUser(ctx context.Context, arg AssignGuestCartToUserParams) error {
	_, err := q.db.ExecContext(ctx, assignGuestCartToUser, arg.UserID, arg.SessionKey)
	return err
}

const clearCartItems = `-- name: ClearCartItems :exec
DELETE FROM cart_items WHERE cart_id = ?
`

func (q *Queries) ClearCartItems(ctx context.Context, cartID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, clearCartItems, cartID)
	return err
}

const createCart = `-- name: CreateCart :exec
INSERT INTO carts (id, user_id, session_key, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateCartParams struct {
	ID         types.BinaryUUID  `json:"id"`
	UserID     *types.BinaryUUID `json:"user_id"`
	SessionKey sql.NullString    `json:"session_key"`
	ExpiresAt  sql.NullTime      `json:"expires_at"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) error {
	_, err := q.db.ExecContext(ctx, createCart,
		arg.ID,
		arg.UserID,
		arg.SessionKey,
		arg.ExpiresAt,
	)
	return err
}

const createCartItem = `-- name: CreateCartItem :exec
INSERT INTO cart_items (id, cart_id, variant_id, quantity)
VALUES (?, ?, ?, ?)
`

type CreateCartItemParams struct {
	ID        types.BinaryUUID `json:"id"`
	CartID    types.BinaryUUID `json:"cart_id"`
	VariantID types.BinaryUUID `json:"variant_id"`
	Quantity  int32            `json:"quantity"`
}

func (q *Queries) CreateCartItem(ctx context.Context, arg CreateCartItemParams) error {
	_, err := q.db.ExecContext(ctx, createCartItem,
		arg.ID,
		arg.CartID,
		arg.VariantID,
		arg.Quantity,
	)
	return err
}

const deleteCartByID = `-- name: DeleteCartByID :exec
DELETE FROM carts WHERE id = ?
`

func (q *Queries) DeleteCartByID(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deleteCartByID, id)
	return err
}

const deleteCartBySessionKey = `-- name: DeleteCartBySessionKey :exec
DELETE FROM carts WHERE session_key = ?
`

func (q *Queries) DeleteCartBySessionKey(ctx context.Context, sessionKey sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteCartBySessionKey, sessionKey)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items WHERE id = ?
`

func (q *Queries) DeleteCartItem(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deleteCartItem, id)
	return err
}

const deleteWishlistBySessionKey = `-- name: DeleteWishlistBySessionKey :exec
DELETE FROM wishlists WHERE session_key = ?
`

func (q *Queries) DeleteWishlistBySessionKey(ctx context.Context, sessionKey sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteWishlistBySessionKey, sessionKey)
	return err
}

const getCartBySessionKey = `-- name: GetCartBySessionKey :one
SELECT id, user_id, session_key, expires_at, created_at, updated_at FROM carts WHERE session_key = ? LIMIT 1
`

func (q *Queries) GetCartBySessionKey(ctx context.Context, sessionKey sql.NullString) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartBySessionKey, sessionKey)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT id, user_id, session_key, expires_at, created_at, updated_at FROM carts WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID *types.BinaryUUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByCartAndVariant = `-- name: GetCartItemByCartAndVariant :one
SELECT id, cart_id, variant_id, quantity, added_at, updated_at FROM cart_items WHERE cart_id = ? AND variant_id = ? LIMIT 1
`

type GetCartItemByCartAndVariantParams struct {
	CartID    types.BinaryUUID `json:"cart_id"`
	VariantID types.BinaryUUID `json:"variant_id"`
}

func (q *Queries) GetCartItemByCartAndVariant(ctx context.Context, arg GetCartItemByCartAndVariantParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByCartAndVariant, arg.CartID, arg.VariantID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.VariantID,
		&i.Quantity,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByProductSizeColor = `-- name: GetVariantByProductSizeColor :one
SELECT id, product_id, size, color, color_hex, price, discount, effective_price, stock, sku, deleted_at, created_at, updated_at FROM product_variants
WHERE product_id = ? AND size = ? AND color = ? AND deleted_at IS NULL
LIMIT 1
`

type GetVariantByProductSizeColorParams struct {
	ProductID types.BinaryUUID `json:"product_id"`
	Size      string           `json:"size"`
	Color     string           `json:"color"`
}

func (q *Queries) GetVariantByProductSizeColor(ctx context.Context, arg GetVariantByProductSizeColorParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getVariantByProductSizeColor, arg.ProductID, arg.Size, arg.Color)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.Color,
		&i.ColorHex,
		&i.Price,
		&i.Discount,
		&i.EffectivePrice,
		&i.Stock,
		&i.Sku,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItemsByCartID = `-- name: ListCartItemsByCartID :many
SELECT
  ci.id, ci.cart_id, ci.variant_id, ci.quantity, ci.added_at, ci.updated_at,
  pv.product_id AS variant_product_id,
  pv.size AS variant_size,
  pv.color AS variant_color
FROM cart_items ci
INNER JOIN product_variants pv ON pv.id = ci.variant_id AND pv.deleted_at IS NULL
WHERE ci.cart_id = ?
ORDER BY ci.added_at ASC
`

type ListCartItemsByCartIDRow struct {
	CartItem         CartItem         `json:"cart_item"`
	VariantProductID types.BinaryUUID `json:"variant_product_id"`
	VariantSize      string           `json:"variant_size"`
	VariantColor     string           `json:"variant_color"`
}

func (q *Queries) ListCartItemsByCartID(ctx context.Context, cartID types.BinaryUUID) ([]ListCartItemsByCartIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listCartItemsByCartID, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartItemsByCartIDRow{}
	for rows.Next() {
		var i ListCartItemsByCartIDRow
		if err := rows.Scan(
			&i.CartItem.ID,
			&i.CartItem.CartID,
			&i.CartItem.VariantID,
			&i.CartItem.Quantity,
			&i.CartItem.AddedAt,
			&i.CartItem.UpdatedAt,
			&i.VariantProductID,
			&i.VariantSize,
			&i.VariantColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistBySessionKey = `-- name: ListWishlistBySessionKey :many
SELECT product_id FROM wishlists WHERE session_key = ? ORDER BY created_at ASC
`

func (q *Queries) ListWishlistBySessionKey(ctx context.Context, sessionKey sql.NullString) ([]types.BinaryUUID, error) {
	rows, err := q.db.QueryContext(ctx, listWishlistBySessionKey, sessionKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.BinaryUUID{}
	for rows.Next() {
		var product_id types.BinaryUUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWishlistByUser = `-- name: ListWishlistByUser :many
SELECT product_id FROM wishlists WHERE user_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListWishlistByUser(ctx context.Context, userID *types.BinaryUUID) ([]types.BinaryUUID, error) {
	rows, err := q.db.QueryContext(ctx, listWishlistByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.BinaryUUID{}
	for rows.Next() {
		var product_id types.BinaryUUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWishlistItemBySession = `-- name: RemoveWishlistItemBySession :exec
DELETE FROM wishlists WHERE session_key = ? AND product_id = ?
`

type RemoveWishlistItemBySessionParams struct {
	SessionKey sql.NullString   `json:"session_key"`
	ProductID  types.BinaryUUID `json:"product_id"`
}

func (q *Queries) RemoveWishlistItemBySession(ctx context.Context, arg RemoveWishlistItemBySessionParams) error {
	_, err := q.db.ExecContext(ctx, removeWishlistItemBySession, arg.SessionKey, arg.ProductID)
	return err
}

const removeWishlistItemByUser = `-- name: RemoveWishlistItemByUser :exec
DELETE FROM wishlists WHERE user_id = ? AND product_id = ?
`

type RemoveWishlistItemByUserParams struct {
	UserID    *types.BinaryUUID `json:"user_id"`
	ProductID types.BinaryUUID  `json:"product_id"`
}

func (q *Queries) RemoveWishlistItemByUser(ctx context.Context, arg RemoveWishlistItemByUserParams) error {
	_, err := q.db.ExecContext(ctx, removeWishlistItemByUser, arg.UserID, arg.ProductID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items SET quantity = ?, updated_at = NOW() WHERE id = ?
`

type UpdateCartItemQuantityParams struct {
	Quantity int32            `json:"quantity"`
	ID       types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateCartItemQuantity, arg.Quantity, arg.ID)
	return err
}
