// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commerce.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const addCollectionProduct = `-- name: AddCollectionProduct :exec
INSERT IGNORE INTO collection_products (collection_id, product_id, sort_order) VALUES (?, ?, ?)
`

type AddCollectionProductParams struct {
	CollectionID types.BinaryUUID `json:"collection_id"`
	ProductID    types.BinaryUUID `json:"product_id"`
	SortOrder    int32            `json:"sort_order"`
}

func (q *Queries) AddCollectionProduct(ctx context.Context, arg AddCollectionProductParams) error {
	_, err := q.db.ExecContext(ctx, addCollectionProduct, arg.CollectionID, arg.ProductID, arg.SortOrder)
	return err
}

const addPromotionProduct = `-- name: AddPromotionProduct :exec
INSERT IGNORE INTO promotion_products (promotion_id, product_id) VALUES (?, ?)
`

type AddPromotionProductParams struct {
	PromotionID types.BinaryUUID `json:"promotion_id"`
	ProductID   types.BinaryUUID `json:"product_id"`
}

func (q *Queries) AddPromotionProduct(ctx context.Context, arg AddPromotionProductParams) error {
	_, err := q.db.ExecContext(ctx, addPromotionProduct, arg.PromotionID, arg.ProductID)
	return err
}

const countAllCollections = `-- name: CountAllCollections :one
SELECT COUNT(*) FROM collections
`

func (q *Queries) CountAllCollections(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllCollections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllCoupons = `-- name: CountAllCoupons :one
SELECT COUNT(*) FROM coupons
`

func (q *Queries) CountAllCoupons(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllCoupons)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllPromotions = `-- name: CountAllPromotions :one
SELECT COUNT(*) FROM promotions
`

func (q *Queries) CountAllPromotions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllPromotions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCouponUsesByUser = `-- name: CountCouponUsesByUser :one
SELECT COUNT(*) FROM coupon_uses WHERE coupon_id = ? AND user_id = ?
`

type CountCouponUsesByUserParams struct {
	CouponID types.BinaryUUID `json:"coupon_id"`
	UserID   types.BinaryUUID `json:"user_id"`
}

func (q *Queries) CountCouponUsesByUser(ctx context.Context, arg CountCouponUsesByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCouponUsesByUser, arg.CouponID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :exec
INSERT INTO collections (id, name, slug, description, image, active, sort_order, starts_at, ends_at, created_by)
VALUES (?, ?, ?, ?, ?, true, ?, ?, ?, ?)
`

type CreateCollectionParams struct {
	ID          types.BinaryUUID  `json:"id"`
	Name        string            `json:"name"`
	Slug        string            `json:"slug"`
	Description sql.NullString    `json:"description"`
	Image       sql.NullString    `json:"image"`
	SortOrder   int32             `json:"sort_order"`
	StartsAt    sql.NullTime      `json:"starts_at"`
	EndsAt      sql.NullTime      `json:"ends_at"`
	CreatedBy   *types.BinaryUUID `json:"created_by"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, createCollection,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Image,
		arg.SortOrder,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	return err
}

const createCoupon = `-- name: CreateCoupon :exec
INSERT INTO coupons (
  id, code, type, value, min_order_amount, max_discount, max_uses, per_user_limit, vendor_id, active, starts_at, expires_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, true, ?, ?)
`

type CreateCouponParams struct {
	ID             types.BinaryUUID  `json:"id"`
	Code           string            `json:"code"`
	Type           CouponsType       `json:"type"`
	Value          string            `json:"value"`
	MinOrderAmount string            `json:"min_order_amount"`
	MaxDiscount    sql.NullString    `json:"max_discount"`
	MaxUses        sql.NullInt32     `json:"max_uses"`
	PerUserLimit   int32             `json:"per_user_limit"`
	VendorID       *types.BinaryUUID `json:"vendor_id"`
	StartsAt       sql.NullTime      `json:"starts_at"`
	ExpiresAt      sql.NullTime      `json:"expires_at"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) error {
	_, err := q.db.ExecContext(ctx, createCoupon,
		arg.ID,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.MinOrderAmount,
		arg.MaxDiscount,
		arg.MaxUses,
		arg.PerUserLimit,
		arg.VendorID,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	return err
}

const createCouponUse = `-- name: CreateCouponUse :exec
INSERT INTO coupon_uses (id, coupon_id, user_id, order_id, discount_amount)
VALUES (?, ?, ?, ?, ?)
`

type CreateCouponUseParams struct {
	ID             types.BinaryUUID `json:"id"`
	CouponID       types.BinaryUUID `json:"coupon_id"`
	UserID         types.BinaryUUID `json:"user_id"`
	OrderID        types.BinaryUUID `json:"order_id"`
	DiscountAmount string           `json:"discount_amount"`
}

func (q *Queries) CreateCouponUse(ctx context.Context, arg CreateCouponUseParams) error {
	_, err := q.db.ExecContext(ctx, createCouponUse,
		arg.ID,
		arg.CouponID,
		arg.UserID,
		arg.OrderID,
		arg.DiscountAmount,
	)
	return err
}

const createDeliveryZone = `-- name: CreateDeliveryZone :exec
INSERT INTO delivery_zones (id, name, base_cost, estimated_days, active)
VALUES (?, ?, ?, ?, true)
`

type CreateDeliveryZoneParams struct {
	ID            types.BinaryUUID `json:"id"`
	Name          string           `json:"name"`
	BaseCost      string           `json:"base_cost"`
	EstimatedDays string           `json:"estimated_days"`
}

func (q *Queries) CreateDeliveryZone(ctx context.Context, arg CreateDeliveryZoneParams) error {
	_, err := q.db.ExecContext(ctx, createDeliveryZone,
		arg.ID,
		arg.Name,
		arg.BaseCost,
		arg.EstimatedDays,
	)
	return err
}

const createDeliveryZoneArea = `-- name: CreateDeliveryZoneArea :exec
INSERT INTO delivery_zone_areas (id, zone_id, area_type, area_name)
VALUES (?, ?, ?, ?)
`

type CreateDeliveryZoneAreaParams struct {
	ID       types.BinaryUUID          `json:"id"`
	ZoneID   types.BinaryUUID          `json:"zone_id"`
	AreaType DeliveryZoneAreasAreaType `json:"area_type"`
	AreaName string                    `json:"area_name"`
}

func (q *Queries) CreateDeliveryZoneArea(ctx context.Context, arg CreateDeliveryZoneAreaParams) error {
	_, err := q.db.ExecContext(ctx, createDeliveryZoneArea,
		arg.ID,
		arg.ZoneID,
		arg.AreaType,
		arg.AreaName,
	)
	return err
}

const createPromotion = `-- name: CreatePromotion :exec
INSERT INTO promotions (id, name, type, discount_type, discount_value, starts_at, ends_at, active, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, true, ?)
`

type CreatePromotionParams struct {
	ID            types.BinaryUUID       `json:"id"`
	Name          string                 `json:"name"`
	Type          PromotionsType         `json:"type"`
	DiscountType  PromotionsDiscountType `json:"discount_type"`
	DiscountValue string                 `json:"discount_value"`
	StartsAt      time.Time              `json:"starts_at"`
	EndsAt        time.Time              `json:"ends_at"`
	CreatedBy     *types.BinaryUUID      `json:"created_by"`
}

func (q *Queries) CreatePromotion(ctx context.Context, arg CreatePromotionParams) error {
	_, err := q.db.ExecContext(ctx, createPromotion,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.DiscountType,
		arg.DiscountValue,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	return err
}

const deleteCollectionProducts = `-- name: DeleteCollectionProducts :exec
DELETE FROM collection_products WHERE collection_id = ?
`

func (q *Queries) DeleteCollectionProducts(ctx context.Context, collectionID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deleteCollectionProducts, collectionID)
	return err
}

const deletePromotionProducts = `-- name: DeletePromotionProducts :exec
DELETE FROM promotion_products WHERE promotion_id = ?
`

func (q *Queries) DeletePromotionProducts(ctx context.Context, promotionID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deletePromotionProducts, promotionID)
	return err
}

const findDeliveryZoneByCity = `-- name: FindDeliveryZoneByCity :one
SELECT dz.id, dz.name, dz.base_cost, dz.estimated_days, dz.active, dz.created_at, dz.updated_at
FROM delivery_zones dz
INNER JOIN delivery_zone_areas dza ON dza.zone_id = dz.id
WHERE dz.active = true AND dza.area_type = 'city' AND LOWER(dza.area_name) = LOWER(?)
LIMIT 1
`

func (q *Queries) FindDeliveryZoneByCity(ctx context.Context, lower string) (DeliveryZone, error) {
	row := q.db.QueryRowContext(ctx, findDeliveryZoneByCity, lower)
	var i DeliveryZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCost,
		&i.EstimatedDays,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, name, slug, description, image, active, sort_order, starts_at, ends_at, created_by, created_at, updated_at FROM collections WHERE id = ? LIMIT 1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id types.BinaryUUID) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Active,
		&i.SortOrder,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionBySlug = `-- name: GetCollectionBySlug :one
SELECT id, name, slug, description, image, active, sort_order, starts_at, ends_at, created_by, created_at, updated_at FROM collections WHERE slug = ? AND active = true LIMIT 1
`

func (q *Queries) GetCollectionBySlug(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionBySlug, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Image,
		&i.Active,
		&i.SortOrder,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, type, value, min_order_amount, max_discount, max_uses, uses_count, per_user_limit, vendor_id, active, starts_at, expires_at, created_at, updated_at FROM coupons WHERE UPPER(code) = UPPER(?) LIMIT 1
`

func (q *Queries) GetCouponByCode(ctx context.Context, upper string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByCode, upper)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxDiscount,
		&i.MaxUses,
		&i.UsesCount,
		&i.PerUserLimit,
		&i.VendorID,
		&i.Active,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCouponByID = `-- name: GetCouponByID :one
SELECT id, code, type, value, min_order_amount, max_discount, max_uses, uses_count, per_user_limit, vendor_id, active, starts_at, expires_at, created_at, updated_at FROM coupons WHERE id = ? LIMIT 1
`

func (q *Queries) GetCouponByID(ctx context.Context, id types.BinaryUUID) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByID, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxDiscount,
		&i.MaxUses,
		&i.UsesCount,
		&i.PerUserLimit,
		&i.VendorID,
		&i.Active,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryZoneByID = `-- name: GetDeliveryZoneByID :one
SELECT id, name, base_cost, estimated_days, active, created_at, updated_at FROM delivery_zones WHERE id = ? LIMIT 1
`

func (q *Queries) GetDeliveryZoneByID(ctx context.Context, id types.BinaryUUID) (DeliveryZone, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryZoneByID, id)
	var i DeliveryZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseCost,
		&i.EstimatedDays,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromotionByID = `-- name: GetPromotionByID :one
SELECT id, name, type, discount_type, discount_value, starts_at, ends_at, active, created_by, created_at, updated_at FROM promotions WHERE id = ? LIMIT 1
`

func (q *Queries) GetPromotionByID(ctx context.Context, id types.BinaryUUID) (Promotion, error) {
	row := q.db.QueryRowContext(ctx, getPromotionByID, id)
	var i Promotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.DiscountType,
		&i.DiscountValue,
		&i.StartsAt,
		&i.EndsAt,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementCouponUses = `-- name: IncrementCouponUses :exec
UPDATE coupons SET uses_count = uses_count + 1 WHERE id = ?
`

func (q *Queries) IncrementCouponUses(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, incrementCouponUses, id)
	return err
}

const listActiveCollections = `-- name: ListActiveCollections :many
SELECT id, name, slug, description, image, active, sort_order, starts_at, ends_at, created_by, created_at, updated_at FROM collections
WHERE active = true
  AND (starts_at IS NULL OR starts_at <= NOW())
  AND (ends_at IS NULL OR ends_at >= NOW())
ORDER BY sort_order, name
`

func (q *Queries) ListActiveCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listActiveCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Image,
			&i.Active,
			&i.SortOrder,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDeliveryZones = `-- name: ListActiveDeliveryZones :many
SELECT id, name, base_cost, estimated_days, active, created_at, updated_at FROM delivery_zones WHERE active = true ORDER BY name
`

func (q *Queries) ListActiveDeliveryZones(ctx context.Context) ([]DeliveryZone, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDeliveryZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryZone{}
	for rows.Next() {
		var i DeliveryZone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseCost,
			&i.EstimatedDays,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePromotions = `-- name: ListActivePromotions :many
SELECT id, name, type, discount_type, discount_value, starts_at, ends_at, active, created_by, created_at, updated_at FROM promotions
WHERE active = true AND starts_at <= NOW() AND ends_at >= NOW()
ORDER BY starts_at DESC
`

func (q *Queries) ListActivePromotions(ctx context.Context) ([]Promotion, error) {
	rows, err := q.db.QueryContext(ctx, listActivePromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Promotion{}
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.DiscountType,
			&i.DiscountValue,
			&i.StartsAt,
			&i.EndsAt,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCollections = `-- name: ListAllCollections :many
SELECT id, name, slug, description, image, active, sort_order, starts_at, ends_at, created_by, created_at, updated_at FROM collections ORDER BY sort_order, name LIMIT ? OFFSET ?
`

type ListAllCollectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllCollections(ctx context.Context, arg ListAllCollectionsParams) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listAllCollections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Image,
			&i.Active,
			&i.SortOrder,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllCoupons = `-- name: ListAllCoupons :many
SELECT id, code, type, value, min_order_amount, max_discount, max_uses, uses_count, per_user_limit, vendor_id, active, starts_at, expires_at, created_at, updated_at FROM coupons ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAllCouponsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllCoupons(ctx context.Context, arg ListAllCouponsParams) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, listAllCoupons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Value,
			&i.MinOrderAmount,
			&i.MaxDiscount,
			&i.MaxUses,
			&i.UsesCount,
			&i.PerUserLimit,
			&i.VendorID,
			&i.Active,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPromotions = `-- name: ListAllPromotions :many
SELECT id, name, type, discount_type, discount_value, starts_at, ends_at, active, created_by, created_at, updated_at FROM promotions ORDER BY starts_at DESC LIMIT ? OFFSET ?
`

type ListAllPromotionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllPromotions(ctx context.Context, arg ListAllPromotionsParams) ([]Promotion, error) {
	rows, err := q.db.QueryContext(ctx, listAllPromotions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Promotion{}
	for rows.Next() {
		var i Promotion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.DiscountType,
			&i.DiscountValue,
			&i.StartsAt,
			&i.EndsAt,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionProductIDs = `-- name: ListCollectionProductIDs :many
SELECT product_id FROM collection_products WHERE collection_id = ? ORDER BY sort_order
`

func (q *Queries) ListCollectionProductIDs(ctx context.Context, collectionID types.BinaryUUID) ([]types.BinaryUUID, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionProductIDs, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.BinaryUUID{}
	for rows.Next() {
		var product_id types.BinaryUUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromotionProductIDs = `-- name: ListPromotionProductIDs :many
SELECT product_id FROM promotion_products WHERE promotion_id = ?
`

func (q *Queries) ListPromotionProductIDs(ctx context.Context, promotionID types.BinaryUUID) ([]types.BinaryUUID, error) {
	rows, err := q.db.QueryContext(ctx, listPromotionProductIDs, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.BinaryUUID{}
	for rows.Next() {
		var product_id types.BinaryUUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCollectionActive = `-- name: SetCollectionActive :exec
UPDATE collections SET active = ? WHERE id = ?
`

type SetCollectionActiveParams struct {
	Active int16            `json:"active"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) SetCollectionActive(ctx context.Context, arg SetCollectionActiveParams) error {
	_, err := q.db.ExecContext(ctx, setCollectionActive, arg.Active, arg.ID)
	return err
}

const setCouponActive = `-- name: SetCouponActive :exec
UPDATE coupons SET active = ? WHERE id = ?
`

type SetCouponActiveParams struct {
	Active int16            `json:"active"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) SetCouponActive(ctx context.Context, arg SetCouponActiveParams) error {
	_, err := q.db.ExecContext(ctx, setCouponActive, arg.Active, arg.ID)
	return err
}

const updateCoupon = `-- name: UpdateCoupon :exec
UPDATE coupons
SET code = ?,
    type = ?,
    value = ?,
    min_order_amount = ?,
    max_discount = ?,
    max_uses = ?,
    per_user_limit = ?,
    starts_at = ?,
    expires_at = ?
WHERE id = ?
`

type UpdateCouponParams struct {
	Code           string           `json:"code"`
	Type           CouponsType      `json:"type"`
	Value          string           `json:"value"`
	MinOrderAmount string           `json:"min_order_amount"`
	MaxDiscount    sql.NullString   `json:"max_discount"`
	MaxUses        sql.NullInt32    `json:"max_uses"`
	PerUserLimit   int32            `json:"per_user_limit"`
	StartsAt       sql.NullTime     `json:"starts_at"`
	ExpiresAt      sql.NullTime     `json:"expires_at"`
	ID             types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateCoupon(ctx context.Context, arg UpdateCouponParams) error {
	_, err := q.db.ExecContext(ctx, updateCoupon,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.MinOrderAmount,
		arg.MaxDiscount,
		arg.MaxUses,
		arg.PerUserLimit,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const setPromotionActive = `-- name: SetPromotionActive :exec
UPDATE promotions SET active = ? WHERE id = ?
`

type SetPromotionActiveParams struct {
	Active int16            `json:"active"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) SetPromotionActive(ctx context.Context, arg SetPromotionActiveParams) error {
	_, err := q.db.ExecContext(ctx, setPromotionActive, arg.Active, arg.ID)
	return err
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE collections
SET name = ?, slug = ?, description = ?, image = ?, sort_order = ?, starts_at = ?, ends_at = ?
WHERE id = ?
`

type UpdateCollectionParams struct {
	Name        string           `json:"name"`
	Slug        string           `json:"slug"`
	Description sql.NullString   `json:"description"`
	Image       sql.NullString   `json:"image"`
	SortOrder   int32            `json:"sort_order"`
	StartsAt    sql.NullTime     `json:"starts_at"`
	EndsAt      sql.NullTime     `json:"ends_at"`
	ID          types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.ExecContext(ctx, updateCollection,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Image,
		arg.SortOrder,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	return err
}

const updatePromotion = `-- name: UpdatePromotion :exec
UPDATE promotions
SET name = ?, type = ?, discount_type = ?, discount_value = ?, starts_at = ?, ends_at = ?
WHERE id = ?
`

type UpdatePromotionParams struct {
	Name          string                 `json:"name"`
	Type          PromotionsType         `json:"type"`
	DiscountType  PromotionsDiscountType `json:"discount_type"`
	DiscountValue string                 `json:"discount_value"`
	StartsAt      time.Time              `json:"starts_at"`
	EndsAt        time.Time              `json:"ends_at"`
	ID            types.BinaryUUID       `json:"id"`
}

func (q *Queries) UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) error {
	_, err := q.db.ExecContext(ctx, updatePromotion,
		arg.Name,
		arg.Type,
		arg.DiscountType,
		arg.DiscountValue,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	return err
}
