// Code generated by sqlc. DO NOT EDIT.
// source: homepage.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const createHomepageBanner = `-- name: CreateHomepageBanner :exec
INSERT INTO homepage_banners (id, title, subtitle, image, link, active, sort_order)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateHomepageBannerParams struct {
	ID        types.BinaryUUID `json:"id"`
	Title     sql.NullString   `json:"title"`
	Subtitle  sql.NullString   `json:"subtitle"`
	Image     string           `json:"image"`
	Link      sql.NullString   `json:"link"`
	Active    int16            `json:"active"`
	SortOrder int32            `json:"sort_order"`
}

func (q *Queries) CreateHomepageBanner(ctx context.Context, arg CreateHomepageBannerParams) error {
	_, err := q.db.ExecContext(ctx, createHomepageBanner,
		arg.ID, arg.Title, arg.Subtitle, arg.Image, arg.Link, arg.Active, arg.SortOrder,
	)
	return err
}

const createHomepageHeroSlide = `-- name: CreateHomepageHeroSlide :exec
INSERT INTO homepage_hero_slides (id, label, title, subtitle, image, link, sort_order, active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHomepageHeroSlideParams struct {
	ID        types.BinaryUUID `json:"id"`
	Label     string           `json:"label"`
	Title     string           `json:"title"`
	Subtitle  sql.NullString   `json:"subtitle"`
	Image     string           `json:"image"`
	Link      string           `json:"link"`
	SortOrder int32            `json:"sort_order"`
	Active    int16            `json:"active"`
}

func (q *Queries) CreateHomepageHeroSlide(ctx context.Context, arg CreateHomepageHeroSlideParams) error {
	_, err := q.db.ExecContext(ctx, createHomepageHeroSlide,
		arg.ID, arg.Label, arg.Title, arg.Subtitle, arg.Image, arg.Link, arg.SortOrder, arg.Active,
	)
	return err
}

const createHomepagePromoItem = `-- name: CreateHomepagePromoItem :exec
INSERT INTO homepage_promo_items (id, title, description, icon, sort_order, active)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateHomepagePromoItemParams struct {
	ID          types.BinaryUUID `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Icon        string           `json:"icon"`
	SortOrder   int32            `json:"sort_order"`
	Active      int16            `json:"active"`
}

func (q *Queries) CreateHomepagePromoItem(ctx context.Context, arg CreateHomepagePromoItemParams) error {
	_, err := q.db.ExecContext(ctx, createHomepagePromoItem,
		arg.ID, arg.Title, arg.Description, arg.Icon, arg.SortOrder, arg.Active,
	)
	return err
}

const deleteHomepageBanner = `-- name: DeleteHomepageBanner :exec
DELETE FROM homepage_banners WHERE id = ?
`

func (q *Queries) DeleteHomepageBanner(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deleteHomepageBanner, id)
	return err
}

const deleteHomepageHeroSlide = `-- name: DeleteHomepageHeroSlide :exec
DELETE FROM homepage_hero_slides WHERE id = ?
`

func (q *Queries) DeleteHomepageHeroSlide(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deleteHomepageHeroSlide, id)
	return err
}

const deleteHomepagePromoItem = `-- name: DeleteHomepagePromoItem :exec
DELETE FROM homepage_promo_items WHERE id = ?
`

func (q *Queries) DeleteHomepagePromoItem(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deleteHomepagePromoItem, id)
	return err
}

const getHomepageBannerByID = `-- name: GetHomepageBannerByID :one
SELECT id, title, subtitle, image, link, active, sort_order, created_at, updated_at FROM homepage_banners WHERE id = ? LIMIT 1
`

func (q *Queries) GetHomepageBannerByID(ctx context.Context, id types.BinaryUUID) (HomepageBanner, error) {
	row := q.db.QueryRowContext(ctx, getHomepageBannerByID, id)
	var i HomepageBanner
	err := row.Scan(
		&i.ID, &i.Title, &i.Subtitle, &i.Image, &i.Link, &i.Active, &i.SortOrder, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getHomepageHeroSlideByID = `-- name: GetHomepageHeroSlideByID :one
SELECT id, label, title, subtitle, image, link, sort_order, active, created_at, updated_at FROM homepage_hero_slides WHERE id = ? LIMIT 1
`

func (q *Queries) GetHomepageHeroSlideByID(ctx context.Context, id types.BinaryUUID) (HomepageHeroSlide, error) {
	row := q.db.QueryRowContext(ctx, getHomepageHeroSlideByID, id)
	var i HomepageHeroSlide
	err := row.Scan(
		&i.ID, &i.Label, &i.Title, &i.Subtitle, &i.Image, &i.Link, &i.SortOrder, &i.Active, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getHomepagePromoItemByID = `-- name: GetHomepagePromoItemByID :one
SELECT id, title, description, icon, sort_order, active, created_at, updated_at FROM homepage_promo_items WHERE id = ? LIMIT 1
`

func (q *Queries) GetHomepagePromoItemByID(ctx context.Context, id types.BinaryUUID) (HomepagePromoItem, error) {
	row := q.db.QueryRowContext(ctx, getHomepagePromoItemByID, id)
	var i HomepagePromoItem
	err := row.Scan(
		&i.ID, &i.Title, &i.Description, &i.Icon, &i.SortOrder, &i.Active, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listActiveHomepageBanners = `-- name: ListActiveHomepageBanners :many
SELECT id, title, subtitle, image, link, active, sort_order, created_at, updated_at FROM homepage_banners
WHERE active = true
ORDER BY sort_order ASC, created_at ASC
LIMIT 1
`

func (q *Queries) ListActiveHomepageBanners(ctx context.Context) ([]HomepageBanner, error) {
	rows, err := q.db.QueryContext(ctx, listActiveHomepageBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepageBanner{}
	for rows.Next() {
		var i HomepageBanner
		if err := rows.Scan(
			&i.ID, &i.Title, &i.Subtitle, &i.Image, &i.Link, &i.Active, &i.SortOrder, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const listActiveHomepageHeroSlides = `-- name: ListActiveHomepageHeroSlides :many
SELECT id, label, title, subtitle, image, link, sort_order, active, created_at, updated_at FROM homepage_hero_slides
WHERE active = true
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListActiveHomepageHeroSlides(ctx context.Context) ([]HomepageHeroSlide, error) {
	rows, err := q.db.QueryContext(ctx, listActiveHomepageHeroSlides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepageHeroSlide{}
	for rows.Next() {
		var i HomepageHeroSlide
		if err := rows.Scan(
			&i.ID, &i.Label, &i.Title, &i.Subtitle, &i.Image, &i.Link, &i.SortOrder, &i.Active, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const listActiveHomepagePromoItems = `-- name: ListActiveHomepagePromoItems :many
SELECT id, title, description, icon, sort_order, active, created_at, updated_at FROM homepage_promo_items
WHERE active = true
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListActiveHomepagePromoItems(ctx context.Context) ([]HomepagePromoItem, error) {
	rows, err := q.db.QueryContext(ctx, listActiveHomepagePromoItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepagePromoItem{}
	for rows.Next() {
		var i HomepagePromoItem
		if err := rows.Scan(
			&i.ID, &i.Title, &i.Description, &i.Icon, &i.SortOrder, &i.Active, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const listAllHomepageBanners = `-- name: ListAllHomepageBanners :many
SELECT id, title, subtitle, image, link, active, sort_order, created_at, updated_at FROM homepage_banners
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListAllHomepageBanners(ctx context.Context) ([]HomepageBanner, error) {
	rows, err := q.db.QueryContext(ctx, listAllHomepageBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepageBanner{}
	for rows.Next() {
		var i HomepageBanner
		if err := rows.Scan(
			&i.ID, &i.Title, &i.Subtitle, &i.Image, &i.Link, &i.Active, &i.SortOrder, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const listAllHomepageHeroSlides = `-- name: ListAllHomepageHeroSlides :many
SELECT id, label, title, subtitle, image, link, sort_order, active, created_at, updated_at FROM homepage_hero_slides
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListAllHomepageHeroSlides(ctx context.Context) ([]HomepageHeroSlide, error) {
	rows, err := q.db.QueryContext(ctx, listAllHomepageHeroSlides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepageHeroSlide{}
	for rows.Next() {
		var i HomepageHeroSlide
		if err := rows.Scan(
			&i.ID, &i.Label, &i.Title, &i.Subtitle, &i.Image, &i.Link, &i.SortOrder, &i.Active, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const listAllHomepagePromoItems = `-- name: ListAllHomepagePromoItems :many
SELECT id, title, description, icon, sort_order, active, created_at, updated_at FROM homepage_promo_items
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListAllHomepagePromoItems(ctx context.Context) ([]HomepagePromoItem, error) {
	rows, err := q.db.QueryContext(ctx, listAllHomepagePromoItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepagePromoItem{}
	for rows.Next() {
		var i HomepagePromoItem
		if err := rows.Scan(
			&i.ID, &i.Title, &i.Description, &i.Icon, &i.SortOrder, &i.Active, &i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const setHomepageBannerActive = `-- name: SetHomepageBannerActive :exec
UPDATE homepage_banners SET active = ? WHERE id = ?
`

type SetHomepageBannerActiveParams struct {
	Active int16            `json:"active"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) SetHomepageBannerActive(ctx context.Context, arg SetHomepageBannerActiveParams) error {
	_, err := q.db.ExecContext(ctx, setHomepageBannerActive, arg.Active, arg.ID)
	return err
}

const setHomepageHeroSlideActive = `-- name: SetHomepageHeroSlideActive :exec
UPDATE homepage_hero_slides SET active = ? WHERE id = ?
`

type SetHomepageHeroSlideActiveParams struct {
	Active int16            `json:"active"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) SetHomepageHeroSlideActive(ctx context.Context, arg SetHomepageHeroSlideActiveParams) error {
	_, err := q.db.ExecContext(ctx, setHomepageHeroSlideActive, arg.Active, arg.ID)
	return err
}

const setHomepagePromoItemActive = `-- name: SetHomepagePromoItemActive :exec
UPDATE homepage_promo_items SET active = ? WHERE id = ?
`

type SetHomepagePromoItemActiveParams struct {
	Active int16            `json:"active"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) SetHomepagePromoItemActive(ctx context.Context, arg SetHomepagePromoItemActiveParams) error {
	_, err := q.db.ExecContext(ctx, setHomepagePromoItemActive, arg.Active, arg.ID)
	return err
}

const updateHomepageBanner = `-- name: UpdateHomepageBanner :exec
UPDATE homepage_banners
SET title = ?, subtitle = ?, image = ?, link = ?, sort_order = ?
WHERE id = ?
`

type UpdateHomepageBannerParams struct {
	Title     sql.NullString   `json:"title"`
	Subtitle  sql.NullString   `json:"subtitle"`
	Image     string           `json:"image"`
	Link      sql.NullString   `json:"link"`
	SortOrder int32            `json:"sort_order"`
	ID        types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateHomepageBanner(ctx context.Context, arg UpdateHomepageBannerParams) error {
	_, err := q.db.ExecContext(ctx, updateHomepageBanner,
		arg.Title, arg.Subtitle, arg.Image, arg.Link, arg.SortOrder, arg.ID,
	)
	return err
}

const updateHomepageHeroSlide = `-- name: UpdateHomepageHeroSlide :exec
UPDATE homepage_hero_slides
SET label = ?, title = ?, subtitle = ?, image = ?, link = ?, sort_order = ?
WHERE id = ?
`

type UpdateHomepageHeroSlideParams struct {
	Label     string           `json:"label"`
	Title     string           `json:"title"`
	Subtitle  sql.NullString   `json:"subtitle"`
	Image     string           `json:"image"`
	Link      string           `json:"link"`
	SortOrder int32            `json:"sort_order"`
	ID        types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateHomepageHeroSlide(ctx context.Context, arg UpdateHomepageHeroSlideParams) error {
	_, err := q.db.ExecContext(ctx, updateHomepageHeroSlide,
		arg.Label, arg.Title, arg.Subtitle, arg.Image, arg.Link, arg.SortOrder, arg.ID,
	)
	return err
}

const updateHomepagePromoItem = `-- name: UpdateHomepagePromoItem :exec
UPDATE homepage_promo_items
SET title = ?, description = ?, icon = ?, sort_order = ?
WHERE id = ?
`

type UpdateHomepagePromoItemParams struct {
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Icon        string           `json:"icon"`
	SortOrder   int32            `json:"sort_order"`
	ID          types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateHomepagePromoItem(ctx context.Context, arg UpdateHomepagePromoItemParams) error {
	_, err := q.db.ExecContext(ctx, updateHomepagePromoItem,
		arg.Title, arg.Description, arg.Icon, arg.SortOrder, arg.ID,
	)
	return err
}
