// Code generated by sqlc. DO NOT EDIT.
// source: homepage.sql

package sqlc

import (
	"context"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const createHomepageShowcase = `-- name: CreateHomepageShowcase :exec
INSERT INTO homepage_showcase (
  id, overline, headline, description, button_text, button_link,
  background_color, image_1, image_2, image_3, image_4, active
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateHomepageShowcaseParams struct {
	ID              types.BinaryUUID `json:"id"`
	Overline        string           `json:"overline"`
	Headline        string           `json:"headline"`
	Description     string           `json:"description"`
	ButtonText      string           `json:"button_text"`
	ButtonLink      string           `json:"button_link"`
	BackgroundColor string           `json:"background_color"`
	Image1          string           `json:"image_1"`
	Image2          string           `json:"image_2"`
	Image3          string           `json:"image_3"`
	Image4          string           `json:"image_4"`
	Active          int16            `json:"active"`
}

func (q *Queries) CreateHomepageShowcase(ctx context.Context, arg CreateHomepageShowcaseParams) error {
	_, err := q.db.ExecContext(ctx, createHomepageShowcase,
		arg.ID,
		arg.Overline,
		arg.Headline,
		arg.Description,
		arg.ButtonText,
		arg.ButtonLink,
		arg.BackgroundColor,
		arg.Image1,
		arg.Image2,
		arg.Image3,
		arg.Image4,
		arg.Active,
	)
	return err
}

const getActiveHomepageShowcase = `-- name: GetActiveHomepageShowcase :one
SELECT id, overline, headline, description, button_text, button_link, background_color, image_1, image_2, image_3, image_4, active, created_at, updated_at FROM homepage_showcase
WHERE active = true
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetActiveHomepageShowcase(ctx context.Context) (HomepageShowcase, error) {
	row := q.db.QueryRowContext(ctx, getActiveHomepageShowcase)
	var i HomepageShowcase
	err := row.Scan(
		&i.ID,
		&i.Overline,
		&i.Headline,
		&i.Description,
		&i.ButtonText,
		&i.ButtonLink,
		&i.BackgroundColor,
		&i.Image1,
		&i.Image2,
		&i.Image3,
		&i.Image4,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHomepageShowcase = `-- name: GetHomepageShowcase :one
SELECT id, overline, headline, description, button_text, button_link, background_color, image_1, image_2, image_3, image_4, active, created_at, updated_at FROM homepage_showcase
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetHomepageShowcase(ctx context.Context) (HomepageShowcase, error) {
	row := q.db.QueryRowContext(ctx, getHomepageShowcase)
	var i HomepageShowcase
	err := row.Scan(
		&i.ID,
		&i.Overline,
		&i.Headline,
		&i.Description,
		&i.ButtonText,
		&i.ButtonLink,
		&i.BackgroundColor,
		&i.Image1,
		&i.Image2,
		&i.Image3,
		&i.Image4,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHomepageShowcase = `-- name: UpdateHomepageShowcase :exec
UPDATE homepage_showcase
SET overline = ?, headline = ?, description = ?, button_text = ?, button_link = ?,
    background_color = ?, image_1 = ?, image_2 = ?, image_3 = ?, image_4 = ?, active = ?
WHERE id = ?
`

type UpdateHomepageShowcaseParams struct {
	Overline        string           `json:"overline"`
	Headline        string           `json:"headline"`
	Description     string           `json:"description"`
	ButtonText      string           `json:"button_text"`
	ButtonLink      string           `json:"button_link"`
	BackgroundColor string           `json:"background_color"`
	Image1          string           `json:"image_1"`
	Image2          string           `json:"image_2"`
	Image3          string           `json:"image_3"`
	Image4          string           `json:"image_4"`
	Active          int16            `json:"active"`
	ID              types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateHomepageShowcase(ctx context.Context, arg UpdateHomepageShowcaseParams) error {
	_, err := q.db.ExecContext(ctx, updateHomepageShowcase,
		arg.Overline,
		arg.Headline,
		arg.Description,
		arg.ButtonText,
		arg.ButtonLink,
		arg.BackgroundColor,
		arg.Image1,
		arg.Image2,
		arg.Image3,
		arg.Image4,
		arg.Active,
		arg.ID,
	)
	return err
}
