// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"lumi-backend/internal/database/types"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET response_code = ?, response_body = ?, completed_at = NOW()
WHERE id = ?
`

type CompleteIdempotencyKeyParams struct {
	ResponseCode sql.NullInt16    `json:"response_code"`
	ResponseBody *json.RawMessage `json:"response_body"`
	ID           types.BinaryUUID `json:"id"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, completeIdempotencyKey, arg.ResponseCode, arg.ResponseBody, arg.ID)
	return err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :exec
INSERT INTO idempotency_keys (
  id, key_hash, user_id, endpoint, request_hash, expires_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateIdempotencyKeyParams struct {
	ID          types.BinaryUUID `json:"id"`
	KeyHash     string           `json:"key_hash"`
	UserID      types.BinaryUUID `json:"user_id"`
	Endpoint    string           `json:"endpoint"`
	RequestHash string           `json:"request_hash"`
	ExpiresAt   time.Time        `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, createIdempotencyKey,
		arg.ID,
		arg.KeyHash,
		arg.UserID,
		arg.Endpoint,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, key_hash, user_id, endpoint, request_hash, response_code, response_body, locked_at, completed_at, expires_at, created_at FROM idempotency_keys WHERE key_hash = ? LIMIT 1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, keyHash string) (IdempotencyKey, error) {
	row := q.db.QueryRowContext(ctx, getIdempotencyKey, keyHash)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.KeyHash,
		&i.UserID,
		&i.Endpoint,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockIdempotencyKey = `-- name: LockIdempotencyKey :execrows
UPDATE idempotency_keys
SET locked_at = NOW()
WHERE id = ? AND completed_at IS NULL AND locked_at IS NULL
`

func (q *Queries) LockIdempotencyKey(ctx context.Context, id types.BinaryUUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, lockIdempotencyKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
