// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

type CouponsType string

const (
	CouponsTypePercentage CouponsType = "percentage"
	CouponsTypeFixed      CouponsType = "fixed"
)

func (e *CouponsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CouponsType(s)
	case string:
		*e = CouponsType(s)
	default:
		return fmt.Errorf("unsupported scan type for CouponsType: %T", src)
	}
	return nil
}

type NullCouponsType struct {
	CouponsType CouponsType `json:"coupons_type"`
	Valid       bool        `json:"valid"` // Valid is true if CouponsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCouponsType) Scan(value interface{}) error {
	if value == nil {
		ns.CouponsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CouponsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCouponsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CouponsType), nil
}

type DeliveryZoneAreasAreaType string

const (
	DeliveryZoneAreasAreaTypeCity    DeliveryZoneAreasAreaType = "city"
	DeliveryZoneAreasAreaTypeCounty  DeliveryZoneAreasAreaType = "county"
	DeliveryZoneAreasAreaTypeCountry DeliveryZoneAreasAreaType = "country"
)

func (e *DeliveryZoneAreasAreaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryZoneAreasAreaType(s)
	case string:
		*e = DeliveryZoneAreasAreaType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryZoneAreasAreaType: %T", src)
	}
	return nil
}

type NullDeliveryZoneAreasAreaType struct {
	DeliveryZoneAreasAreaType DeliveryZoneAreasAreaType `json:"delivery_zone_areas_area_type"`
	Valid                     bool                      `json:"valid"` // Valid is true if DeliveryZoneAreasAreaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryZoneAreasAreaType) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryZoneAreasAreaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryZoneAreasAreaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryZoneAreasAreaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryZoneAreasAreaType), nil
}

type OrderReturnsRefundStatus string

const (
	OrderReturnsRefundStatusPending    OrderReturnsRefundStatus = "pending"
	OrderReturnsRefundStatusProcessing OrderReturnsRefundStatus = "processing"
	OrderReturnsRefundStatusCompleted  OrderReturnsRefundStatus = "completed"
	OrderReturnsRefundStatusFailed     OrderReturnsRefundStatus = "failed"
)

func (e *OrderReturnsRefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderReturnsRefundStatus(s)
	case string:
		*e = OrderReturnsRefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderReturnsRefundStatus: %T", src)
	}
	return nil
}

type NullOrderReturnsRefundStatus struct {
	OrderReturnsRefundStatus OrderReturnsRefundStatus `json:"order_returns_refund_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if OrderReturnsRefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderReturnsRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderReturnsRefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderReturnsRefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderReturnsRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderReturnsRefundStatus), nil
}

type OrderReturnsStatus string

const (
	OrderReturnsStatusRequested OrderReturnsStatus = "requested"
	OrderReturnsStatusApproved  OrderReturnsStatus = "approved"
	OrderReturnsStatusRejected  OrderReturnsStatus = "rejected"
	OrderReturnsStatusRefunded  OrderReturnsStatus = "refunded"
)

func (e *OrderReturnsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderReturnsStatus(s)
	case string:
		*e = OrderReturnsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderReturnsStatus: %T", src)
	}
	return nil
}

type NullOrderReturnsStatus struct {
	OrderReturnsStatus OrderReturnsStatus `json:"order_returns_status"`
	Valid              bool               `json:"valid"` // Valid is true if OrderReturnsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderReturnsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderReturnsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderReturnsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderReturnsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderReturnsStatus), nil
}

type OrdersStatus string

const (
	OrdersStatusPending    OrdersStatus = "pending"
	OrdersStatusProcessing OrdersStatus = "processing"
	OrdersStatusShipped    OrdersStatus = "shipped"
	OrdersStatusDelivered  OrdersStatus = "delivered"
	OrdersStatusCancelled  OrdersStatus = "cancelled"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus `json:"orders_status"`
	Valid        bool         `json:"valid"` // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

type PaymentTransactionsStatus string

const (
	PaymentTransactionsStatusPending  PaymentTransactionsStatus = "pending"
	PaymentTransactionsStatusSuccess  PaymentTransactionsStatus = "success"
	PaymentTransactionsStatusFailed   PaymentTransactionsStatus = "failed"
	PaymentTransactionsStatusRefunded PaymentTransactionsStatus = "refunded"
)

func (e *PaymentTransactionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentTransactionsStatus(s)
	case string:
		*e = PaymentTransactionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentTransactionsStatus: %T", src)
	}
	return nil
}

type NullPaymentTransactionsStatus struct {
	PaymentTransactionsStatus PaymentTransactionsStatus `json:"payment_transactions_status"`
	Valid                     bool                      `json:"valid"` // Valid is true if PaymentTransactionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentTransactionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentTransactionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentTransactionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentTransactionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentTransactionsStatus), nil
}

type PaymentTransactionsType string

const (
	PaymentTransactionsTypeOrder        PaymentTransactionsType = "order"
	PaymentTransactionsTypeSubscription PaymentTransactionsType = "subscription"
)

func (e *PaymentTransactionsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentTransactionsType(s)
	case string:
		*e = PaymentTransactionsType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentTransactionsType: %T", src)
	}
	return nil
}

type NullPaymentTransactionsType struct {
	PaymentTransactionsType PaymentTransactionsType `json:"payment_transactions_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if PaymentTransactionsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentTransactionsType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentTransactionsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentTransactionsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentTransactionsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentTransactionsType), nil
}

type ProductsGender string

const (
	ProductsGenderMen    ProductsGender = "men"
	ProductsGenderWomen  ProductsGender = "women"
	ProductsGenderKids   ProductsGender = "kids"
	ProductsGenderUnisex ProductsGender = "unisex"
)

func (e *ProductsGender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductsGender(s)
	case string:
		*e = ProductsGender(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductsGender: %T", src)
	}
	return nil
}

type NullProductsGender struct {
	ProductsGender ProductsGender `json:"products_gender"`
	Valid          bool           `json:"valid"` // Valid is true if ProductsGender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductsGender) Scan(value interface{}) error {
	if value == nil {
		ns.ProductsGender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductsGender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductsGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductsGender), nil
}

type ProductsStatus string

const (
	ProductsStatusActive   ProductsStatus = "active"
	ProductsStatusPending  ProductsStatus = "pending"
	ProductsStatusHidden   ProductsStatus = "hidden"
	ProductsStatusArchived ProductsStatus = "archived"
)

func (e *ProductsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductsStatus(s)
	case string:
		*e = ProductsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductsStatus: %T", src)
	}
	return nil
}

type NullProductsStatus struct {
	ProductsStatus ProductsStatus `json:"products_status"`
	Valid          bool           `json:"valid"` // Valid is true if ProductsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductsStatus), nil
}

type PromotionsDiscountType string

const (
	PromotionsDiscountTypePercentage PromotionsDiscountType = "percentage"
	PromotionsDiscountTypeFixed      PromotionsDiscountType = "fixed"
)

func (e *PromotionsDiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionsDiscountType(s)
	case string:
		*e = PromotionsDiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionsDiscountType: %T", src)
	}
	return nil
}

type NullPromotionsDiscountType struct {
	PromotionsDiscountType PromotionsDiscountType `json:"promotions_discount_type"`
	Valid                  bool                   `json:"valid"` // Valid is true if PromotionsDiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionsDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionsDiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionsDiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionsDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionsDiscountType), nil
}

type PromotionsType string

const (
	PromotionsTypeFlashSale PromotionsType = "flash_sale"
	PromotionsTypeSeasonal  PromotionsType = "seasonal"
	PromotionsTypeClearance PromotionsType = "clearance"
)

func (e *PromotionsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionsType(s)
	case string:
		*e = PromotionsType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionsType: %T", src)
	}
	return nil
}

type NullPromotionsType struct {
	PromotionsType PromotionsType `json:"promotions_type"`
	Valid          bool           `json:"valid"` // Valid is true if PromotionsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionsType) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionsType), nil
}

type ShipmentsStatus string

const (
	ShipmentsStatusPending        ShipmentsStatus = "pending"
	ShipmentsStatusPickedUp       ShipmentsStatus = "picked_up"
	ShipmentsStatusInTransit      ShipmentsStatus = "in_transit"
	ShipmentsStatusOutForDelivery ShipmentsStatus = "out_for_delivery"
	ShipmentsStatusDelivered      ShipmentsStatus = "delivered"
	ShipmentsStatusFailed         ShipmentsStatus = "failed"
)

func (e *ShipmentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShipmentsStatus(s)
	case string:
		*e = ShipmentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShipmentsStatus: %T", src)
	}
	return nil
}

type NullShipmentsStatus struct {
	ShipmentsStatus ShipmentsStatus `json:"shipments_status"`
	Valid           bool            `json:"valid"` // Valid is true if ShipmentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShipmentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShipmentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShipmentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShipmentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShipmentsStatus), nil
}

type StockMovementsReason string

const (
	StockMovementsReasonOrder      StockMovementsReason = "order"
	StockMovementsReasonReturn     StockMovementsReason = "return"
	StockMovementsReasonRestock    StockMovementsReason = "restock"
	StockMovementsReasonAdjustment StockMovementsReason = "adjustment"
	StockMovementsReasonCorrection StockMovementsReason = "correction"
)

func (e *StockMovementsReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockMovementsReason(s)
	case string:
		*e = StockMovementsReason(s)
	default:
		return fmt.Errorf("unsupported scan type for StockMovementsReason: %T", src)
	}
	return nil
}

type NullStockMovementsReason struct {
	StockMovementsReason StockMovementsReason `json:"stock_movements_reason"`
	Valid                bool                 `json:"valid"` // Valid is true if StockMovementsReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockMovementsReason) Scan(value interface{}) error {
	if value == nil {
		ns.StockMovementsReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockMovementsReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockMovementsReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockMovementsReason), nil
}

type StockReservationsStatus string

const (
	StockReservationsStatusReserved  StockReservationsStatus = "reserved"
	StockReservationsStatusCompleted StockReservationsStatus = "completed"
	StockReservationsStatusAbandoned StockReservationsStatus = "abandoned"
)

func (e *StockReservationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockReservationsStatus(s)
	case string:
		*e = StockReservationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StockReservationsStatus: %T", src)
	}
	return nil
}

type NullStockReservationsStatus struct {
	StockReservationsStatus StockReservationsStatus `json:"stock_reservations_status"`
	Valid                   bool                    `json:"valid"` // Valid is true if StockReservationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockReservationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StockReservationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockReservationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockReservationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockReservationsStatus), nil
}

type UsersRole string

const (
	UsersRoleCUSTOMER UsersRole = "CUSTOMER"
	UsersRoleVENDOR   UsersRole = "VENDOR"
	UsersRoleADMIN    UsersRole = "ADMIN"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type VendorApplicationsRiskStatus string

const (
	VendorApplicationsRiskStatusLow    VendorApplicationsRiskStatus = "low"
	VendorApplicationsRiskStatusMedium VendorApplicationsRiskStatus = "medium"
	VendorApplicationsRiskStatusHigh   VendorApplicationsRiskStatus = "high"
)

func (e *VendorApplicationsRiskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorApplicationsRiskStatus(s)
	case string:
		*e = VendorApplicationsRiskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorApplicationsRiskStatus: %T", src)
	}
	return nil
}

type NullVendorApplicationsRiskStatus struct {
	VendorApplicationsRiskStatus VendorApplicationsRiskStatus `json:"vendor_applications_risk_status"`
	Valid                        bool                         `json:"valid"` // Valid is true if VendorApplicationsRiskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorApplicationsRiskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VendorApplicationsRiskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorApplicationsRiskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorApplicationsRiskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorApplicationsRiskStatus), nil
}

type VendorApplicationsStatus string

const (
	VendorApplicationsStatusPending  VendorApplicationsStatus = "pending"
	VendorApplicationsStatusApproved VendorApplicationsStatus = "approved"
	VendorApplicationsStatusRejected VendorApplicationsStatus = "rejected"
)

func (e *VendorApplicationsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorApplicationsStatus(s)
	case string:
		*e = VendorApplicationsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorApplicationsStatus: %T", src)
	}
	return nil
}

type NullVendorApplicationsStatus struct {
	VendorApplicationsStatus VendorApplicationsStatus `json:"vendor_applications_status"`
	Valid                    bool                     `json:"valid"` // Valid is true if VendorApplicationsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorApplicationsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VendorApplicationsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorApplicationsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorApplicationsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorApplicationsStatus), nil
}

type VendorPayoutMethodsType string

const (
	VendorPayoutMethodsTypeMpesa        VendorPayoutMethodsType = "mpesa"
	VendorPayoutMethodsTypeBankTransfer VendorPayoutMethodsType = "bank_transfer"
)

func (e *VendorPayoutMethodsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorPayoutMethodsType(s)
	case string:
		*e = VendorPayoutMethodsType(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorPayoutMethodsType: %T", src)
	}
	return nil
}

type NullVendorPayoutMethodsType struct {
	VendorPayoutMethodsType VendorPayoutMethodsType `json:"vendor_payout_methods_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if VendorPayoutMethodsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorPayoutMethodsType) Scan(value interface{}) error {
	if value == nil {
		ns.VendorPayoutMethodsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorPayoutMethodsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorPayoutMethodsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorPayoutMethodsType), nil
}

type VendorPayoutsStatus string

const (
	VendorPayoutsStatusPending    VendorPayoutsStatus = "pending"
	VendorPayoutsStatusProcessing VendorPayoutsStatus = "processing"
	VendorPayoutsStatusPaid       VendorPayoutsStatus = "paid"
	VendorPayoutsStatusFailed     VendorPayoutsStatus = "failed"
)

func (e *VendorPayoutsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorPayoutsStatus(s)
	case string:
		*e = VendorPayoutsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorPayoutsStatus: %T", src)
	}
	return nil
}

type NullVendorPayoutsStatus struct {
	VendorPayoutsStatus VendorPayoutsStatus `json:"vendor_payouts_status"`
	Valid               bool                `json:"valid"` // Valid is true if VendorPayoutsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorPayoutsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VendorPayoutsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorPayoutsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorPayoutsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorPayoutsStatus), nil
}

type VendorSubscriptionsPlan string

const (
	VendorSubscriptionsPlanMonthly   VendorSubscriptionsPlan = "monthly"
	VendorSubscriptionsPlanQuarterly VendorSubscriptionsPlan = "quarterly"
	VendorSubscriptionsPlanBiannual  VendorSubscriptionsPlan = "biannual"
	VendorSubscriptionsPlanYearly    VendorSubscriptionsPlan = "yearly"
)

func (e *VendorSubscriptionsPlan) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VendorSubscriptionsPlan(s)
	case string:
		*e = VendorSubscriptionsPlan(s)
	default:
		return fmt.Errorf("unsupported scan type for VendorSubscriptionsPlan: %T", src)
	}
	return nil
}

type NullVendorSubscriptionsPlan struct {
	VendorSubscriptionsPlan VendorSubscriptionsPlan `json:"vendor_subscriptions_plan"`
	Valid                   bool                    `json:"valid"` // Valid is true if VendorSubscriptionsPlan is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVendorSubscriptionsPlan) Scan(value interface{}) error {
	if value == nil {
		ns.VendorSubscriptionsPlan, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VendorSubscriptionsPlan.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVendorSubscriptionsPlan) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VendorSubscriptionsPlan), nil
}

type Address struct {
	ID        types.BinaryUUID `json:"id"`
	UserID    types.BinaryUUID `json:"user_id"`
	Label     string           `json:"label"`
	Street    string           `json:"street"`
	City      string           `json:"city"`
	State     string           `json:"state"`
	Country   string           `json:"country"`
	ZipCode   string           `json:"zip_code"`
	IsDefault int16            `json:"is_default"`
	DeletedAt sql.NullTime     `json:"deleted_at"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

type AuditLog struct {
	ID           types.BinaryUUID `json:"id"`
	UserID       types.BinaryUUID `json:"user_id"`
	ActorName    string           `json:"actor_name"`
	ActorRole    string           `json:"actor_role"`
	Action       string           `json:"action"`
	ResourceType string           `json:"resource_type"`
	ResourceID   types.BinaryUUID `json:"resource_id"`
	BeforeState  *json.RawMessage `json:"before_state"`
	AfterState   *json.RawMessage `json:"after_state"`
	IpAddress    sql.NullString   `json:"ip_address"`
	CreatedAt    time.Time        `json:"created_at"`
}

type Cart struct {
	ID         types.BinaryUUID  `json:"id"`
	UserID     *types.BinaryUUID `json:"user_id"`
	SessionKey sql.NullString    `json:"session_key"`
	ExpiresAt  sql.NullTime      `json:"expires_at"`
	CreatedAt  time.Time         `json:"created_at"`
	UpdatedAt  time.Time         `json:"updated_at"`
}

type CartItem struct {
	ID        types.BinaryUUID `json:"id"`
	CartID    types.BinaryUUID `json:"cart_id"`
	VariantID types.BinaryUUID `json:"variant_id"`
	Quantity  int32            `json:"quantity"`
	AddedAt   time.Time        `json:"added_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

type Category struct {
	ID        types.BinaryUUID  `json:"id"`
	Name      string            `json:"name"`
	Slug      string            `json:"slug"`
	ParentID  *types.BinaryUUID `json:"parent_id"`
	SortOrder int32             `json:"sort_order"`
	Active    int16             `json:"active"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
}

type Collection struct {
	ID          types.BinaryUUID  `json:"id"`
	Name        string            `json:"name"`
	Slug        string            `json:"slug"`
	Description sql.NullString    `json:"description"`
	Image       sql.NullString    `json:"image"`
	Active      int16             `json:"active"`
	SortOrder   int32             `json:"sort_order"`
	StartsAt    sql.NullTime      `json:"starts_at"`
	EndsAt      sql.NullTime      `json:"ends_at"`
	CreatedBy   *types.BinaryUUID `json:"created_by"`
	DeletedAt   sql.NullTime      `json:"deleted_at"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
}

type CollectionProduct struct {
	CollectionID types.BinaryUUID `json:"collection_id"`
	ProductID    types.BinaryUUID `json:"product_id"`
	SortOrder    int32            `json:"sort_order"`
}

type Coupon struct {
	ID             types.BinaryUUID  `json:"id"`
	Code           string            `json:"code"`
	Type           CouponsType       `json:"type"`
	Value          string            `json:"value"`
	MinOrderAmount string            `json:"min_order_amount"`
	MaxDiscount    sql.NullString    `json:"max_discount"`
	MaxUses        sql.NullInt32     `json:"max_uses"`
	UsesCount      int32             `json:"uses_count"`
	PerUserLimit   int32             `json:"per_user_limit"`
	VendorID       *types.BinaryUUID `json:"vendor_id"`
	Active         int16             `json:"active"`
	DeletedAt      sql.NullTime      `json:"deleted_at"`
	StartsAt       sql.NullTime      `json:"starts_at"`
	ExpiresAt      sql.NullTime      `json:"expires_at"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

type CouponUse struct {
	ID             types.BinaryUUID `json:"id"`
	CouponID       types.BinaryUUID `json:"coupon_id"`
	UserID         types.BinaryUUID `json:"user_id"`
	OrderID        types.BinaryUUID `json:"order_id"`
	DiscountAmount string           `json:"discount_amount"`
	UsedAt         time.Time        `json:"used_at"`
}

type DeliveryZone struct {
	ID            types.BinaryUUID  `json:"id"`
	VendorID      *types.BinaryUUID `json:"vendor_id"`
	Name          string            `json:"name"`
	BaseCost      string            `json:"base_cost"`
	EstimatedDays string            `json:"estimated_days"`
	Active        int16             `json:"active"`
	CreatedAt     time.Time         `json:"created_at"`
	UpdatedAt     time.Time         `json:"updated_at"`
}

type DeliveryZoneArea struct {
	ID       types.BinaryUUID          `json:"id"`
	ZoneID   types.BinaryUUID          `json:"zone_id"`
	AreaType DeliveryZoneAreasAreaType `json:"area_type"`
	AreaName string                    `json:"area_name"`
}

type EmailVerification struct {
	ID         types.BinaryUUID `json:"id"`
	UserID     types.BinaryUUID `json:"user_id"`
	TokenHash  string           `json:"token_hash"`
	ExpiresAt  time.Time        `json:"expires_at"`
	VerifiedAt sql.NullTime     `json:"verified_at"`
	CreatedAt  time.Time        `json:"created_at"`
}

type IdempotencyKey struct {
	ID           types.BinaryUUID `json:"id"`
	KeyHash      string           `json:"key_hash"`
	UserID       types.BinaryUUID `json:"user_id"`
	Endpoint     string           `json:"endpoint"`
	RequestHash  string           `json:"request_hash"`
	ResponseCode sql.NullInt16    `json:"response_code"`
	ResponseBody *json.RawMessage `json:"response_body"`
	LockedAt     sql.NullTime     `json:"locked_at"`
	CompletedAt  sql.NullTime     `json:"completed_at"`
	ExpiresAt    time.Time        `json:"expires_at"`
	CreatedAt    time.Time        `json:"created_at"`
}

type Notification struct {
	ID        types.BinaryUUID `json:"id"`
	UserID    types.BinaryUUID `json:"user_id"`
	Type      string           `json:"type"`
	Title     string           `json:"title"`
	Body      string           `json:"body"`
	Data      *json.RawMessage `json:"data"`
	ReadAt    sql.NullTime     `json:"read_at"`
	CreatedAt time.Time        `json:"created_at"`
}

type Order struct {
	ID               types.BinaryUUID  `json:"id"`
	UserID           types.BinaryUUID  `json:"user_id"`
	DeliveryZoneID   *types.BinaryUUID `json:"delivery_zone_id"`
	DeliveryZoneName sql.NullString    `json:"delivery_zone_name"`
	CouponID         *types.BinaryUUID `json:"coupon_id"`
	Subtotal         string            `json:"subtotal"`
	DiscountAmount   string            `json:"discount_amount"`
	ShippingCost     string            `json:"shipping_cost"`
	TaxAmount        string            `json:"tax_amount"`
	Total            string            `json:"total"`
	Currency         string            `json:"currency"`
	PaymentMethod    string            `json:"payment_method"`
	Status           OrdersStatus      `json:"status"`
	DeliveryAddress  json.RawMessage   `json:"delivery_address"`
	Notes            sql.NullString    `json:"notes"`
	DeliveredAt      sql.NullTime      `json:"delivered_at"`
	CreatedAt        time.Time         `json:"created_at"`
	UpdatedAt        time.Time         `json:"updated_at"`
}

type OrderItem struct {
	ID             types.BinaryUUID `json:"id"`
	OrderID        types.BinaryUUID `json:"order_id"`
	ProductID      types.BinaryUUID `json:"product_id"`
	VariantID      types.BinaryUUID `json:"variant_id"`
	VendorID       types.BinaryUUID `json:"vendor_id"`
	ProductName    string           `json:"product_name"`
	Sku            string           `json:"sku"`
	Size           string           `json:"size"`
	Color          string           `json:"color"`
	ImageUrl       sql.NullString   `json:"image_url"`
	UnitPrice      string           `json:"unit_price"`
	Discount       string           `json:"discount"`
	Quantity       int32            `json:"quantity"`
	Subtotal       string           `json:"subtotal"`
	VendorEarnings string           `json:"vendor_earnings"`
	PlatformFee    string           `json:"platform_fee"`
}

type OrderReturn struct {
	ID           types.BinaryUUID             `json:"id"`
	OrderID      types.BinaryUUID             `json:"order_id"`
	UserID       types.BinaryUUID             `json:"user_id"`
	Reason       string                       `json:"reason"`
	Items        *json.RawMessage             `json:"items"`
	Status       OrderReturnsStatus           `json:"status"`
	RefundAmount sql.NullString               `json:"refund_amount"`
	RefundStatus NullOrderReturnsRefundStatus `json:"refund_status"`
	AdminNote    sql.NullString               `json:"admin_note"`
	ResolvedAt   sql.NullTime                 `json:"resolved_at"`
	CreatedAt    time.Time                    `json:"created_at"`
	UpdatedAt    time.Time                    `json:"updated_at"`
}

type OrderStatusHistory struct {
	ID         types.BinaryUUID  `json:"id"`
	OrderID    types.BinaryUUID  `json:"order_id"`
	FromStatus sql.NullString    `json:"from_status"`
	ToStatus   string            `json:"to_status"`
	ChangedBy  *types.BinaryUUID `json:"changed_by"`
	Note       sql.NullString    `json:"note"`
	CreatedAt  time.Time         `json:"created_at"`
}

type PasswordResetToken struct {
	ID        types.BinaryUUID `json:"id"`
	UserID    types.BinaryUUID `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt time.Time        `json:"expires_at"`
	Used      int16            `json:"used"`
	CreatedAt time.Time        `json:"created_at"`
}

type PaymentTransaction struct {
	ID                 types.BinaryUUID          `json:"id"`
	Reference          string                    `json:"reference"`
	Type               PaymentTransactionsType   `json:"type"`
	UserID             types.BinaryUUID          `json:"user_id"`
	VendorID           *types.BinaryUUID         `json:"vendor_id"`
	Amount             string                    `json:"amount"`
	Currency           string                    `json:"currency"`
	Status             PaymentTransactionsStatus `json:"status"`
	PaystackAccessCode sql.NullString            `json:"paystack_access_code"`
	Metadata           json.RawMessage           `json:"metadata"`
	OrderID            *types.BinaryUUID         `json:"order_id"`
	SubscriptionID     *types.BinaryUUID         `json:"subscription_id"`
	CreatedAt          time.Time                 `json:"created_at"`
	UpdatedAt          time.Time                 `json:"updated_at"`
}

type Product struct {
	ID          types.BinaryUUID `json:"id"`
	VendorID    types.BinaryUUID `json:"vendor_id"`
	CategoryID  types.BinaryUUID `json:"category_id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Brand       string           `json:"brand"`
	Gender      ProductsGender   `json:"gender"`
	Sku         string           `json:"sku"`
	MinPrice    string           `json:"min_price"`
	MaxPrice    string           `json:"max_price"`
	TotalStock  int32            `json:"total_stock"`
	Rating      string           `json:"rating"`
	ReviewCount int32            `json:"review_count"`
	Status      ProductsStatus   `json:"status"`
	Bestseller  int16            `json:"bestseller"`
	NewArrival  int16            `json:"new_arrival"`
	Featured    int16            `json:"featured"`
	Trending    int16            `json:"trending"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type ProductImage struct {
	ID        types.BinaryUUID `json:"id"`
	ProductID types.BinaryUUID `json:"product_id"`
	Url       string           `json:"url"`
	Alt       sql.NullString   `json:"alt"`
	SortOrder int32            `json:"sort_order"`
	IsPrimary int16            `json:"is_primary"`
	CreatedAt time.Time        `json:"created_at"`
}

type ProductPriceHistory struct {
	ID        types.BinaryUUID `json:"id"`
	ProductID types.BinaryUUID `json:"product_id"`
	VariantID types.BinaryUUID `json:"variant_id"`
	OldPrice  string           `json:"old_price"`
	NewPrice  string           `json:"new_price"`
	ChangedBy types.BinaryUUID `json:"changed_by"`
	ChangedAt time.Time        `json:"changed_at"`
}

type ProductTag struct {
	ProductID types.BinaryUUID `json:"product_id"`
	Tag       string           `json:"tag"`
}

type ProductVariant struct {
	ID             types.BinaryUUID `json:"id"`
	ProductID      types.BinaryUUID `json:"product_id"`
	Size           string           `json:"size"`
	Color          string           `json:"color"`
	ColorHex       sql.NullString   `json:"color_hex"`
	Price          string           `json:"price"`
	Discount       string           `json:"discount"`
	EffectivePrice sql.NullString   `json:"effective_price"`
	Stock          int32            `json:"stock"`
	Sku            sql.NullString   `json:"sku"`
	DeletedAt      sql.NullTime     `json:"deleted_at"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type Promotion struct {
	ID            types.BinaryUUID       `json:"id"`
	Name          string                 `json:"name"`
	Type          PromotionsType         `json:"type"`
	DiscountType  PromotionsDiscountType `json:"discount_type"`
	DiscountValue string                 `json:"discount_value"`
	StartsAt      time.Time              `json:"starts_at"`
	EndsAt        time.Time              `json:"ends_at"`
	Active        int16                  `json:"active"`
	CreatedBy     *types.BinaryUUID      `json:"created_by"`
	DeletedAt     sql.NullTime           `json:"deleted_at"`
	CreatedAt     time.Time              `json:"created_at"`
	UpdatedAt     time.Time              `json:"updated_at"`
}

type PromotionProduct struct {
	PromotionID types.BinaryUUID `json:"promotion_id"`
	ProductID   types.BinaryUUID `json:"product_id"`
}

type RefreshToken struct {
	ID        types.BinaryUUID `json:"id"`
	UserID    types.BinaryUUID `json:"user_id"`
	TokenHash string           `json:"token_hash"`
	UserAgent sql.NullString   `json:"user_agent"`
	IpAddress sql.NullString   `json:"ip_address"`
	ExpiresAt time.Time        `json:"expires_at"`
	RevokedAt sql.NullTime     `json:"revoked_at"`
	CreatedAt time.Time        `json:"created_at"`
}

type Review struct {
	ID            types.BinaryUUID  `json:"id"`
	ProductID     types.BinaryUUID  `json:"product_id"`
	VendorID      types.BinaryUUID  `json:"vendor_id"`
	UserID        types.BinaryUUID  `json:"user_id"`
	OrderID       *types.BinaryUUID `json:"order_id"`
	Rating        int16             `json:"rating"`
	Comment       string            `json:"comment"`
	VendorReply   sql.NullString    `json:"vendor_reply"`
	VendorReplyAt sql.NullTime      `json:"vendor_reply_at"`
	CreatedAt     time.Time         `json:"created_at"`
	UpdatedAt     time.Time         `json:"updated_at"`
}

type SearchTerm struct {
	Term      string    `json:"term"`
	Count     uint32    `json:"count"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Shipment struct {
	ID                types.BinaryUUID `json:"id"`
	OrderID           types.BinaryUUID `json:"order_id"`
	Carrier           string           `json:"carrier"`
	TrackingNumber    string           `json:"tracking_number"`
	TrackingUrl       sql.NullString   `json:"tracking_url"`
	Status            ShipmentsStatus  `json:"status"`
	ShippedAt         sql.NullTime     `json:"shipped_at"`
	EstimatedDelivery sql.NullTime     `json:"estimated_delivery"`
	DeliveredAt       sql.NullTime     `json:"delivered_at"`
	CreatedAt         time.Time        `json:"created_at"`
	UpdatedAt         time.Time        `json:"updated_at"`
}

type StockMovement struct {
	ID            types.BinaryUUID     `json:"id"`
	ProductID     types.BinaryUUID     `json:"product_id"`
	VariantID     types.BinaryUUID     `json:"variant_id"`
	QuantityDelta int32                `json:"quantity_delta"`
	Reason        StockMovementsReason `json:"reason"`
	ReferenceType sql.NullString       `json:"reference_type"`
	ReferenceID   *types.BinaryUUID    `json:"reference_id"`
	Note          sql.NullString       `json:"note"`
	CreatedAt     time.Time            `json:"created_at"`
}

type StockReservation struct {
	ID            types.BinaryUUID        `json:"id"`
	UserID        types.BinaryUUID        `json:"user_id"`
	VariantID     types.BinaryUUID        `json:"variant_id"`
	Quantity      int32                   `json:"quantity"`
	ReservedAt    time.Time               `json:"reserved_at"`
	ReservedUntil time.Time               `json:"reserved_until"`
	Status        StockReservationsStatus `json:"status"`
	OrderID       *types.BinaryUUID       `json:"order_id"`
	CreatedAt     time.Time               `json:"created_at"`
	UpdatedAt     time.Time               `json:"updated_at"`
}

type User struct {
	ID              types.BinaryUUID `json:"id"`
	FullName        string           `json:"full_name"`
	Email           string           `json:"email"`
	Phone           string           `json:"phone"`
	Password        string           `json:"password"`
	Role            UsersRole        `json:"role"`
	Avatar          sql.NullString   `json:"avatar"`
	Disabled        int16            `json:"disabled"`
	EmailVerifiedAt sql.NullTime     `json:"email_verified_at"`
	PasswordSetAt   sql.NullTime     `json:"password_set_at"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type Vendor struct {
	ID                    types.BinaryUUID `json:"id"`
	UserID                types.BinaryUUID `json:"user_id"`
	StoreName             string           `json:"store_name"`
	Slug                  string           `json:"slug"`
	Description           sql.NullString   `json:"description"`
	Logo                  string           `json:"logo"`
	Banner                sql.NullString   `json:"banner"`
	ContactPhone          string           `json:"contact_phone"`
	BusinessEmail         string           `json:"business_email"`
	Country               string           `json:"country"`
	City                  string           `json:"city"`
	ShippingCost          string           `json:"shipping_cost"`
	FreeShippingThreshold sql.NullString   `json:"free_shipping_threshold"`
	SocialLinks           *json.RawMessage `json:"social_links"`
	CommissionRate        string           `json:"commission_rate"`
	Rating                string           `json:"rating"`
	Verified              int16            `json:"verified"`
	Suspended             int16            `json:"suspended"`
	IsFeatured            int16            `json:"is_featured"`
	CreatedAt             time.Time        `json:"created_at"`
	UpdatedAt             time.Time        `json:"updated_at"`
}

type VendorAnalyticsDaily struct {
	VendorID   types.BinaryUUID `json:"vendor_id"`
	PeriodDate time.Time        `json:"period_date"`
	Orders     int32            `json:"orders"`
	UnitsSold  int32            `json:"units_sold"`
	Revenue    string           `json:"revenue"`
	Earnings   string           `json:"earnings"`
	Refunds    string           `json:"refunds"`
}

type VendorApplication struct {
	ID                  types.BinaryUUID             `json:"id"`
	UserID              *types.BinaryUUID            `json:"user_id"`
	ApplicantName       string                       `json:"applicant_name"`
	StoreName           string                       `json:"store_name"`
	BusinessDescription string                       `json:"business_description"`
	Logo                string                       `json:"logo"`
	BusinessCertificate string                       `json:"business_certificate"`
	VendorPhoto         string                       `json:"vendor_photo"`
	BusinessPhoto       string                       `json:"business_photo"`
	BusinessEmail       string                       `json:"business_email"`
	ContactPhone        string                       `json:"contact_phone"`
	Country             string                       `json:"country"`
	City                string                       `json:"city"`
	RegistrationNumber  string                       `json:"registration_number"`
	Categories          json.RawMessage              `json:"categories"`
	RiskStatus          VendorApplicationsRiskStatus `json:"risk_status"`
	Status              VendorApplicationsStatus     `json:"status"`
	ReviewNote          sql.NullString               `json:"review_note"`
	ReviewedBy          *types.BinaryUUID            `json:"reviewed_by"`
	SubmittedAt         time.Time                    `json:"submitted_at"`
	ReviewedAt          sql.NullTime                 `json:"reviewed_at"`
	CreatedAt           time.Time                    `json:"created_at"`
	UpdatedAt           time.Time                    `json:"updated_at"`
}

type VendorCategory struct {
	VendorID   types.BinaryUUID `json:"vendor_id"`
	CategoryID types.BinaryUUID `json:"category_id"`
}

type VendorPayout struct {
	ID             types.BinaryUUID    `json:"id"`
	VendorID       types.BinaryUUID    `json:"vendor_id"`
	PayoutMethodID types.BinaryUUID    `json:"payout_method_id"`
	Amount         string              `json:"amount"`
	Currency       string              `json:"currency"`
	Status         VendorPayoutsStatus `json:"status"`
	PeriodStart    time.Time           `json:"period_start"`
	PeriodEnd      time.Time           `json:"period_end"`
	Reference      sql.NullString      `json:"reference"`
	AdminNote      sql.NullString      `json:"admin_note"`
	InitiatedAt    sql.NullTime        `json:"initiated_at"`
	CompletedAt    sql.NullTime        `json:"completed_at"`
	CreatedAt      time.Time           `json:"created_at"`
	UpdatedAt      time.Time           `json:"updated_at"`
}

type VendorPayoutItem struct {
	PayoutID    types.BinaryUUID `json:"payout_id"`
	OrderItemID types.BinaryUUID `json:"order_item_id"`
	Amount      string           `json:"amount"`
}

type VendorPayoutMethod struct {
	ID          types.BinaryUUID        `json:"id"`
	VendorID    types.BinaryUUID        `json:"vendor_id"`
	Type        VendorPayoutMethodsType `json:"type"`
	AccountName string                  `json:"account_name"`
	AccountRef  string                  `json:"account_ref"`
	BankName    sql.NullString          `json:"bank_name"`
	IsDefault   int16                   `json:"is_default"`
	CreatedAt   time.Time               `json:"created_at"`
	UpdatedAt   time.Time               `json:"updated_at"`
}

type VendorShippingRate struct {
	ID        types.BinaryUUID `json:"id"`
	VendorID  types.BinaryUUID `json:"vendor_id"`
	ZoneID    types.BinaryUUID `json:"zone_id"`
	Fee       string           `json:"fee"`
	DeletedAt sql.NullTime     `json:"deleted_at"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

type VendorSubscription struct {
	ID            types.BinaryUUID        `json:"id"`
	VendorID      types.BinaryUUID        `json:"vendor_id"`
	Plan          VendorSubscriptionsPlan `json:"plan"`
	AmountPaid    string                  `json:"amount_paid"`
	PaymentMethod string                  `json:"payment_method"`
	StartedAt     time.Time               `json:"started_at"`
	ExpiresAt     time.Time               `json:"expires_at"`
	Active        int16                   `json:"active"`
	CreatedAt     time.Time               `json:"created_at"`
	UpdatedAt     time.Time               `json:"updated_at"`
}

type Wishlist struct {
	ID         types.BinaryUUID  `json:"id"`
	UserID     *types.BinaryUUID `json:"user_id"`
	SessionKey sql.NullString    `json:"session_key"`
	ProductID  types.BinaryUUID  `json:"product_id"`
	ExpiresAt  sql.NullTime      `json:"expires_at"`
	CreatedAt  time.Time         `json:"created_at"`
}
