// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
	"time"

	"lumi-backend/internal/database/types"
)

const countAllOrders = `-- name: CountAllOrders :one
SELECT COUNT(*) FROM orders
`

func (q *Queries) CountAllOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDistinctOrderCustomers = `-- name: CountDistinctOrderCustomers :one
SELECT COUNT(DISTINCT user_id) FROM orders WHERE status != 'cancelled'
`

func (q *Queries) CountDistinctOrderCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDistinctOrderCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByUser = `-- name: CountOrdersByUser :one
SELECT COUNT(*) FROM orders WHERE user_id = ?
`

func (q *Queries) CountOrdersByUser(ctx context.Context, userID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByVendor = `-- name: CountOrdersByVendor :one
SELECT COUNT(DISTINCT o.id)
FROM orders o
INNER JOIN order_items oi ON oi.order_id = o.id
WHERE oi.vendor_id = ?
`

func (q *Queries) CountOrdersByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :exec
INSERT INTO orders (
  id, user_id, delivery_zone_id, coupon_id, subtotal, discount_amount, shipping_cost, tax_amount, total,
  payment_method, status, delivery_address, notes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)
`

type CreateOrderParams struct {
	ID              types.BinaryUUID  `json:"id"`
	UserID          types.BinaryUUID  `json:"user_id"`
	DeliveryZoneID  *types.BinaryUUID `json:"delivery_zone_id"`
	CouponID        *types.BinaryUUID `json:"coupon_id"`
	Subtotal        string            `json:"subtotal"`
	DiscountAmount  string            `json:"discount_amount"`
	ShippingCost    string            `json:"shipping_cost"`
	TaxAmount       string            `json:"tax_amount"`
	Total           string            `json:"total"`
	PaymentMethod   string            `json:"payment_method"`
	DeliveryAddress json.RawMessage   `json:"delivery_address"`
	Notes           sql.NullString    `json:"notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.DeliveryZoneID,
		arg.CouponID,
		arg.Subtotal,
		arg.DiscountAmount,
		arg.ShippingCost,
		arg.TaxAmount,
		arg.Total,
		arg.PaymentMethod,
		arg.DeliveryAddress,
		arg.Notes,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, delivery_zone_id, coupon_id, subtotal, discount_amount, shipping_cost, tax_amount, total, currency, payment_method, status, delivery_address, notes, delivered_at, created_at, updated_at FROM orders WHERE id = ? LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id types.BinaryUUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeliveryZoneID,
		&i.CouponID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.ShippingCost,
		&i.TaxAmount,
		&i.Total,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.DeliveryAddress,
		&i.Notes,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIDAndUser = `-- name: GetOrderByIDAndUser :one
SELECT id, user_id, delivery_zone_id, coupon_id, subtotal, discount_amount, shipping_cost, tax_amount, total, currency, payment_method, status, delivery_address, notes, delivered_at, created_at, updated_at FROM orders WHERE id = ? AND user_id = ? LIMIT 1
`

type GetOrderByIDAndUserParams struct {
	ID     types.BinaryUUID `json:"id"`
	UserID types.BinaryUUID `json:"user_id"`
}

func (q *Queries) GetOrderByIDAndUser(ctx context.Context, arg GetOrderByIDAndUserParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByIDAndUser, arg.ID, arg.UserID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeliveryZoneID,
		&i.CouponID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.ShippingCost,
		&i.TaxAmount,
		&i.Total,
		&i.Currency,
		&i.PaymentMethod,
		&i.Status,
		&i.DeliveryAddress,
		&i.Notes,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT id, user_id, delivery_zone_id, coupon_id, subtotal, discount_amount, shipping_cost, tax_amount, total, currency, payment_method, status, delivery_address, notes, delivered_at, created_at, updated_at FROM orders ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListAllOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listAllOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeliveryZoneID,
			&i.CouponID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.ShippingCost,
			&i.TaxAmount,
			&i.Total,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.DeliveryAddress,
			&i.Notes,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, product_id, variant_id, vendor_id, product_name, sku, size, color, image_url, unit_price, discount, quantity, subtotal, vendor_earnings, platform_fee FROM order_items WHERE order_id = ? ORDER BY id ASC
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID types.BinaryUUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.VendorID,
			&i.ProductName,
			&i.Sku,
			&i.Size,
			&i.Color,
			&i.ImageUrl,
			&i.UnitPrice,
			&i.Discount,
			&i.Quantity,
			&i.Subtotal,
			&i.VendorEarnings,
			&i.PlatformFee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderIDs = `-- name: ListOrderItemsByOrderIDs :many
SELECT id, order_id, product_id, variant_id, vendor_id, product_name, sku, size, color, image_url, unit_price, discount, quantity, subtotal, vendor_earnings, platform_fee FROM order_items WHERE order_id IN (/*SLICE:order_ids*/?)
`

func (q *Queries) ListOrderItemsByOrderIDs(ctx context.Context, orderIds []types.BinaryUUID) ([]OrderItem, error) {
	query := listOrderItemsByOrderIDs
	var queryParams []interface{}
	if len(orderIds) > 0 {
		for _, v := range orderIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:order_ids*/?", strings.Repeat(",?", len(orderIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:order_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.VariantID,
			&i.VendorID,
			&i.ProductName,
			&i.Sku,
			&i.Size,
			&i.Color,
			&i.ImageUrl,
			&i.UnitPrice,
			&i.Discount,
			&i.Quantity,
			&i.Subtotal,
			&i.VendorEarnings,
			&i.PlatformFee,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, delivery_zone_id, coupon_id, subtotal, discount_amount, shipping_cost, tax_amount, total, currency, payment_method, status, delivery_address, notes, delivered_at, created_at, updated_at FROM orders WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListOrdersByUserParams struct {
	UserID types.BinaryUUID `json:"user_id"`
	Limit  int32            `json:"limit"`
	Offset int32            `json:"offset"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeliveryZoneID,
			&i.CouponID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.ShippingCost,
			&i.TaxAmount,
			&i.Total,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.DeliveryAddress,
			&i.Notes,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByVendor = `-- name: ListOrdersByVendor :many
SELECT DISTINCT o.id, o.user_id, o.delivery_zone_id, o.coupon_id, o.subtotal, o.discount_amount, o.shipping_cost, o.tax_amount, o.total, o.currency, o.payment_method, o.status, o.delivery_address, o.notes, o.delivered_at, o.created_at, o.updated_at
FROM orders o
INNER JOIN order_items oi ON oi.order_id = o.id
WHERE oi.vendor_id = ?
ORDER BY o.created_at DESC
LIMIT ? OFFSET ?
`

type ListOrdersByVendorParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
}

func (q *Queries) ListOrdersByVendor(ctx context.Context, arg ListOrdersByVendorParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByVendor, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeliveryZoneID,
			&i.CouponID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.ShippingCost,
			&i.TaxAmount,
			&i.Total,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.DeliveryAddress,
			&i.Notes,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByVendorSince = `-- name: ListOrdersByVendorSince :many
SELECT DISTINCT o.id, o.user_id, o.delivery_zone_id, o.coupon_id, o.subtotal, o.discount_amount, o.shipping_cost, o.tax_amount, o.total, o.currency, o.payment_method, o.status, o.delivery_address, o.notes, o.delivered_at, o.created_at, o.updated_at
FROM orders o
INNER JOIN order_items oi ON oi.order_id = o.id
WHERE o.status != 'cancelled'
  AND oi.vendor_id = ?
  AND (? IS NULL OR o.created_at >= ?)
ORDER BY o.created_at DESC
`

type ListOrdersByVendorSinceParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	Since    sql.NullTime     `json:"since"`
}

func (q *Queries) ListOrdersByVendorSince(ctx context.Context, arg ListOrdersByVendorSinceParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByVendorSince, arg.VendorID, arg.Since, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeliveryZoneID,
			&i.CouponID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.ShippingCost,
			&i.TaxAmount,
			&i.Total,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.DeliveryAddress,
			&i.Notes,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersSince = `-- name: ListOrdersSince :many
SELECT id, user_id, delivery_zone_id, coupon_id, subtotal, discount_amount, shipping_cost, tax_amount, total, currency, payment_method, status, delivery_address, notes, delivered_at, created_at, updated_at FROM orders
WHERE status != 'cancelled'
  AND (? IS NULL OR created_at >= ?)
`

type ListOrdersSinceParams struct {
	Since sql.NullTime `json:"since"`
}

func (q *Queries) ListOrdersSince(ctx context.Context, arg ListOrdersSinceParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersSince, arg.Since, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeliveryZoneID,
			&i.CouponID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.ShippingCost,
			&i.TaxAmount,
			&i.Total,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.DeliveryAddress,
			&i.Notes,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentOrders = `-- name: ListRecentOrders :many
SELECT id, user_id, delivery_zone_id, coupon_id, subtotal, discount_amount, shipping_cost, tax_amount, total, currency, payment_method, status, delivery_address, notes, delivered_at, created_at, updated_at FROM orders ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRecentOrders(ctx context.Context, limit int32) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listRecentOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeliveryZoneID,
			&i.CouponID,
			&i.Subtotal,
			&i.DiscountAmount,
			&i.ShippingCost,
			&i.TaxAmount,
			&i.Total,
			&i.Currency,
			&i.PaymentMethod,
			&i.Status,
			&i.DeliveryAddress,
			&i.Notes,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderTimestamps = `-- name: SetOrderTimestamps :exec
UPDATE orders SET created_at = ?, updated_at = ? WHERE id = ?
`

type SetOrderTimestampsParams struct {
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
	ID        types.BinaryUUID `json:"id"`
}

func (q *Queries) SetOrderTimestamps(ctx context.Context, arg SetOrderTimestampsParams) error {
	_, err := q.db.ExecContext(ctx, setOrderTimestamps, arg.CreatedAt, arg.UpdatedAt, arg.ID)
	return err
}

const setOrderUpdatedAt = `-- name: SetOrderUpdatedAt :exec
UPDATE orders SET updated_at = ? WHERE id = ?
`

type SetOrderUpdatedAtParams struct {
	UpdatedAt time.Time        `json:"updated_at"`
	ID        types.BinaryUUID `json:"id"`
}

func (q *Queries) SetOrderUpdatedAt(ctx context.Context, arg SetOrderUpdatedAtParams) error {
	_, err := q.db.ExecContext(ctx, setOrderUpdatedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = ?, delivered_at = ? WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status      OrdersStatus     `json:"status"`
	DeliveredAt sql.NullTime     `json:"delivered_at"`
	ID          types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.DeliveredAt, arg.ID)
	return err
}
