// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const countFeaturedProductsAdmin = `-- name: CountFeaturedProductsAdmin :one
SELECT COUNT(*) FROM products p
INNER JOIN vendors v ON p.vendor_id = v.id
WHERE p.featured = true AND p.status IN ('active', 'pending') AND v.suspended = false
`

func (q *Queries) CountFeaturedProductsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeaturedProductsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFeaturedVendorsAdmin = `-- name: CountFeaturedVendorsAdmin :one
SELECT COUNT(*) FROM vendors WHERE is_featured = true AND suspended = false
`

func (q *Queries) CountFeaturedVendorsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeaturedVendorsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPaymentTransaction = `-- name: CreatePaymentTransaction :exec
INSERT INTO payment_transactions (
  id, reference, type, user_id, vendor_id, amount, currency, status, paystack_access_code, metadata
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)
`

type CreatePaymentTransactionParams struct {
	ID                 types.BinaryUUID        `json:"id"`
	Reference          string                  `json:"reference"`
	Type               PaymentTransactionsType `json:"type"`
	UserID             types.BinaryUUID        `json:"user_id"`
	VendorID           *types.BinaryUUID       `json:"vendor_id"`
	Amount             string                  `json:"amount"`
	Currency           string                  `json:"currency"`
	PaystackAccessCode sql.NullString          `json:"paystack_access_code"`
	Metadata           json.RawMessage         `json:"metadata"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createPaymentTransaction,
		arg.ID,
		arg.Reference,
		arg.Type,
		arg.UserID,
		arg.VendorID,
		arg.Amount,
		arg.Currency,
		arg.PaystackAccessCode,
		arg.Metadata,
	)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, reference, type, user_id, vendor_id, amount, currency, status, paystack_access_code, metadata, order_id, subscription_id, created_at, updated_at FROM payment_transactions WHERE id = ? LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id types.BinaryUUID) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.UserID,
		&i.VendorID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaystackAccessCode,
		&i.Metadata,
		&i.OrderID,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, reference, type, user_id, vendor_id, amount, currency, status, paystack_access_code, metadata, order_id, subscription_id, created_at, updated_at FROM payment_transactions WHERE reference = ? LIMIT 1
`

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (PaymentTransaction, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Type,
		&i.UserID,
		&i.VendorID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaystackAccessCode,
		&i.Metadata,
		&i.OrderID,
		&i.SubscriptionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredActiveSubscriptions = `-- name: ListExpiredActiveSubscriptions :many
SELECT id, vendor_id, plan, amount_paid, payment_method, started_at, expires_at, active, created_at, updated_at FROM vendor_subscriptions
WHERE active = true AND expires_at <= NOW()
`

func (q *Queries) ListExpiredActiveSubscriptions(ctx context.Context) ([]VendorSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorSubscription{}
	for rows.Next() {
		var i VendorSubscription
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Plan,
			&i.AmountPaid,
			&i.PaymentMethod,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedProductsAdmin = `-- name: ListFeaturedProductsAdmin :many
SELECT p.id, p.vendor_id, p.category_id, p.name, p.description, p.brand, p.gender, p.sku, p.min_price, p.max_price, p.total_stock, p.rating, p.review_count, p.status, p.bestseller, p.new_arrival, p.featured, p.trending, p.created_at, p.updated_at FROM products p
INNER JOIN vendors v ON p.vendor_id = v.id
WHERE p.featured = true AND p.status IN ('active', 'pending') AND v.suspended = false
ORDER BY p.updated_at DESC
LIMIT ? OFFSET ?
`

type ListFeaturedProductsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeaturedProductsAdmin(ctx context.Context, arg ListFeaturedProductsAdminParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturedProductsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedVendorsAdmin = `-- name: ListFeaturedVendorsAdmin :many
SELECT v.id, v.user_id, v.store_name, v.slug, v.description, v.logo, v.banner, v.contact_phone, v.business_email, v.country, v.city, v.social_links, v.commission_rate, v.rating, v.verified, v.suspended, v.is_featured, v.created_at, v.updated_at FROM vendors v
WHERE v.is_featured = true AND v.suspended = false
ORDER BY v.store_name ASC
LIMIT ? OFFSET ?
`

type ListFeaturedVendorsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeaturedVendorsAdmin(ctx context.Context, arg ListFeaturedVendorsAdminParams) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturedVendorsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.Slug,
			&i.Description,
			&i.Logo,
			&i.Banner,
			&i.ContactPhone,
			&i.BusinessEmail,
			&i.Country,
			&i.City,
			&i.SocialLinks,
			&i.CommissionRate,
			&i.Rating,
			&i.Verified,
			&i.Suspended,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfeatureVendorIfNoActiveSubscription = `-- name: UnfeatureVendorIfNoActiveSubscription :exec
UPDATE vendors v
SET is_featured = false
WHERE v.id = ?
  AND NOT EXISTS (
    SELECT 1 FROM vendor_subscriptions vs
    WHERE vs.vendor_id = v.id AND vs.active = true AND vs.expires_at > NOW()
  )
`

func (q *Queries) UnfeatureVendorIfNoActiveSubscription(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, unfeatureVendorIfNoActiveSubscription, id)
	return err
}

const updatePaymentInitMetadata = `-- name: UpdatePaymentInitMetadata :exec
UPDATE payment_transactions SET metadata = ?, paystack_access_code = ?, updated_at = NOW() WHERE id = ?
`

type UpdatePaymentInitMetadataParams struct {
	Metadata           json.RawMessage  `json:"metadata"`
	PaystackAccessCode sql.NullString   `json:"paystack_access_code"`
	ID                 types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdatePaymentInitMetadata(ctx context.Context, arg UpdatePaymentInitMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentInitMetadata, arg.Metadata, arg.PaystackAccessCode, arg.ID)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payment_transactions
SET status = ?, order_id = ?, subscription_id = ?, updated_at = NOW()
WHERE id = ?
`

type UpdatePaymentStatusParams struct {
	Status         PaymentTransactionsStatus `json:"status"`
	OrderID        *types.BinaryUUID         `json:"order_id"`
	SubscriptionID *types.BinaryUUID         `json:"subscription_id"`
	ID             types.BinaryUUID          `json:"id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus,
		arg.Status,
		arg.OrderID,
		arg.SubscriptionID,
		arg.ID,
	)
	return err
}

const updatePaymentStatusIfPending = `-- name: UpdatePaymentStatusIfPending :execrows
UPDATE payment_transactions
SET status = ?, order_id = ?, subscription_id = ?, updated_at = NOW()
WHERE id = ? AND status = 'pending'
`

type UpdatePaymentStatusIfPendingParams struct {
	Status         PaymentTransactionsStatus `json:"status"`
	OrderID        *types.BinaryUUID         `json:"order_id"`
	SubscriptionID *types.BinaryUUID         `json:"subscription_id"`
	ID             types.BinaryUUID          `json:"id"`
}

func (q *Queries) UpdatePaymentStatusIfPending(ctx context.Context, arg UpdatePaymentStatusIfPendingParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePaymentStatusIfPending,
		arg.Status,
		arg.OrderID,
		arg.SubscriptionID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
