// Code generated by sqlc. DO NOT EDIT.
// source: payouts.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const clearVendorDefaultPayoutMethods = `-- name: ClearVendorDefaultPayoutMethods :exec
UPDATE vendor_payout_methods SET is_default = 0 WHERE vendor_id = ?
`

func (q *Queries) ClearVendorDefaultPayoutMethods(ctx context.Context, vendorID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, clearVendorDefaultPayoutMethods, vendorID)
	return err
}

const clearVendorMpesaRecipientCodes = `-- name: ClearVendorMpesaRecipientCodes :exec
UPDATE vendor_payout_methods SET bank_name = NULL WHERE vendor_id = ? AND type = 'mpesa'
`

func (q *Queries) ClearVendorMpesaRecipientCodes(ctx context.Context, vendorID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, clearVendorMpesaRecipientCodes, vendorID)
	return err
}

const countVendorPayouts = `-- name: CountVendorPayouts :one
SELECT COUNT(*) FROM vendor_payouts WHERE vendor_id = ?
`

func (q *Queries) CountVendorPayouts(ctx context.Context, vendorID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVendorPayouts, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendorPayout = `-- name: CreateVendorPayout :exec
INSERT INTO vendor_payouts (
  id, vendor_id, payout_method_id, amount, currency, status,
  period_start, period_end, reference, initiated_at
) VALUES (?, ?, ?, ?, 'KES', ?, ?, ?, ?, NOW())
`

type CreateVendorPayoutParams struct {
	ID             types.BinaryUUID    `json:"id"`
	VendorID       types.BinaryUUID    `json:"vendor_id"`
	PayoutMethodID types.BinaryUUID    `json:"payout_method_id"`
	Amount         string              `json:"amount"`
	Status         VendorPayoutsStatus `json:"status"`
	PeriodStart    time.Time           `json:"period_start"`
	PeriodEnd      time.Time           `json:"period_end"`
	Reference      sql.NullString      `json:"reference"`
}

func (q *Queries) CreateVendorPayout(ctx context.Context, arg CreateVendorPayoutParams) error {
	_, err := q.db.ExecContext(ctx, createVendorPayout,
		arg.ID,
		arg.VendorID,
		arg.PayoutMethodID,
		arg.Amount,
		arg.Status,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Reference,
	)
	return err
}

const createVendorPayoutItem = `-- name: CreateVendorPayoutItem :exec
INSERT INTO vendor_payout_items (payout_id, order_item_id, amount)
VALUES (?, ?, ?)
`

type CreateVendorPayoutItemParams struct {
	PayoutID    types.BinaryUUID `json:"payout_id"`
	OrderItemID types.BinaryUUID `json:"order_item_id"`
	Amount      string           `json:"amount"`
}

func (q *Queries) CreateVendorPayoutItem(ctx context.Context, arg CreateVendorPayoutItemParams) error {
	_, err := q.db.ExecContext(ctx, createVendorPayoutItem, arg.PayoutID, arg.OrderItemID, arg.Amount)
	return err
}

const createVendorPayoutMethod = `-- name: CreateVendorPayoutMethod :exec
INSERT INTO vendor_payout_methods (
  id, vendor_id, type, account_name, account_ref, is_default
) VALUES (?, ?, 'mpesa', ?, ?, ?)
`

type CreateVendorPayoutMethodParams struct {
	ID          types.BinaryUUID `json:"id"`
	VendorID    types.BinaryUUID `json:"vendor_id"`
	AccountName string           `json:"account_name"`
	AccountRef  string           `json:"account_ref"`
	IsDefault   int16            `json:"is_default"`
}

func (q *Queries) CreateVendorPayoutMethod(ctx context.Context, arg CreateVendorPayoutMethodParams) error {
	_, err := q.db.ExecContext(ctx, createVendorPayoutMethod,
		arg.ID,
		arg.VendorID,
		arg.AccountName,
		arg.AccountRef,
		arg.IsDefault,
	)
	return err
}

const getDefaultVendorMpesaMethod = `-- name: GetDefaultVendorMpesaMethod :one
SELECT id, vendor_id, type, account_name, account_ref, bank_name, is_default, created_at, updated_at FROM vendor_payout_methods
WHERE vendor_id = ? AND type = 'mpesa' AND is_default = 1
LIMIT 1
`

func (q *Queries) GetDefaultVendorMpesaMethod(ctx context.Context, vendorID types.BinaryUUID) (VendorPayoutMethod, error) {
	row := q.db.QueryRowContext(ctx, getDefaultVendorMpesaMethod, vendorID)
	var i VendorPayoutMethod
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Type,
		&i.AccountName,
		&i.AccountRef,
		&i.BankName,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorAvailableBalance = `-- name: GetVendorAvailableBalance :one
SELECT COALESCE(SUM(oi.vendor_earnings), 0) AS balance
FROM order_items oi
INNER JOIN orders o ON o.id = oi.order_id
WHERE oi.vendor_id = ?
  AND o.status = 'delivered'
  AND NOT EXISTS (
    SELECT 1 FROM vendor_payout_items vpi WHERE vpi.order_item_id = oi.id
  )
`

func (q *Queries) GetVendorAvailableBalance(ctx context.Context, vendorID types.BinaryUUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getVendorAvailableBalance, vendorID)
	var balance interface{}
	err := row.Scan(&balance)
	return balance, err
}

const getVendorPayoutMethodByID = `-- name: GetVendorPayoutMethodByID :one
SELECT id, vendor_id, type, account_name, account_ref, bank_name, is_default, created_at, updated_at FROM vendor_payout_methods
WHERE id = ? AND vendor_id = ?
LIMIT 1
`

type GetVendorPayoutMethodByIDParams struct {
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
}

func (q *Queries) GetVendorPayoutMethodByID(ctx context.Context, arg GetVendorPayoutMethodByIDParams) (VendorPayoutMethod, error) {
	row := q.db.QueryRowContext(ctx, getVendorPayoutMethodByID, arg.ID, arg.VendorID)
	var i VendorPayoutMethod
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Type,
		&i.AccountName,
		&i.AccountRef,
		&i.BankName,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type ListPayableOrderItemsRow struct {
	ID             types.BinaryUUID `json:"id"`
	VendorEarnings string           `json:"vendor_earnings"`
	DeliveredAt    sql.NullTime     `json:"delivered_at"`
}

const listPayableOrderItems = `-- name: ListPayableOrderItems :many
SELECT oi.id, oi.vendor_earnings, o.delivered_at
FROM order_items oi
INNER JOIN orders o ON o.id = oi.order_id
WHERE oi.vendor_id = ?
  AND o.status = 'delivered'
  AND NOT EXISTS (
    SELECT 1 FROM vendor_payout_items vpi WHERE vpi.order_item_id = oi.id
  )
ORDER BY o.delivered_at ASC
`

func (q *Queries) ListPayableOrderItems(ctx context.Context, vendorID types.BinaryUUID) ([]ListPayableOrderItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPayableOrderItems, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayableOrderItemsRow
	for rows.Next() {
		var i ListPayableOrderItemsRow
		if err := rows.Scan(&i.ID, &i.VendorEarnings, &i.DeliveredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const listVendorPayoutMethods = `-- name: ListVendorPayoutMethods :many
SELECT id, vendor_id, type, account_name, account_ref, bank_name, is_default, created_at, updated_at FROM vendor_payout_methods
WHERE vendor_id = ?
ORDER BY is_default DESC, created_at ASC
`

func (q *Queries) ListVendorPayoutMethods(ctx context.Context, vendorID types.BinaryUUID) ([]VendorPayoutMethod, error) {
	rows, err := q.db.QueryContext(ctx, listVendorPayoutMethods, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorPayoutMethod
	for rows.Next() {
		var i VendorPayoutMethod
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Type,
			&i.AccountName,
			&i.AccountRef,
			&i.BankName,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const listVendorPayouts = `-- name: ListVendorPayouts :many
SELECT id, vendor_id, payout_method_id, amount, currency, status, period_start, period_end, reference, admin_note, initiated_at, completed_at, created_at, updated_at FROM vendor_payouts
WHERE vendor_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListVendorPayoutsParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
}

func (q *Queries) ListVendorPayouts(ctx context.Context, arg ListVendorPayoutsParams) ([]VendorPayout, error) {
	rows, err := q.db.QueryContext(ctx, listVendorPayouts, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VendorPayout
	for rows.Next() {
		var i VendorPayout
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.PayoutMethodID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Reference,
			&i.AdminNote,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Close()
}

const updateVendorPayoutStatus = `-- name: UpdateVendorPayoutStatus :exec
UPDATE vendor_payouts
SET status = ?,
    reference = ?,
    completed_at = CASE WHEN ? = 'paid' THEN NOW() ELSE completed_at END,
    admin_note = COALESCE(?, admin_note)
WHERE id = ?
`

type UpdateVendorPayoutStatusParams struct {
	Status    VendorPayoutsStatus `json:"status"`
	Reference sql.NullString      `json:"reference"`
	StatusEq  VendorPayoutsStatus `json:"status_eq"`
	AdminNote sql.NullString      `json:"admin_note"`
	ID        types.BinaryUUID    `json:"id"`
}

func (q *Queries) UpdateVendorPayoutStatus(ctx context.Context, arg UpdateVendorPayoutStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateVendorPayoutStatus,
		arg.Status,
		arg.Reference,
		arg.StatusEq,
		arg.AdminNote,
		arg.ID,
	)
	return err
}

const updateVendorPayoutMethodRecipient = `-- name: UpdateVendorPayoutMethodRecipient :exec
UPDATE vendor_payout_methods SET bank_name = ? WHERE id = ? AND vendor_id = ?
`

type UpdateVendorPayoutMethodRecipientParams struct {
	BankName sql.NullString   `json:"bank_name"`
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
}

func (q *Queries) UpdateVendorPayoutMethodRecipient(ctx context.Context, arg UpdateVendorPayoutMethodRecipientParams) error {
	_, err := q.db.ExecContext(ctx, updateVendorPayoutMethodRecipient, arg.BankName, arg.ID, arg.VendorID)
	return err
}
