// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlc

import (
	"context"
	"database/sql"

	"lumi-backend/internal/database/types"
)

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO order_items (
  id, order_id, product_id, variant_id, vendor_id,
  product_name, sku, size, color, image_url,
  unit_price, discount, quantity, subtotal, vendor_earnings, platform_fee
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	ID             types.BinaryUUID `json:"id"`
	OrderID        types.BinaryUUID `json:"order_id"`
	ProductID      types.BinaryUUID `json:"product_id"`
	VariantID      types.BinaryUUID `json:"variant_id"`
	VendorID       types.BinaryUUID `json:"vendor_id"`
	ProductName    string           `json:"product_name"`
	Sku            string           `json:"sku"`
	Size           string           `json:"size"`
	Color          string           `json:"color"`
	ImageUrl       sql.NullString   `json:"image_url"`
	UnitPrice      string           `json:"unit_price"`
	Discount       string           `json:"discount"`
	Quantity       int32            `json:"quantity"`
	Subtotal       string           `json:"subtotal"`
	VendorEarnings string           `json:"vendor_earnings"`
	PlatformFee    string           `json:"platform_fee"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.VendorID,
		arg.ProductName,
		arg.Sku,
		arg.Size,
		arg.Color,
		arg.ImageUrl,
		arg.UnitPrice,
		arg.Discount,
		arg.Quantity,
		arg.Subtotal,
		arg.VendorEarnings,
		arg.PlatformFee,
	)
	return err
}

const getAverageCommissionRate = `-- name: GetAverageCommissionRate :one
SELECT COALESCE(AVG(commission_rate), 10.00) AS commission_rate FROM vendors
`

func (q *Queries) GetAverageCommissionRate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAverageCommissionRate)
	var commission_rate interface{}
	err := row.Scan(&commission_rate)
	return commission_rate, err
}

const getVendorCommissionRate = `-- name: GetVendorCommissionRate :one
SELECT commission_rate FROM vendors WHERE id = ? LIMIT 1
`

func (q *Queries) GetVendorCommissionRate(ctx context.Context, id types.BinaryUUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getVendorCommissionRate, id)
	var commission_rate string
	err := row.Scan(&commission_rate)
	return commission_rate, err
}

const updateAllVendorCommissionRates = `-- name: UpdateAllVendorCommissionRates :exec
UPDATE vendors SET commission_rate = ?, updated_at = NOW()
`

func (q *Queries) UpdateAllVendorCommissionRates(ctx context.Context, commissionRate string) error {
	_, err := q.db.ExecContext(ctx, updateAllVendorCommissionRates, commissionRate)
	return err
}

const updateVendorCommissionRate = `-- name: UpdateVendorCommissionRate :exec
UPDATE vendors SET commission_rate = ?, updated_at = NOW() WHERE id = ?
`

type UpdateVendorCommissionRateParams struct {
	CommissionRate string           `json:"commission_rate"`
	ID             types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateVendorCommissionRate(ctx context.Context, arg UpdateVendorCommissionRateParams) error {
	_, err := q.db.ExecContext(ctx, updateVendorCommissionRate, arg.CommissionRate, arg.ID)
	return err
}
