// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"lumi-backend/internal/database/types"
)

const archiveProduct = `-- name: ArchiveProduct :exec
UPDATE products SET status = 'archived' WHERE id = ? AND vendor_id = ?
`

type ArchiveProductParams struct {
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
}

func (q *Queries) ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error {
	_, err := q.db.ExecContext(ctx, archiveProduct, arg.ID, arg.VendorID)
	return err
}

const clearVendorFeaturedProducts = `-- name: ClearVendorFeaturedProducts :exec
UPDATE products SET featured = false WHERE vendor_id = ?
`

func (q *Queries) ClearVendorFeaturedProducts(ctx context.Context, vendorID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, clearVendorFeaturedProducts, vendorID)
	return err
}

const countAdminProducts = `-- name: CountAdminProducts :one
SELECT COUNT(*) FROM products WHERE status != 'archived'
`

func (q *Queries) CountAdminProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminProductsSearch = `-- name: CountAdminProductsSearch :one
SELECT COUNT(*) FROM products
WHERE status != 'archived'
  AND (? = '' OR name LIKE ? OR brand LIKE ? OR sku LIKE ?)
`

type CountAdminProductsSearchParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountAdminProductsSearch(ctx context.Context, arg CountAdminProductsSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminProductsSearch,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProducts = `-- name: CountAllProducts :one
SELECT COUNT(*) FROM products
`

func (q *Queries) CountAllProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFeaturedProductsByVendorExceptProduct = `-- name: CountFeaturedProductsByVendorExceptProduct :one
SELECT COUNT(*) FROM products
WHERE vendor_id = ? AND featured = true AND id != ?
`

type CountFeaturedProductsByVendorExceptProductParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	ID       types.BinaryUUID `json:"id"`
}

func (q *Queries) CountFeaturedProductsByVendorExceptProduct(ctx context.Context, arg CountFeaturedProductsByVendorExceptProductParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeaturedProductsByVendorExceptProduct, arg.VendorID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutOfStockByVendor = `-- name: CountOutOfStockByVendor :one
SELECT COUNT(*) FROM products WHERE vendor_id = ? AND total_stock = 0
`

func (q *Queries) CountOutOfStockByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOutOfStockByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingProducts = `-- name: CountPendingProducts :one
SELECT COUNT(*) FROM products WHERE status = 'pending'
`

func (q *Queries) CountPendingProducts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingProducts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingProductsSearch = `-- name: CountPendingProductsSearch :one
SELECT COUNT(*) FROM products
WHERE status = 'pending'
  AND (? = '' OR name LIKE ? OR brand LIKE ? OR sku LIKE ?)
`

type CountPendingProductsSearchParams struct {
	Search string `json:"search"`
}

func (q *Queries) CountPendingProductsSearch(ctx context.Context, arg CountPendingProductsSearchParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingProductsSearch,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByVendor = `-- name: CountProductsByVendor :one
SELECT COUNT(*) FROM products WHERE vendor_id = ?
`

func (q *Queries) CountProductsByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProductsByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT COUNT(*) FROM products p
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.status = 'active'
  AND p.total_stock > 0
  AND (? IS NULL OR p.name LIKE CONCAT('%', ?, '%') OR p.description LIKE CONCAT('%', ?, '%') OR p.brand LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR c.slug = ? OR c.name = ?)
  AND (? IS NULL OR EXISTS (
    SELECT 1 FROM categories child WHERE child.id = p.category_id AND child.slug = ?
  ))
  AND (? IS NULL OR p.brand = ?)
  AND (? IS NULL OR p.gender = ?)
  AND (? IS NULL OR p.vendor_id = ?)
  AND (? IS NULL OR EXISTS (
    SELECT 1 FROM product_variants pv WHERE pv.product_id = p.id AND pv.size = ? AND pv.deleted_at IS NULL AND pv.stock > 0
  ))
  AND (? IS NULL OR EXISTS (
    SELECT 1 FROM product_variants pv WHERE pv.product_id = p.id AND pv.color = ? AND pv.deleted_at IS NULL AND pv.stock > 0
  ))
  AND (? IS NULL OR p.min_price >= ?)
  AND (? IS NULL OR p.max_price <= ?)
  AND (? IS NULL OR p.rating >= ?)
  AND (? = false OR p.featured = true)
  AND (? = false OR p.trending = true)
  AND (? = false OR p.bestseller = true)
  AND (? = false OR p.created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY))
  AND (? = false OR EXISTS (
    SELECT 1 FROM product_variants pv WHERE pv.product_id = p.id AND pv.discount > 0 AND pv.deleted_at IS NULL
  ))
`

type CountSearchProductsParams struct {
	Q              interface{}        `json:"q"`
	Category       sql.NullString     `json:"category"`
	Subcategory    sql.NullString     `json:"subcategory"`
	Brand          sql.NullString     `json:"brand"`
	Gender         NullProductsGender `json:"gender"`
	VendorID       *types.BinaryUUID  `json:"vendor_id"`
	Size           sql.NullString     `json:"size"`
	Color          sql.NullString     `json:"color"`
	MinPrice       sql.NullString     `json:"min_price"`
	MaxPrice       sql.NullString     `json:"max_price"`
	MinRating      sql.NullString     `json:"min_rating"`
	FeaturedOnly   interface{}        `json:"featured_only"`
	TrendingOnly   interface{}        `json:"trending_only"`
	BestsellerOnly interface{}        `json:"bestseller_only"`
	NewArrivalOnly interface{}        `json:"new_arrival_only"`
	OnSaleOnly     interface{}        `json:"on_sale_only"`
}

func (q *Queries) CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchProducts,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Category,
		arg.Category,
		arg.Category,
		arg.Subcategory,
		arg.Subcategory,
		arg.Brand,
		arg.Brand,
		arg.Gender,
		arg.Gender,
		arg.VendorID,
		arg.VendorID,
		arg.Size,
		arg.Size,
		arg.Color,
		arg.Color,
		arg.MinPrice,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MaxPrice,
		arg.MinRating,
		arg.MinRating,
		arg.FeaturedOnly,
		arg.TrendingOnly,
		arg.BestsellerOnly,
		arg.NewArrivalOnly,
		arg.OnSaleOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVendorProducts = `-- name: CountVendorProducts :one
SELECT COUNT(*) FROM products WHERE vendor_id = ?
`

func (q *Queries) CountVendorProducts(ctx context.Context, vendorID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVendorProducts, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :exec
INSERT INTO products (
  id, vendor_id, category_id, name, description, brand, gender, sku,
  min_price, max_price, total_stock, status,
  bestseller, new_arrival, featured, trending
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProductParams struct {
	ID          types.BinaryUUID `json:"id"`
	VendorID    types.BinaryUUID `json:"vendor_id"`
	CategoryID  types.BinaryUUID `json:"category_id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Brand       string           `json:"brand"`
	Gender      ProductsGender   `json:"gender"`
	Sku         string           `json:"sku"`
	MinPrice    string           `json:"min_price"`
	MaxPrice    string           `json:"max_price"`
	TotalStock  int32            `json:"total_stock"`
	Status      ProductsStatus   `json:"status"`
	Bestseller  int16            `json:"bestseller"`
	NewArrival  int16            `json:"new_arrival"`
	Featured    int16            `json:"featured"`
	Trending    int16            `json:"trending"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) error {
	_, err := q.db.ExecContext(ctx, createProduct,
		arg.ID,
		arg.VendorID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.Gender,
		arg.Sku,
		arg.MinPrice,
		arg.MaxPrice,
		arg.TotalStock,
		arg.Status,
		arg.Bestseller,
		arg.NewArrival,
		arg.Featured,
		arg.Trending,
	)
	return err
}

const createProductImage = `-- name: CreateProductImage :exec
INSERT INTO product_images (id, product_id, url, alt, sort_order, is_primary)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateProductImageParams struct {
	ID        types.BinaryUUID `json:"id"`
	ProductID types.BinaryUUID `json:"product_id"`
	Url       string           `json:"url"`
	Alt       sql.NullString   `json:"alt"`
	SortOrder int32            `json:"sort_order"`
	IsPrimary int16            `json:"is_primary"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) error {
	_, err := q.db.ExecContext(ctx, createProductImage,
		arg.ID,
		arg.ProductID,
		arg.Url,
		arg.Alt,
		arg.SortOrder,
		arg.IsPrimary,
	)
	return err
}

const createProductVariant = `-- name: CreateProductVariant :exec
INSERT INTO product_variants (
  id, product_id, size, color, color_hex, price, discount, stock, sku
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProductVariantParams struct {
	ID        types.BinaryUUID `json:"id"`
	ProductID types.BinaryUUID `json:"product_id"`
	Size      string           `json:"size"`
	Color     string           `json:"color"`
	ColorHex  sql.NullString   `json:"color_hex"`
	Price     string           `json:"price"`
	Discount  string           `json:"discount"`
	Stock     int32            `json:"stock"`
	Sku       sql.NullString   `json:"sku"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) error {
	_, err := q.db.ExecContext(ctx, createProductVariant,
		arg.ID,
		arg.ProductID,
		arg.Size,
		arg.Color,
		arg.ColorHex,
		arg.Price,
		arg.Discount,
		arg.Stock,
		arg.Sku,
	)
	return err
}

const decrementProductStock = `-- name: DecrementProductStock :execrows
UPDATE product_variants
SET stock = stock - ?, updated_at = NOW()
WHERE id = ? AND stock >= ? AND deleted_at IS NULL
`

type DecrementProductStockParams struct {
	Stock   int32            `json:"stock"`
	ID      types.BinaryUUID `json:"id"`
	Stock_2 int32            `json:"stock_2"`
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, decrementProductStock, arg.Stock, arg.ID, arg.Stock_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProductImages = `-- name: DeleteProductImages :exec
DELETE FROM product_images WHERE product_id = ?
`

func (q *Queries) DeleteProductImages(ctx context.Context, productID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deleteProductImages, productID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE id = ? AND status != 'archived' LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id types.BinaryUUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Gender,
		&i.Sku,
		&i.MinPrice,
		&i.MaxPrice,
		&i.TotalStock,
		&i.Rating,
		&i.ReviewCount,
		&i.Status,
		&i.Bestseller,
		&i.NewArrival,
		&i.Featured,
		&i.Trending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByIDAny = `-- name: GetProductByIDAny :one
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE id = ? LIMIT 1
`

func (q *Queries) GetProductByIDAny(ctx context.Context, id types.BinaryUUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByIDAny, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Gender,
		&i.Sku,
		&i.MinPrice,
		&i.MaxPrice,
		&i.TotalStock,
		&i.Rating,
		&i.ReviewCount,
		&i.Status,
		&i.Bestseller,
		&i.NewArrival,
		&i.Featured,
		&i.Trending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByVendor = `-- name: GetProductByVendor :one
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE id = ? AND vendor_id = ? LIMIT 1
`

type GetProductByVendorParams struct {
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
}

func (q *Queries) GetProductByVendor(ctx context.Context, arg GetProductByVendorParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProductByVendor, arg.ID, arg.VendorID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.Brand,
		&i.Gender,
		&i.Sku,
		&i.MinPrice,
		&i.MaxPrice,
		&i.TotalStock,
		&i.Rating,
		&i.ReviewCount,
		&i.Status,
		&i.Bestseller,
		&i.NewArrival,
		&i.Featured,
		&i.Trending,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductPriceRange = `-- name: GetProductPriceRange :one
SELECT COALESCE(MIN(min_price), 0) AS min_price, COALESCE(MAX(max_price), 0) AS max_price
FROM products WHERE status = 'active' AND total_stock > 0
`

type GetProductPriceRangeRow struct {
	MinPrice interface{} `json:"min_price"`
	MaxPrice interface{} `json:"max_price"`
}

func (q *Queries) GetProductPriceRange(ctx context.Context) (GetProductPriceRangeRow, error) {
	row := q.db.QueryRowContext(ctx, getProductPriceRange)
	var i GetProductPriceRangeRow
	err := row.Scan(&i.MinPrice, &i.MaxPrice)
	return i, err
}

const getProductVariant = `-- name: GetProductVariant :one
SELECT id, product_id, size, color, color_hex, price, discount, effective_price, stock, sku, deleted_at, created_at, updated_at FROM product_variants WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetProductVariant(ctx context.Context, id types.BinaryUUID) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariant, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.Color,
		&i.ColorHex,
		&i.Price,
		&i.Discount,
		&i.EffectivePrice,
		&i.Stock,
		&i.Sku,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductVariantByProductSizeColor = `-- name: GetProductVariantByProductSizeColor :one
SELECT id, product_id, size, color, color_hex, price, discount, effective_price, stock, sku, deleted_at, created_at, updated_at FROM product_variants
WHERE product_id = ? AND size = ? AND color = ? AND deleted_at IS NULL
LIMIT 1
`

type GetProductVariantByProductSizeColorParams struct {
	ProductID types.BinaryUUID `json:"product_id"`
	Size      string           `json:"size"`
	Color     string           `json:"color"`
}

func (q *Queries) GetProductVariantByProductSizeColor(ctx context.Context, arg GetProductVariantByProductSizeColorParams) (ProductVariant, error) {
	row := q.db.QueryRowContext(ctx, getProductVariantByProductSizeColor, arg.ProductID, arg.Size, arg.Color)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Size,
		&i.Color,
		&i.ColorHex,
		&i.Price,
		&i.Discount,
		&i.EffectivePrice,
		&i.Stock,
		&i.Sku,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hideOutOfStockProductByVendor = `-- name: HideOutOfStockProductByVendor :exec
UPDATE products SET status = 'hidden' WHERE id = ? AND vendor_id = ? AND total_stock = 0
`

type HideOutOfStockProductByVendorParams struct {
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
}

func (q *Queries) HideOutOfStockProductByVendor(ctx context.Context, arg HideOutOfStockProductByVendorParams) error {
	_, err := q.db.ExecContext(ctx, hideOutOfStockProductByVendor, arg.ID, arg.VendorID)
	return err
}

const listAdminProducts = `-- name: ListAdminProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE status != 'archived'
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAdminProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdminProducts(ctx context.Context, arg ListAdminProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listAdminProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminProductsSearch = `-- name: ListAdminProductsSearch :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status != 'archived'
  AND (? = '' OR name LIKE ? OR brand LIKE ? OR sku LIKE ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAdminProductsSearchParams struct {
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListAdminProductsSearch(ctx context.Context, arg ListAdminProductsSearchParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listAdminProductsSearch,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctBrands = `-- name: ListDistinctBrands :many
SELECT DISTINCT brand FROM products WHERE status = 'active' AND total_stock > 0 ORDER BY brand
`

func (q *Queries) ListDistinctBrands(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var brand string
		if err := rows.Scan(&brand); err != nil {
			return nil, err
		}
		items = append(items, brand)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCategories = `-- name: ListDistinctCategories :many
SELECT DISTINCT c.name AS category
FROM products p
INNER JOIN categories c ON c.id = p.category_id
WHERE p.status = 'active' AND p.total_stock > 0
ORDER BY category
`

func (q *Queries) ListDistinctCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctColors = `-- name: ListDistinctColors :many
SELECT DISTINCT pv.color AS color_name
FROM product_variants pv
INNER JOIN products p ON p.id = pv.product_id
WHERE p.status = 'active' AND p.total_stock > 0 AND pv.deleted_at IS NULL AND pv.stock > 0
ORDER BY color_name
`

func (q *Queries) ListDistinctColors(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctColors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var color_name string
		if err := rows.Scan(&color_name); err != nil {
			return nil, err
		}
		items = append(items, color_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSizes = `-- name: ListDistinctSizes :many
SELECT DISTINCT pv.size AS size_val
FROM product_variants pv
INNER JOIN products p ON p.id = pv.product_id
WHERE p.status = 'active' AND p.total_stock > 0 AND pv.deleted_at IS NULL AND pv.stock > 0
ORDER BY size_val
`

func (q *Queries) ListDistinctSizes(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctSizes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var size_val string
		if err := rows.Scan(&size_val); err != nil {
			return nil, err
		}
		items = append(items, size_val)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctSubcategories = `-- name: ListDistinctSubcategories :many
SELECT DISTINCT c.name AS subcategory
FROM products p
INNER JOIN categories c ON c.id = p.category_id
WHERE p.status = 'active' AND p.total_stock > 0 AND c.parent_id IS NOT NULL
ORDER BY subcategory
`

func (q *Queries) ListDistinctSubcategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDistinctSubcategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var subcategory string
		if err := rows.Scan(&subcategory); err != nil {
			return nil, err
		}
		items = append(items, subcategory)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomepageBestsellerProducts = `-- name: ListHomepageBestsellerProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active' AND total_stock > 0 AND bestseller = true
ORDER BY review_count DESC, rating DESC
LIMIT ?
`

func (q *Queries) ListHomepageBestsellerProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listHomepageBestsellerProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomepageFeaturedProducts = `-- name: ListHomepageFeaturedProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active' AND total_stock > 0 AND featured = true
ORDER BY updated_at DESC
LIMIT ?
`

func (q *Queries) ListHomepageFeaturedProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listHomepageFeaturedProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomepageNewArrivalProducts = `-- name: ListHomepageNewArrivalProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active' AND total_stock > 0
  AND created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListHomepageNewArrivalProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listHomepageNewArrivalProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomepageRecentProducts = `-- name: ListHomepageRecentProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active' AND total_stock > 0
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListHomepageRecentProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listHomepageRecentProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomepageTrendingProducts = `-- name: ListHomepageTrendingProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active' AND total_stock > 0 AND trending = true
ORDER BY review_count DESC, rating DESC
LIMIT ?
`

func (q *Queries) ListHomepageTrendingProducts(ctx context.Context, limit int32) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listHomepageTrendingProducts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockByVendor = `-- name: ListLowStockByVendor :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE vendor_id = ? AND total_stock > 0 AND total_stock <= 10
`

func (q *Queries) ListLowStockByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listLowStockByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProducts = `-- name: ListPendingProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE status = 'pending'
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPendingProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingProducts(ctx context.Context, arg ListPendingProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listPendingProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProductsSearch = `-- name: ListPendingProductsSearch :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'pending'
  AND (? = '' OR name LIKE ? OR brand LIKE ? OR sku LIKE ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPendingProductsSearchParams struct {
	Search string `json:"search"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListPendingProductsSearch(ctx context.Context, arg ListPendingProductsSearchParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listPendingProductsSearch,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Search,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductIDsByVendor = `-- name: ListProductIDsByVendor :many
SELECT id FROM products WHERE vendor_id = ?
`

func (q *Queries) ListProductIDsByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]types.BinaryUUID, error) {
	rows, err := q.db.QueryContext(ctx, listProductIDsByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.BinaryUUID{}
	for rows.Next() {
		var id types.BinaryUUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, url, alt, sort_order, is_primary, created_at FROM product_images WHERE product_id = ? ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID types.BinaryUUID) ([]ProductImage, error) {
	rows, err := q.db.QueryContext(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.Alt,
			&i.SortOrder,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, product_id, size, color, color_hex, price, discount, effective_price, stock, sku, deleted_at, created_at, updated_at FROM product_variants
WHERE product_id = ? AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListProductVariants(ctx context.Context, productID types.BinaryUUID) ([]ProductVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Size,
			&i.Color,
			&i.ColorHex,
			&i.Price,
			&i.Discount,
			&i.EffectivePrice,
			&i.Stock,
			&i.Sku,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByVendor = `-- name: ListProductsByVendor :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE vendor_id = ?
`

func (q *Queries) ListProductsByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProductsByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRandomRelatedProducts = `-- name: ListRandomRelatedProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products
WHERE status = 'active' AND total_stock > 0 AND id != ? AND category_id = ?
ORDER BY RAND()
LIMIT ?
`

type ListRandomRelatedProductsParams struct {
	ID         types.BinaryUUID `json:"id"`
	CategoryID types.BinaryUUID `json:"category_id"`
	Limit      int32            `json:"limit"`
}

func (q *Queries) ListRandomRelatedProducts(ctx context.Context, arg ListRandomRelatedProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listRandomRelatedProducts, arg.ID, arg.CategoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorProducts = `-- name: ListVendorProducts :many
SELECT id, vendor_id, category_id, name, description, brand, gender, sku, min_price, max_price, total_stock, rating, review_count, status, bestseller, new_arrival, featured, trending, created_at, updated_at FROM products WHERE vendor_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListVendorProductsParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
}

func (q *Queries) ListVendorProducts(ctx context.Context, arg ListVendorProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listVendorProducts, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moderateProduct = `-- name: ModerateProduct :exec
UPDATE products SET status = ? WHERE id = ?
`

type ModerateProductParams struct {
	Status ProductsStatus   `json:"status"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) ModerateProduct(ctx context.Context, arg ModerateProductParams) error {
	_, err := q.db.ExecContext(ctx, moderateProduct, arg.Status, arg.ID)
	return err
}

const refreshBestsellerProducts = `-- name: RefreshBestsellerProducts :exec
UPDATE products SET bestseller = false WHERE bestseller = true
`

func (q *Queries) RefreshBestsellerProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, refreshBestsellerProducts)
	return err
}

const refreshNewArrivalProducts = `-- name: RefreshNewArrivalProducts :exec
UPDATE products SET new_arrival = (created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY))
`

func (q *Queries) RefreshNewArrivalProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, refreshNewArrivalProducts)
	return err
}

const refreshProductVariantCaches = `-- name: RefreshProductVariantCaches :exec
UPDATE products p
SET
  min_price = (
    SELECT COALESCE(MIN(pv.effective_price), 0) FROM product_variants pv
    WHERE pv.product_id = p.id AND pv.deleted_at IS NULL
  ),
  max_price = (
    SELECT COALESCE(MAX(pv.effective_price), 0) FROM product_variants pv
    WHERE pv.product_id = p.id AND pv.deleted_at IS NULL
  ),
  total_stock = (
    SELECT COALESCE(SUM(pv.stock), 0) FROM product_variants pv
    WHERE pv.product_id = p.id AND pv.deleted_at IS NULL
  ),
  updated_at = NOW()
WHERE p.id = ?
`

func (q *Queries) RefreshProductVariantCaches(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, refreshProductVariantCaches, id)
	return err
}

const refreshTrendingProducts = `-- name: RefreshTrendingProducts :exec
UPDATE products SET trending = false WHERE trending = true
`

func (q *Queries) RefreshTrendingProducts(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, refreshTrendingProducts)
	return err
}

const restoreProductByVendor = `-- name: RestoreProductByVendor :exec
UPDATE products SET status = 'active' WHERE id = ? AND vendor_id = ? AND status = 'archived'
`

type RestoreProductByVendorParams struct {
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
}

func (q *Queries) RestoreProductByVendor(ctx context.Context, arg RestoreProductByVendorParams) error {
	_, err := q.db.ExecContext(ctx, restoreProductByVendor, arg.ID, arg.VendorID)
	return err
}

const searchProducts = `-- name: SearchProducts :many
SELECT p.id, p.vendor_id, p.category_id, p.name, p.description, p.brand, p.gender, p.sku, p.min_price, p.max_price, p.total_stock, p.rating, p.review_count, p.status, p.bestseller, p.new_arrival, p.featured, p.trending, p.created_at, p.updated_at FROM products p
LEFT JOIN categories c ON c.id = p.category_id
WHERE p.status = 'active'
  AND p.total_stock > 0
  AND (? IS NULL OR p.name LIKE CONCAT('%', ?, '%') OR p.description LIKE CONCAT('%', ?, '%') OR p.brand LIKE CONCAT('%', ?, '%'))
  AND (? IS NULL OR c.slug = ? OR c.name = ?)
  AND (? IS NULL OR EXISTS (
    SELECT 1 FROM categories child
    WHERE child.id = p.category_id AND child.slug = ?
  ))
  AND (? IS NULL OR p.brand = ?)
  AND (? IS NULL OR p.gender = ?)
  AND (? IS NULL OR p.vendor_id = ?)
  AND (? IS NULL OR EXISTS (
    SELECT 1 FROM product_variants pv
    WHERE pv.product_id = p.id AND pv.size = ? AND pv.deleted_at IS NULL AND pv.stock > 0
  ))
  AND (? IS NULL OR EXISTS (
    SELECT 1 FROM product_variants pv
    WHERE pv.product_id = p.id AND pv.color = ? AND pv.deleted_at IS NULL AND pv.stock > 0
  ))
  AND (? IS NULL OR p.min_price >= ?)
  AND (? IS NULL OR p.max_price <= ?)
  AND (? IS NULL OR p.rating >= ?)
  AND (? = false OR p.featured = true)
  AND (? = false OR p.trending = true)
  AND (? = false OR p.bestseller = true)
  AND (? = false OR p.created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY))
  AND (? = false OR EXISTS (
    SELECT 1 FROM product_variants pv WHERE pv.product_id = p.id AND pv.discount > 0 AND pv.deleted_at IS NULL
  ))
ORDER BY
  CASE WHEN ? = 'popular' THEN p.review_count END DESC,
  CASE WHEN ? = 'popular' THEN p.rating END DESC,
  CASE WHEN ? = 'rating' THEN p.rating END DESC,
  CASE WHEN ? = 'trending' THEN p.trending END DESC,
  CASE WHEN ? = 'bestsellers' THEN p.bestseller END DESC,
  CASE WHEN ? = 'price-asc' THEN p.min_price END ASC,
  CASE WHEN ? = 'price-desc' THEN p.max_price END DESC,
  CASE WHEN ? = 'newest' THEN p.created_at END DESC,
  p.created_at DESC
LIMIT ? OFFSET ?
`

type SearchProductsParams struct {
	Q              interface{}        `json:"q"`
	Category       sql.NullString     `json:"category"`
	Subcategory    sql.NullString     `json:"subcategory"`
	Brand          sql.NullString     `json:"brand"`
	Gender         NullProductsGender `json:"gender"`
	VendorID       *types.BinaryUUID  `json:"vendor_id"`
	Size           sql.NullString     `json:"size"`
	Color          sql.NullString     `json:"color"`
	MinPrice       sql.NullString     `json:"min_price"`
	MaxPrice       sql.NullString     `json:"max_price"`
	MinRating      sql.NullString     `json:"min_rating"`
	FeaturedOnly   interface{}        `json:"featured_only"`
	TrendingOnly   interface{}        `json:"trending_only"`
	BestsellerOnly interface{}        `json:"bestseller_only"`
	NewArrivalOnly interface{}        `json:"new_arrival_only"`
	OnSaleOnly     interface{}        `json:"on_sale_only"`
	SortBy         interface{}        `json:"sort_by"`
	Limit          int32              `json:"limit"`
	Offset         int32              `json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, searchProducts,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Q,
		arg.Category,
		arg.Category,
		arg.Category,
		arg.Subcategory,
		arg.Subcategory,
		arg.Brand,
		arg.Brand,
		arg.Gender,
		arg.Gender,
		arg.VendorID,
		arg.VendorID,
		arg.Size,
		arg.Size,
		arg.Color,
		arg.Color,
		arg.MinPrice,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MaxPrice,
		arg.MinRating,
		arg.MinRating,
		arg.FeaturedOnly,
		arg.TrendingOnly,
		arg.BestsellerOnly,
		arg.NewArrivalOnly,
		arg.OnSaleOnly,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.SortBy,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.Brand,
			&i.Gender,
			&i.Sku,
			&i.MinPrice,
			&i.MaxPrice,
			&i.TotalStock,
			&i.Rating,
			&i.ReviewCount,
			&i.Status,
			&i.Bestseller,
			&i.NewArrival,
			&i.Featured,
			&i.Trending,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductCreatedAt = `-- name: SetProductCreatedAt :exec
UPDATE products SET created_at = ? WHERE id = ?
`

type SetProductCreatedAtParams struct {
	CreatedAt time.Time        `json:"created_at"`
	ID        types.BinaryUUID `json:"id"`
}

func (q *Queries) SetProductCreatedAt(ctx context.Context, arg SetProductCreatedAtParams) error {
	_, err := q.db.ExecContext(ctx, setProductCreatedAt, arg.CreatedAt, arg.ID)
	return err
}

const setProductFeatured = `-- name: SetProductFeatured :exec
UPDATE products SET featured = ? WHERE id = ?
`

type SetProductFeaturedParams struct {
	Featured int16            `json:"featured"`
	ID       types.BinaryUUID `json:"id"`
}

func (q *Queries) SetProductFeatured(ctx context.Context, arg SetProductFeaturedParams) error {
	_, err := q.db.ExecContext(ctx, setProductFeatured, arg.Featured, arg.ID)
	return err
}

const setProductFeaturedByVendor = `-- name: SetProductFeaturedByVendor :exec
UPDATE products SET featured = ? WHERE id = ? AND vendor_id = ?
`

type SetProductFeaturedByVendorParams struct {
	Featured int16            `json:"featured"`
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
}

func (q *Queries) SetProductFeaturedByVendor(ctx context.Context, arg SetProductFeaturedByVendorParams) error {
	_, err := q.db.ExecContext(ctx, setProductFeaturedByVendor, arg.Featured, arg.ID, arg.VendorID)
	return err
}

const softDeleteProductVariantsByProduct = `-- name: SoftDeleteProductVariantsByProduct :exec
UPDATE product_variants SET deleted_at = NOW(), updated_at = NOW()
WHERE product_id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProductVariantsByProduct(ctx context.Context, productID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteProductVariantsByProduct, productID)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET name = COALESCE(?, name),
    description = COALESCE(?, description),
    brand = COALESCE(?, brand),
    category_id = COALESCE(?, category_id),
    gender = COALESCE(?, gender),
    status = COALESCE(?, status)
WHERE id = ? AND vendor_id = ?
`

type UpdateProductParams struct {
	Name        sql.NullString     `json:"name"`
	Description sql.NullString     `json:"description"`
	Brand       sql.NullString     `json:"brand"`
	CategoryID  *types.BinaryUUID  `json:"category_id"`
	Gender      NullProductsGender `json:"gender"`
	Status      NullProductsStatus `json:"status"`
	ID          types.BinaryUUID   `json:"id"`
	VendorID    types.BinaryUUID   `json:"vendor_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Brand,
		arg.CategoryID,
		arg.Gender,
		arg.Status,
		arg.ID,
		arg.VendorID,
	)
	return err
}

const updateProductInventory = `-- name: UpdateProductInventory :exec
UPDATE products SET total_stock = ? WHERE id = ?
`

type UpdateProductInventoryParams struct {
	TotalStock int32            `json:"total_stock"`
	ID         types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateProductInventory(ctx context.Context, arg UpdateProductInventoryParams) error {
	_, err := q.db.ExecContext(ctx, updateProductInventory, arg.TotalStock, arg.ID)
	return err
}

const updateProductRating = `-- name: UpdateProductRating :exec
UPDATE products SET rating = ?, review_count = ? WHERE id = ?
`

type UpdateProductRatingParams struct {
	Rating      string           `json:"rating"`
	ReviewCount int32            `json:"review_count"`
	ID          types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateProductRating, arg.Rating, arg.ReviewCount, arg.ID)
	return err
}

const updateProductVariant = `-- name: UpdateProductVariant :exec
UPDATE product_variants
SET size = COALESCE(?, size),
    color = COALESCE(?, color),
    color_hex = COALESCE(?, color_hex),
    price = COALESCE(?, price),
    discount = COALESCE(?, discount),
    stock = COALESCE(?, stock),
    sku = COALESCE(?, sku),
    updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateProductVariantParams struct {
	Size     sql.NullString   `json:"size"`
	Color    sql.NullString   `json:"color"`
	ColorHex sql.NullString   `json:"color_hex"`
	Price    sql.NullString   `json:"price"`
	Discount sql.NullString   `json:"discount"`
	Stock    sql.NullInt32    `json:"stock"`
	Sku      sql.NullString   `json:"sku"`
	ID       types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) error {
	_, err := q.db.ExecContext(ctx, updateProductVariant,
		arg.Size,
		arg.Color,
		arg.ColorHex,
		arg.Price,
		arg.Discount,
		arg.Stock,
		arg.Sku,
		arg.ID,
	)
	return err
}
