// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

type Querier interface {
	AddCollectionProduct(ctx context.Context, arg AddCollectionProductParams) error
	AddPromotionProduct(ctx context.Context, arg AddPromotionProductParams) error
	AddWishlistItemForSession(ctx context.Context, arg AddWishlistItemForSessionParams) error
	AddWishlistItemForUser(ctx context.Context, arg AddWishlistItemForUserParams) error
	ApproveApplication(ctx context.Context, arg ApproveApplicationParams) error
	ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error
	AssignGuestCartToUser(ctx context.Context, arg AssignGuestCartToUserParams) error
	AvgRatingByProduct(ctx context.Context, productID types.BinaryUUID) (interface{}, error)
	AvgRatingByVendor(ctx context.Context, vendorID types.BinaryUUID) (interface{}, error)
	ClearCartItems(ctx context.Context, cartID types.BinaryUUID) error
	ClearVendorFeaturedProducts(ctx context.Context, vendorID types.BinaryUUID) error
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	CountAdminProducts(ctx context.Context) (int64, error)
	CountAdminProductsSearch(ctx context.Context, arg CountAdminProductsSearchParams) (int64, error)
	CountAllCollections(ctx context.Context) (int64, error)
	CountAllCoupons(ctx context.Context) (int64, error)
	CountAllOrders(ctx context.Context) (int64, error)
	CountAllProducts(ctx context.Context) (int64, error)
	CountAllPromotions(ctx context.Context) (int64, error)
	CountAllSubscriptions(ctx context.Context, arg CountAllSubscriptionsParams) (int64, error)
	CountAllVendors(ctx context.Context) (int64, error)
	CountCouponUsesByUser(ctx context.Context, arg CountCouponUsesByUserParams) (int64, error)
	CountCustomers(ctx context.Context) (int64, error)
	CountDistinctOrderCustomers(ctx context.Context) (int64, error)
	CountFeaturedProductsAdmin(ctx context.Context) (int64, error)
	CountFeaturedProductsByVendorExceptProduct(ctx context.Context, arg CountFeaturedProductsByVendorExceptProductParams) (int64, error)
	CountFeaturedVendorsAdmin(ctx context.Context) (int64, error)
	CountOrdersByUser(ctx context.Context, userID types.BinaryUUID) (int64, error)
	CountOrdersByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error)
	CountOutOfStockByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error)
	CountPendingApplications(ctx context.Context) (int64, error)
	CountPendingProducts(ctx context.Context) (int64, error)
	CountPendingProductsSearch(ctx context.Context, arg CountPendingProductsSearchParams) (int64, error)
	CountProductsByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error)
	CountReviewsByProduct(ctx context.Context, productID types.BinaryUUID) (int64, error)
	CountReviewsByProductID(ctx context.Context, productID types.BinaryUUID) (int64, error)
	CountReviewsByProductIDs(ctx context.Context, productIds []types.BinaryUUID) (int64, error)
	CountReviewsByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error)
	CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error)
	CountSearchVendors(ctx context.Context) (int64, error)
	CountSubscriptionsByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVendorProducts(ctx context.Context, vendorID types.BinaryUUID) (int64, error)
	CountVendorsAdmin(ctx context.Context) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) error
	CreateCart(ctx context.Context, arg CreateCartParams) error
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateCollection(ctx context.Context, arg CreateCollectionParams) error
	CreateCoupon(ctx context.Context, arg CreateCouponParams) error
	CreateCouponUse(ctx context.Context, arg CreateCouponUseParams) error
	CreateDeliveryZone(ctx context.Context, arg CreateDeliveryZoneParams) error
	CreateDeliveryZoneArea(ctx context.Context, arg CreateDeliveryZoneAreaParams) error
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) error
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) error
	CreatePromotion(ctx context.Context, arg CreatePromotionParams) error
	CreateReview(ctx context.Context, arg CreateReviewParams) error
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateVendor(ctx context.Context, arg CreateVendorParams) error
	CreateVendorApplication(ctx context.Context, arg CreateVendorApplicationParams) error
	DeactivateSubscription(ctx context.Context, id types.BinaryUUID) error
	DeactivateVendorSubscriptions(ctx context.Context, vendorID types.BinaryUUID) error
	DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (int64, error)
	DeleteCartByID(ctx context.Context, id types.BinaryUUID) error
	DeleteCartBySessionKey(ctx context.Context, sessionKey sql.NullString) error
	DeleteCartItem(ctx context.Context, id types.BinaryUUID) error
	DeleteCollectionProducts(ctx context.Context, collectionID types.BinaryUUID) error
	DeleteProductImages(ctx context.Context, productID types.BinaryUUID) error
	DeletePromotionProducts(ctx context.Context, promotionID types.BinaryUUID) error
	DeleteWishlistBySessionKey(ctx context.Context, sessionKey sql.NullString) error
	DisableUser(ctx context.Context, id types.BinaryUUID) error
	EnableUser(ctx context.Context, id types.BinaryUUID) error
	FeatureVendor(ctx context.Context, arg FeatureVendorParams) error
	FindDeliveryZoneByCity(ctx context.Context, lower string) (DeliveryZone, error)
	GetActiveSubscription(ctx context.Context, vendorID types.BinaryUUID) (VendorSubscription, error)
	GetAddressByIDAndUser(ctx context.Context, arg GetAddressByIDAndUserParams) (Address, error)
	GetApplicationByID(ctx context.Context, id types.BinaryUUID) (VendorApplication, error)
	GetApprovedApplicationByBusinessEmail(ctx context.Context, lower string) (VendorApplication, error)
	GetAverageCommissionRate(ctx context.Context) (interface{}, error)
	GetCartBySessionKey(ctx context.Context, sessionKey sql.NullString) (Cart, error)
	GetCartByUserID(ctx context.Context, userID *types.BinaryUUID) (Cart, error)
	GetCartItemByCartAndVariant(ctx context.Context, arg GetCartItemByCartAndVariantParams) (CartItem, error)
	GetCategoryByID(ctx context.Context, id types.BinaryUUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCollectionByID(ctx context.Context, id types.BinaryUUID) (Collection, error)
	GetCollectionBySlug(ctx context.Context, slug string) (Collection, error)
	GetCouponByCode(ctx context.Context, upper string) (Coupon, error)
	GetCouponByID(ctx context.Context, id types.BinaryUUID) (Coupon, error)
	GetDeliveryZoneByID(ctx context.Context, id types.BinaryUUID) (DeliveryZone, error)
	GetDeliveryZoneByVendorAndName(ctx context.Context, arg GetDeliveryZoneByVendorAndNameParams) (DeliveryZone, error)
	GetFeaturedVendors(ctx context.Context, limit int32) ([]Vendor, error)
	GetIdempotencyKey(ctx context.Context, keyHash string) (IdempotencyKey, error)
	GetLatestApplicationByBusinessEmail(ctx context.Context, lower string) (VendorApplication, error)
	GetLatestApplicationByUser(ctx context.Context, userID *types.BinaryUUID) (VendorApplication, error)
	GetOrderByID(ctx context.Context, id types.BinaryUUID) (Order, error)
	GetOrderByIDAndUser(ctx context.Context, arg GetOrderByIDAndUserParams) (Order, error)
	GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error)
	GetPaymentByID(ctx context.Context, id types.BinaryUUID) (PaymentTransaction, error)
	GetPaymentByReference(ctx context.Context, reference string) (PaymentTransaction, error)
	GetPendingApplicationByBusinessEmail(ctx context.Context, lower string) (VendorApplication, error)
	GetPendingApplicationByUser(ctx context.Context, userID *types.BinaryUUID) (VendorApplication, error)
	GetProductByID(ctx context.Context, id types.BinaryUUID) (Product, error)
	GetProductByIDAny(ctx context.Context, id types.BinaryUUID) (Product, error)
	GetProductByVendor(ctx context.Context, arg GetProductByVendorParams) (Product, error)
	GetProductPriceRange(ctx context.Context) (GetProductPriceRangeRow, error)
	GetProductVariant(ctx context.Context, id types.BinaryUUID) (ProductVariant, error)
	GetProductVariantByProductSizeColor(ctx context.Context, arg GetProductVariantByProductSizeColorParams) (ProductVariant, error)
	GetPromotionByID(ctx context.Context, id types.BinaryUUID) (Promotion, error)
	GetReviewByID(ctx context.Context, id types.BinaryUUID) (Review, error)
	GetReviewByProductAndUser(ctx context.Context, arg GetReviewByProductAndUserParams) (Review, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id types.BinaryUUID) (User, error)
	GetVariantByProductSizeColor(ctx context.Context, arg GetVariantByProductSizeColorParams) (ProductVariant, error)
	GetVendorByBusinessEmail(ctx context.Context, lower string) (Vendor, error)
	GetVendorByID(ctx context.Context, id types.BinaryUUID) (Vendor, error)
	GetVendorByIDAdmin(ctx context.Context, id types.BinaryUUID) (Vendor, error)
	GetVendorByUserID(ctx context.Context, userID types.BinaryUUID) (Vendor, error)
	GetVendorCommissionRate(ctx context.Context, id types.BinaryUUID) (string, error)
	GetVendorDeliveryZoneByID(ctx context.Context, arg GetVendorDeliveryZoneByIDParams) (DeliveryZone, error)
	GetVendorShippingRate(ctx context.Context, arg GetVendorShippingRateParams) (GetVendorShippingRateRow, error)
	HideOutOfStockProductByVendor(ctx context.Context, arg HideOutOfStockProductByVendorParams) error
	IncrementCouponUses(ctx context.Context, id types.BinaryUUID) error
	InsertVendorCategory(ctx context.Context, arg InsertVendorCategoryParams) error
	InvalidateUserResetTokens(ctx context.Context, userID types.BinaryUUID) error
	ListActiveCollections(ctx context.Context) ([]Collection, error)
	ListActivePromotions(ctx context.Context) ([]Promotion, error)
	ListAddressesByUser(ctx context.Context, userID types.BinaryUUID) ([]Address, error)
	ListAdminProducts(ctx context.Context, arg ListAdminProductsParams) ([]Product, error)
	ListAdminProductsSearch(ctx context.Context, arg ListAdminProductsSearchParams) ([]Product, error)
	ListAllActiveCategories(ctx context.Context) ([]Category, error)
	ListAllCollections(ctx context.Context, arg ListAllCollectionsParams) ([]Collection, error)
	ListAllCoupons(ctx context.Context, arg ListAllCouponsParams) ([]Coupon, error)
	ListAllOrders(ctx context.Context, arg ListAllOrdersParams) ([]Order, error)
	ListAllPromotions(ctx context.Context, arg ListAllPromotionsParams) ([]Promotion, error)
	ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]VendorSubscription, error)
	ListCartItemsByCartID(ctx context.Context, cartID types.BinaryUUID) ([]ListCartItemsByCartIDRow, error)
	ListCheckoutDeliveryZones(ctx context.Context) ([]ListCheckoutDeliveryZonesRow, error)
	ListChildCategories(ctx context.Context, parentID *types.BinaryUUID) ([]Category, error)
	ListCollectionProductIDs(ctx context.Context, collectionID types.BinaryUUID) ([]types.BinaryUUID, error)
	ListDeliveryZonesByVendor(ctx context.Context, vendorID *types.BinaryUUID) ([]DeliveryZone, error)
	ListDistinctBrands(ctx context.Context) ([]string, error)
	ListDistinctCategories(ctx context.Context) ([]string, error)
	ListDistinctColors(ctx context.Context) ([]string, error)
	ListDistinctSizes(ctx context.Context) ([]string, error)
	ListDistinctSubcategories(ctx context.Context) ([]string, error)
	ListExpiredActiveSubscriptions(ctx context.Context) ([]VendorSubscription, error)
	ListFeaturedProductsAdmin(ctx context.Context, arg ListFeaturedProductsAdminParams) ([]Product, error)
	ListFeaturedVendorsAdmin(ctx context.Context, arg ListFeaturedVendorsAdminParams) ([]Vendor, error)
	ListHomepageBestsellerProducts(ctx context.Context, limit int32) ([]Product, error)
	ListHomepageFeaturedProducts(ctx context.Context, limit int32) ([]Product, error)
	ListHomepageNewArrivalProducts(ctx context.Context, limit int32) ([]Product, error)
	ListHomepageRecentProducts(ctx context.Context, limit int32) ([]Product, error)
	ListHomepageTrendingProducts(ctx context.Context, limit int32) ([]Product, error)
	ListLowStockByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]Product, error)
	ListOnSaleProductIDs(ctx context.Context) ([]types.BinaryUUID, error)
	ListOrderItemsByOrder(ctx context.Context, orderID types.BinaryUUID) ([]OrderItem, error)
	ListOrderItemsByOrderIDs(ctx context.Context, orderIds []types.BinaryUUID) ([]OrderItem, error)
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	ListOrdersByVendor(ctx context.Context, arg ListOrdersByVendorParams) ([]Order, error)
	ListOrdersByVendorSince(ctx context.Context, arg ListOrdersByVendorSinceParams) ([]Order, error)
	ListOrdersSince(ctx context.Context, arg ListOrdersSinceParams) ([]Order, error)
	ListPendingApplications(ctx context.Context, arg ListPendingApplicationsParams) ([]VendorApplication, error)
	ListPendingProducts(ctx context.Context, arg ListPendingProductsParams) ([]Product, error)
	ListPendingProductsSearch(ctx context.Context, arg ListPendingProductsSearchParams) ([]Product, error)
	ListProductIDsByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]types.BinaryUUID, error)
	ListProductImages(ctx context.Context, productID types.BinaryUUID) ([]ProductImage, error)
	ListProductVariants(ctx context.Context, productID types.BinaryUUID) ([]ProductVariant, error)
	ListProductsByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]Product, error)
	ListPromotionProductIDs(ctx context.Context, promotionID types.BinaryUUID) ([]types.BinaryUUID, error)
	ListRandomRelatedProducts(ctx context.Context, arg ListRandomRelatedProductsParams) ([]Product, error)
	ListRecentOrders(ctx context.Context, limit int32) ([]Order, error)
	ListReviewsByProduct(ctx context.Context, arg ListReviewsByProductParams) ([]Review, error)
	ListReviewsByProductID(ctx context.Context, productID types.BinaryUUID) ([]int16, error)
	ListReviewsByProductIDs(ctx context.Context, arg ListReviewsByProductIDsParams) ([]Review, error)
	ListRootCategories(ctx context.Context) ([]Category, error)
	ListSubscriptionsByVendor(ctx context.Context, arg ListSubscriptionsByVendorParams) ([]VendorSubscription, error)
	ListTopVendorsForAnalytics(ctx context.Context, limit int32) ([]Vendor, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListVendorCategoryIDs(ctx context.Context, vendorID types.BinaryUUID) ([]types.BinaryUUID, error)
	ListVendorProducts(ctx context.Context, arg ListVendorProductsParams) ([]Product, error)
	ListVendorShippingRatesByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]ListVendorShippingRatesByVendorRow, error)
	ListVendorsAdmin(ctx context.Context, arg ListVendorsAdminParams) ([]Vendor, error)
	ListWishlistBySessionKey(ctx context.Context, sessionKey sql.NullString) ([]types.BinaryUUID, error)
	ListWishlistByUser(ctx context.Context, userID *types.BinaryUUID) ([]types.BinaryUUID, error)
	LockIdempotencyKey(ctx context.Context, id types.BinaryUUID) (int64, error)
	MarkPasswordResetTokenUsed(ctx context.Context, id types.BinaryUUID) error
	MarkUserPasswordSet(ctx context.Context, id types.BinaryUUID) error
	ModerateProduct(ctx context.Context, arg ModerateProductParams) error
	RefreshBestsellerProducts(ctx context.Context) error
	RefreshNewArrivalProducts(ctx context.Context) error
	RefreshProductVariantCaches(ctx context.Context, id types.BinaryUUID) error
	RefreshTrendingProducts(ctx context.Context) error
	RejectApplication(ctx context.Context, arg RejectApplicationParams) error
	RemoveWishlistItemBySession(ctx context.Context, arg RemoveWishlistItemBySessionParams) error
	RemoveWishlistItemByUser(ctx context.Context, arg RemoveWishlistItemByUserParams) error
	RestoreProductByVendor(ctx context.Context, arg RestoreProductByVendorParams) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchVendors(ctx context.Context, arg SearchVendorsParams) ([]Vendor, error)
	SetCollectionActive(ctx context.Context, arg SetCollectionActiveParams) error
	SetCouponActive(ctx context.Context, arg SetCouponActiveParams) error
	SetDeliveryZoneActive(ctx context.Context, arg SetDeliveryZoneActiveParams) error
	SetOrderTimestamps(ctx context.Context, arg SetOrderTimestampsParams) error
	SetOrderUpdatedAt(ctx context.Context, arg SetOrderUpdatedAtParams) error
	SetProductCreatedAt(ctx context.Context, arg SetProductCreatedAtParams) error
	SetProductFeatured(ctx context.Context, arg SetProductFeaturedParams) error
	SetProductFeaturedByVendor(ctx context.Context, arg SetProductFeaturedByVendorParams) error
	SetPromotionActive(ctx context.Context, arg SetPromotionActiveParams) error
	SoftDeleteAddress(ctx context.Context, arg SoftDeleteAddressParams) error
	SoftDeleteCollection(ctx context.Context, id types.BinaryUUID) error
	SoftDeleteCoupon(ctx context.Context, id types.BinaryUUID) error
	SoftDeleteProductVariantsByProduct(ctx context.Context, productID types.BinaryUUID) error
	SoftDeletePromotion(ctx context.Context, id types.BinaryUUID) error
	SoftDeleteVendorShippingRate(ctx context.Context, arg SoftDeleteVendorShippingRateParams) error
	UnfeatureVendorIfNoActiveSubscription(ctx context.Context, id types.BinaryUUID) error
	UpdateAllVendorCommissionRates(ctx context.Context, commissionRate string) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error
	UpdateCoupon(ctx context.Context, arg UpdateCouponParams) error
	UpdateDeliveryZone(ctx context.Context, arg UpdateDeliveryZoneParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdatePaymentInitMetadata(ctx context.Context, arg UpdatePaymentInitMetadataParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
	UpdatePaymentStatusIfPending(ctx context.Context, arg UpdatePaymentStatusIfPendingParams) (int64, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductInventory(ctx context.Context, arg UpdateProductInventoryParams) error
	UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) error
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) error
	UpdatePromotion(ctx context.Context, arg UpdatePromotionParams) error
	UpdateReviewReply(ctx context.Context, arg UpdateReviewReplyParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateVendorCommissionRate(ctx context.Context, arg UpdateVendorCommissionRateParams) error
	UpdateVendorProfile(ctx context.Context, arg UpdateVendorProfileParams) error
	UpdateVendorRating(ctx context.Context, arg UpdateVendorRatingParams) error
	UpsertVendorShippingRate(ctx context.Context, arg UpsertVendorShippingRateParams) error
	UserHasUsedPasswordResetToken(ctx context.Context, userID types.BinaryUUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
