// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlc

import (
	"context"
	"database/sql"
	"strings"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const avgRatingByProduct = `-- name: AvgRatingByProduct :one
SELECT COALESCE(AVG(rating), 0) FROM reviews WHERE product_id = ?
`

func (q *Queries) AvgRatingByProduct(ctx context.Context, productID types.BinaryUUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, avgRatingByProduct, productID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const avgRatingByVendor = `-- name: AvgRatingByVendor :one
SELECT COALESCE(AVG(rating), 0) FROM reviews WHERE vendor_id = ?
`

func (q *Queries) AvgRatingByVendor(ctx context.Context, vendorID types.BinaryUUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, avgRatingByVendor, vendorID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const countReviewsByProduct = `-- name: CountReviewsByProduct :one
SELECT COUNT(*) FROM reviews WHERE product_id = ?
`

func (q *Queries) CountReviewsByProduct(ctx context.Context, productID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByProductID = `-- name: CountReviewsByProductID :one
SELECT COUNT(*) FROM reviews WHERE product_id = ?
`

func (q *Queries) CountReviewsByProductID(ctx context.Context, productID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsByProductID, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByProductIDs = `-- name: CountReviewsByProductIDs :one
SELECT COUNT(*) FROM reviews
WHERE product_id IN (/*SLICE:product_ids*/?)
`

func (q *Queries) CountReviewsByProductIDs(ctx context.Context, productIds []types.BinaryUUID) (int64, error) {
	query := countReviewsByProductIDs
	var queryParams []interface{}
	if len(productIds) > 0 {
		for _, v := range productIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(productIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	row := q.db.QueryRowContext(ctx, query, queryParams...)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByVendor = `-- name: CountReviewsByVendor :one
SELECT COUNT(*) FROM reviews WHERE vendor_id = ?
`

func (q *Queries) CountReviewsByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :exec
INSERT INTO reviews (id, product_id, vendor_id, user_id, order_id, rating, comment)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateReviewParams struct {
	ID        types.BinaryUUID  `json:"id"`
	ProductID types.BinaryUUID  `json:"product_id"`
	VendorID  types.BinaryUUID  `json:"vendor_id"`
	UserID    types.BinaryUUID  `json:"user_id"`
	OrderID   *types.BinaryUUID `json:"order_id"`
	Rating    int16             `json:"rating"`
	Comment   string            `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.ExecContext(ctx, createReview,
		arg.ID,
		arg.ProductID,
		arg.VendorID,
		arg.UserID,
		arg.OrderID,
		arg.Rating,
		arg.Comment,
	)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, product_id, vendor_id, user_id, order_id, rating, comment, vendor_reply, vendor_reply_at, created_at, updated_at FROM reviews WHERE id = ? LIMIT 1
`

func (q *Queries) GetReviewByID(ctx context.Context, id types.BinaryUUID) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VendorID,
		&i.UserID,
		&i.OrderID,
		&i.Rating,
		&i.Comment,
		&i.VendorReply,
		&i.VendorReplyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByProductAndUser = `-- name: GetReviewByProductAndUser :one
SELECT id, product_id, vendor_id, user_id, order_id, rating, comment, vendor_reply, vendor_reply_at, created_at, updated_at FROM reviews WHERE product_id = ? AND user_id = ? LIMIT 1
`

type GetReviewByProductAndUserParams struct {
	ProductID types.BinaryUUID `json:"product_id"`
	UserID    types.BinaryUUID `json:"user_id"`
}

func (q *Queries) GetReviewByProductAndUser(ctx context.Context, arg GetReviewByProductAndUserParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByProductAndUser, arg.ProductID, arg.UserID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.VendorID,
		&i.UserID,
		&i.OrderID,
		&i.Rating,
		&i.Comment,
		&i.VendorReply,
		&i.VendorReplyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsByProduct = `-- name: ListReviewsByProduct :many
SELECT id, product_id, vendor_id, user_id, order_id, rating, comment, vendor_reply, vendor_reply_at, created_at, updated_at FROM reviews WHERE product_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListReviewsByProductParams struct {
	ProductID types.BinaryUUID `json:"product_id"`
	Limit     int32            `json:"limit"`
	Offset    int32            `json:"offset"`
}

func (q *Queries) ListReviewsByProduct(ctx context.Context, arg ListReviewsByProductParams) ([]Review, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByProduct, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VendorID,
			&i.UserID,
			&i.OrderID,
			&i.Rating,
			&i.Comment,
			&i.VendorReply,
			&i.VendorReplyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProductID = `-- name: ListReviewsByProductID :many
SELECT rating FROM reviews WHERE product_id = ?
`

func (q *Queries) ListReviewsByProductID(ctx context.Context, productID types.BinaryUUID) ([]int16, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int16{}
	for rows.Next() {
		var rating int16
		if err := rows.Scan(&rating); err != nil {
			return nil, err
		}
		items = append(items, rating)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByProductIDs = `-- name: ListReviewsByProductIDs :many
SELECT r.id, r.product_id, r.vendor_id, r.user_id, r.order_id, r.rating, r.comment, r.vendor_reply, r.vendor_reply_at, r.created_at, r.updated_at
FROM reviews r
WHERE r.product_id IN (/*SLICE:product_ids*/?)
ORDER BY r.created_at DESC
LIMIT ? OFFSET ?
`

type ListReviewsByProductIDsParams struct {
	ProductIds []types.BinaryUUID `json:"product_ids"`
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
}

func (q *Queries) ListReviewsByProductIDs(ctx context.Context, arg ListReviewsByProductIDsParams) ([]Review, error) {
	query := listReviewsByProductIDs
	var queryParams []interface{}
	if len(arg.ProductIds) > 0 {
		for _, v := range arg.ProductIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(arg.ProductIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	queryParams = append(queryParams, arg.Offset)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.VendorID,
			&i.UserID,
			&i.OrderID,
			&i.Rating,
			&i.Comment,
			&i.VendorReply,
			&i.VendorReplyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewReply = `-- name: UpdateReviewReply :exec
UPDATE reviews
SET vendor_reply = ?, vendor_reply_at = ?
WHERE id = ?
`

type UpdateReviewReplyParams struct {
	VendorReply   sql.NullString   `json:"vendor_reply"`
	VendorReplyAt sql.NullTime     `json:"vendor_reply_at"`
	ID            types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateReviewReply(ctx context.Context, arg UpdateReviewReplyParams) error {
	_, err := q.db.ExecContext(ctx, updateReviewReply, arg.VendorReply, arg.VendorReplyAt, arg.ID)
	return err
}
