// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const countAllSubscriptions = `-- name: CountAllSubscriptions :one
SELECT COUNT(*) FROM vendor_subscriptions
WHERE (? IS NULL OR active = ?)
`

type CountAllSubscriptionsParams struct {
	Active sql.NullBool `json:"active"`
}

func (q *Queries) CountAllSubscriptions(ctx context.Context, arg CountAllSubscriptionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllSubscriptions, arg.Active, arg.Active)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscriptionsByVendor = `-- name: CountSubscriptionsByVendor :one
SELECT COUNT(*) FROM vendor_subscriptions WHERE vendor_id = ?
`

func (q *Queries) CountSubscriptionsByVendor(ctx context.Context, vendorID types.BinaryUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubscriptionsByVendor, vendorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO vendor_subscriptions (
  id, vendor_id, plan, amount_paid, payment_method, started_at, expires_at, active
) VALUES (?, ?, ?, ?, ?, ?, ?, true)
`

type CreateSubscriptionParams struct {
	ID            types.BinaryUUID        `json:"id"`
	VendorID      types.BinaryUUID        `json:"vendor_id"`
	Plan          VendorSubscriptionsPlan `json:"plan"`
	AmountPaid    string                  `json:"amount_paid"`
	PaymentMethod string                  `json:"payment_method"`
	StartedAt     time.Time               `json:"started_at"`
	ExpiresAt     time.Time               `json:"expires_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createSubscription,
		arg.ID,
		arg.VendorID,
		arg.Plan,
		arg.AmountPaid,
		arg.PaymentMethod,
		arg.StartedAt,
		arg.ExpiresAt,
	)
	return err
}

const deactivateSubscription = `-- name: DeactivateSubscription :exec
UPDATE vendor_subscriptions SET active = false WHERE id = ?
`

func (q *Queries) DeactivateSubscription(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deactivateSubscription, id)
	return err
}

const deactivateVendorSubscriptions = `-- name: DeactivateVendorSubscriptions :exec
UPDATE vendor_subscriptions SET active = false WHERE vendor_id = ? AND active = true
`

func (q *Queries) DeactivateVendorSubscriptions(ctx context.Context, vendorID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, deactivateVendorSubscriptions, vendorID)
	return err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, vendor_id, plan, amount_paid, payment_method, started_at, expires_at, active, created_at, updated_at FROM vendor_subscriptions WHERE vendor_id = ? AND active = true LIMIT 1
`

func (q *Queries) GetActiveSubscription(ctx context.Context, vendorID types.BinaryUUID) (VendorSubscription, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscription, vendorID)
	var i VendorSubscription
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Plan,
		&i.AmountPaid,
		&i.PaymentMethod,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSubscriptions = `-- name: ListAllSubscriptions :many
SELECT id, vendor_id, plan, amount_paid, payment_method, started_at, expires_at, active, created_at, updated_at FROM vendor_subscriptions
WHERE (? IS NULL OR active = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListAllSubscriptionsParams struct {
	Active sql.NullBool `json:"active"`
	Limit  int32        `json:"limit"`
	Offset int32        `json:"offset"`
}

func (q *Queries) ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]VendorSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listAllSubscriptions,
		arg.Active,
		arg.Active,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorSubscription{}
	for rows.Next() {
		var i VendorSubscription
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Plan,
			&i.AmountPaid,
			&i.PaymentMethod,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByVendor = `-- name: ListSubscriptionsByVendor :many
SELECT id, vendor_id, plan, amount_paid, payment_method, started_at, expires_at, active, created_at, updated_at FROM vendor_subscriptions WHERE vendor_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSubscriptionsByVendorParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	Limit    int32            `json:"limit"`
	Offset   int32            `json:"offset"`
}

func (q *Queries) ListSubscriptionsByVendor(ctx context.Context, arg ListSubscriptionsByVendorParams) ([]VendorSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listSubscriptionsByVendor, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorSubscription{}
	for rows.Next() {
		var i VendorSubscription
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Plan,
			&i.AmountPaid,
			&i.PaymentMethod,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
