// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"lumi-backend/internal/database/types"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :exec
INSERT INTO addresses (id, user_id, label, street, city, state, country, zip_code, is_default)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAddressParams struct {
	ID        types.BinaryUUID `json:"id"`
	UserID    types.BinaryUUID `json:"user_id"`
	Label     string           `json:"label"`
	Street    string           `json:"street"`
	City      string           `json:"city"`
	State     string           `json:"state"`
	Country   string           `json:"country"`
	ZipCode   string           `json:"zip_code"`
	IsDefault int16            `json:"is_default"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) error {
	_, err := q.db.ExecContext(ctx, createAddress,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.Street,
		arg.City,
		arg.State,
		arg.Country,
		arg.ZipCode,
		arg.IsDefault,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (id, user_id, token, expires_at)
VALUES (?, ?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	ID        types.BinaryUUID `json:"id"`
	UserID    types.BinaryUUID `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt time.Time        `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, full_name, email, phone, password, role, disabled)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID       types.BinaryUUID `json:"id"`
	FullName string           `json:"full_name"`
	Email    string           `json:"email"`
	Phone    string           `json:"phone"`
	Password string           `json:"password"`
	Role     UsersRole        `json:"role"`
	Disabled int16            `json:"disabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Role,
		arg.Disabled,
	)
	return err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM addresses WHERE id = ? AND user_id = ?
`

type DeleteAddressParams struct {
	ID     types.BinaryUUID `json:"id"`
	UserID types.BinaryUUID `json:"user_id"`
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.ExecContext(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const disableUser = `-- name: DisableUser :exec
UPDATE users SET disabled = true WHERE id = ?
`

func (q *Queries) DisableUser(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, disableUser, id)
	return err
}

const enableUser = `-- name: EnableUser :exec
UPDATE users SET disabled = false WHERE id = ?
`

func (q *Queries) EnableUser(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, enableUser, id)
	return err
}

const getAddressByIDAndUser = `-- name: GetAddressByIDAndUser :one
SELECT id, user_id, label, street, city, state, country, zip_code, is_default, created_at, updated_at FROM addresses WHERE id = ? AND user_id = ? LIMIT 1
`

type GetAddressByIDAndUserParams struct {
	ID     types.BinaryUUID `json:"id"`
	UserID types.BinaryUUID `json:"user_id"`
}

func (q *Queries) GetAddressByIDAndUser(ctx context.Context, arg GetAddressByIDAndUserParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, getAddressByIDAndUser, arg.ID, arg.UserID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.Street,
		&i.City,
		&i.State,
		&i.Country,
		&i.ZipCode,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, expires_at, used, created_at FROM password_reset_tokens WHERE token = ? AND used = false AND expires_at > NOW() LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, phone, password, role, avatar, disabled, email_verified_at, password_set_at, created_at, updated_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Role,
		&i.Avatar,
		&i.Disabled,
		&i.EmailVerifiedAt,
		&i.PasswordSetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, phone, password, role, avatar, disabled, email_verified_at, password_set_at, created_at, updated_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id types.BinaryUUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Role,
		&i.Avatar,
		&i.Disabled,
		&i.EmailVerifiedAt,
		&i.PasswordSetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateUserResetTokens = `-- name: InvalidateUserResetTokens :exec
UPDATE password_reset_tokens SET used = true WHERE user_id = ? AND used = false
`

func (q *Queries) InvalidateUserResetTokens(ctx context.Context, userID types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, invalidateUserResetTokens, userID)
	return err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT id, user_id, label, street, city, state, country, zip_code, is_default, created_at, updated_at FROM addresses WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAddressesByUser(ctx context.Context, userID types.BinaryUUID) ([]Address, error) {
	rows, err := q.db.QueryContext(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Address{}
	for rows.Next() {
		var i Address
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.Street,
			&i.City,
			&i.State,
			&i.Country,
			&i.ZipCode,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, phone, role, avatar, disabled, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        types.BinaryUUID `json:"id"`
	FullName  string           `json:"full_name"`
	Email     string           `json:"email"`
	Phone     string           `json:"phone"`
	Role      UsersRole        `json:"role"`
	Avatar    sql.NullString   `json:"avatar"`
	Disabled  int16            `json:"disabled"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Avatar,
			&i.Disabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens SET used = true WHERE id = ?
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, id)
	return err
}

const markUserPasswordSet = `-- name: MarkUserPasswordSet :exec
UPDATE users SET password_set_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) MarkUserPasswordSet(ctx context.Context, id types.BinaryUUID) error {
	_, err := q.db.ExecContext(ctx, markUserPasswordSet, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password = ? WHERE id = ?
`

type UpdateUserPasswordParams struct {
	Password string           `json:"password"`
	ID       types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE users
SET full_name = COALESCE(?, full_name),
    phone = COALESCE(?, phone),
    avatar = COALESCE(?, avatar)
WHERE id = ?
`

type UpdateUserProfileParams struct {
	FullName sql.NullString   `json:"full_name"`
	Phone    sql.NullString   `json:"phone"`
	Avatar   sql.NullString   `json:"avatar"`
	ID       types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.FullName,
		arg.Phone,
		arg.Avatar,
		arg.ID,
	)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role UsersRole        `json:"role"`
	ID   types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const userHasUsedPasswordResetToken = `-- name: UserHasUsedPasswordResetToken :one
SELECT EXISTS(
  SELECT 1 FROM password_reset_tokens WHERE user_id = ? AND used = TRUE
) AS has_used
`

func (q *Queries) UserHasUsedPasswordResetToken(ctx context.Context, userID types.BinaryUUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasUsedPasswordResetToken, userID)
	var has_used bool
	err := row.Scan(&has_used)
	return has_used, err
}
