// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendor_shipping.sql

package sqlc

import (
	"context"
	"time"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const getVendorShippingRate = `-- name: GetVendorShippingRate :one
SELECT id, vendor_id, zone_id, fee, created_at, updated_at
FROM vendor_shipping_rates
WHERE vendor_id = ? AND zone_id = ? AND deleted_at IS NULL
LIMIT 1
`

type GetVendorShippingRateParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	ZoneID   types.BinaryUUID `json:"zone_id"`
}

type GetVendorShippingRateRow struct {
	ID        types.BinaryUUID `json:"id"`
	VendorID  types.BinaryUUID `json:"vendor_id"`
	ZoneID    types.BinaryUUID `json:"zone_id"`
	Fee       string           `json:"fee"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

func (q *Queries) GetVendorShippingRate(ctx context.Context, arg GetVendorShippingRateParams) (GetVendorShippingRateRow, error) {
	row := q.db.QueryRowContext(ctx, getVendorShippingRate, arg.VendorID, arg.ZoneID)
	var i GetVendorShippingRateRow
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.ZoneID,
		&i.Fee,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendorShippingRatesByVendor = `-- name: ListVendorShippingRatesByVendor :many
SELECT vsr.id, vsr.vendor_id, vsr.zone_id, vsr.fee, vsr.created_at, vsr.updated_at,
       dz.name AS zone_name, dz.estimated_days AS zone_estimated_days
FROM vendor_shipping_rates vsr
INNER JOIN delivery_zones dz ON dz.id = vsr.zone_id
WHERE vsr.vendor_id = ? AND vsr.deleted_at IS NULL
ORDER BY dz.name
`

type ListVendorShippingRatesByVendorRow struct {
	ID                types.BinaryUUID `json:"id"`
	VendorID          types.BinaryUUID `json:"vendor_id"`
	ZoneID            types.BinaryUUID `json:"zone_id"`
	Fee               string           `json:"fee"`
	CreatedAt         time.Time        `json:"created_at"`
	UpdatedAt         time.Time        `json:"updated_at"`
	ZoneName          string           `json:"zone_name"`
	ZoneEstimatedDays string           `json:"zone_estimated_days"`
}

func (q *Queries) ListVendorShippingRatesByVendor(ctx context.Context, vendorID types.BinaryUUID) ([]ListVendorShippingRatesByVendorRow, error) {
	rows, err := q.db.QueryContext(ctx, listVendorShippingRatesByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorShippingRatesByVendorRow{}
	for rows.Next() {
		var i ListVendorShippingRatesByVendorRow
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.ZoneID,
			&i.Fee,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ZoneName,
			&i.ZoneEstimatedDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVendorShippingRate = `-- name: SoftDeleteVendorShippingRate :exec
UPDATE vendor_shipping_rates SET deleted_at = NOW(), updated_at = NOW()
WHERE vendor_id = ? AND zone_id = ? AND deleted_at IS NULL
`

type SoftDeleteVendorShippingRateParams struct {
	VendorID types.BinaryUUID `json:"vendor_id"`
	ZoneID   types.BinaryUUID `json:"zone_id"`
}

func (q *Queries) SoftDeleteVendorShippingRate(ctx context.Context, arg SoftDeleteVendorShippingRateParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteVendorShippingRate, arg.VendorID, arg.ZoneID)
	return err
}

const upsertVendorShippingRate = `-- name: UpsertVendorShippingRate :exec
INSERT INTO vendor_shipping_rates (id, vendor_id, zone_id, fee)
VALUES (?, ?, ?, ?)
ON DUPLICATE KEY UPDATE fee = VALUES(fee), deleted_at = NULL, updated_at = NOW()
`

type UpsertVendorShippingRateParams struct {
	ID       types.BinaryUUID `json:"id"`
	VendorID types.BinaryUUID `json:"vendor_id"`
	ZoneID   types.BinaryUUID `json:"zone_id"`
	Fee      string           `json:"fee"`
}

func (q *Queries) UpsertVendorShippingRate(ctx context.Context, arg UpsertVendorShippingRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertVendorShippingRate,
		arg.ID,
		arg.VendorID,
		arg.ZoneID,
		arg.Fee,
	)
	return err
}
