// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/Reactguru24/lumiafrica/internal/database/types"
)

const approveApplication = `-- name: ApproveApplication :exec
UPDATE vendor_applications
SET status = 'approved', review_note = ?, reviewed_at = ?
WHERE id = ?
`

type ApproveApplicationParams struct {
	ReviewNote sql.NullString   `json:"review_note"`
	ReviewedAt sql.NullTime     `json:"reviewed_at"`
	ID         types.BinaryUUID `json:"id"`
}

func (q *Queries) ApproveApplication(ctx context.Context, arg ApproveApplicationParams) error {
	_, err := q.db.ExecContext(ctx, approveApplication, arg.ReviewNote, arg.ReviewedAt, arg.ID)
	return err
}

const countPendingApplications = `-- name: CountPendingApplications :one
SELECT COUNT(*) FROM vendor_applications WHERE status = 'pending'
`

func (q *Queries) CountPendingApplications(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingApplications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchVendors = `-- name: CountSearchVendors :one
SELECT COUNT(*) FROM vendors WHERE suspended = false
`

func (q *Queries) CountSearchVendors(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchVendors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVendorsAdmin = `-- name: CountVendorsAdmin :one
SELECT COUNT(*) FROM vendors
`

func (q *Queries) CountVendorsAdmin(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVendorsAdmin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVendor = `-- name: CreateVendor :exec
INSERT INTO vendors (
  id, user_id, store_name, slug, description, logo, banner,
  contact_phone, business_email, country, city, social_links
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateVendorParams struct {
	ID            types.BinaryUUID `json:"id"`
	UserID        types.BinaryUUID `json:"user_id"`
	StoreName     string           `json:"store_name"`
	Slug          string           `json:"slug"`
	Description   sql.NullString   `json:"description"`
	Logo          string           `json:"logo"`
	Banner        sql.NullString   `json:"banner"`
	ContactPhone  string           `json:"contact_phone"`
	BusinessEmail string           `json:"business_email"`
	Country       string           `json:"country"`
	City          string           `json:"city"`
	SocialLinks   *json.RawMessage `json:"social_links"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) error {
	_, err := q.db.ExecContext(ctx, createVendor,
		arg.ID,
		arg.UserID,
		arg.StoreName,
		arg.Slug,
		arg.Description,
		arg.Logo,
		arg.Banner,
		arg.ContactPhone,
		arg.BusinessEmail,
		arg.Country,
		arg.City,
		arg.SocialLinks,
	)
	return err
}

const createVendorApplication = `-- name: CreateVendorApplication :exec
INSERT INTO vendor_applications (
  id, user_id, applicant_name, store_name, business_description, logo,
  business_certificate, vendor_photo, business_photo,
  business_email, contact_phone, country, city, registration_number, categories, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'pending')
`

type CreateVendorApplicationParams struct {
	ID                  types.BinaryUUID  `json:"id"`
	UserID              *types.BinaryUUID `json:"user_id"`
	ApplicantName       string            `json:"applicant_name"`
	StoreName           string            `json:"store_name"`
	BusinessDescription string            `json:"business_description"`
	Logo                string            `json:"logo"`
	BusinessCertificate string            `json:"business_certificate"`
	VendorPhoto         string            `json:"vendor_photo"`
	BusinessPhoto       string            `json:"business_photo"`
	BusinessEmail       string            `json:"business_email"`
	ContactPhone        string            `json:"contact_phone"`
	Country             string            `json:"country"`
	City                string            `json:"city"`
	RegistrationNumber  string            `json:"registration_number"`
	Categories          json.RawMessage   `json:"categories"`
}

func (q *Queries) CreateVendorApplication(ctx context.Context, arg CreateVendorApplicationParams) error {
	_, err := q.db.ExecContext(ctx, createVendorApplication,
		arg.ID,
		arg.UserID,
		arg.ApplicantName,
		arg.StoreName,
		arg.BusinessDescription,
		arg.Logo,
		arg.BusinessCertificate,
		arg.VendorPhoto,
		arg.BusinessPhoto,
		arg.BusinessEmail,
		arg.ContactPhone,
		arg.Country,
		arg.City,
		arg.RegistrationNumber,
		arg.Categories,
	)
	return err
}

const featureVendor = `-- name: FeatureVendor :exec
UPDATE vendors SET is_featured = ? WHERE id = ?
`

type FeatureVendorParams struct {
	IsFeatured int16            `json:"is_featured"`
	ID         types.BinaryUUID `json:"id"`
}

func (q *Queries) FeatureVendor(ctx context.Context, arg FeatureVendorParams) error {
	_, err := q.db.ExecContext(ctx, featureVendor, arg.IsFeatured, arg.ID)
	return err
}

const getApplicationByID = `-- name: GetApplicationByID :one
SELECT id, user_id, applicant_name, store_name, business_description, logo, business_certificate, vendor_photo, business_photo, business_email, contact_phone, country, city, registration_number, categories, risk_status, status, review_note, reviewed_by, submitted_at, reviewed_at, created_at, updated_at FROM vendor_applications WHERE id = ? LIMIT 1
`

func (q *Queries) GetApplicationByID(ctx context.Context, id types.BinaryUUID) (VendorApplication, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByID, id)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantName,
		&i.StoreName,
		&i.BusinessDescription,
		&i.Logo,
		&i.BusinessCertificate,
		&i.VendorPhoto,
		&i.BusinessPhoto,
		&i.BusinessEmail,
		&i.ContactPhone,
		&i.Country,
		&i.City,
		&i.RegistrationNumber,
		&i.Categories,
		&i.RiskStatus,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovedApplicationByBusinessEmail = `-- name: GetApprovedApplicationByBusinessEmail :one
SELECT id, user_id, applicant_name, store_name, business_description, logo, business_certificate, vendor_photo, business_photo, business_email, contact_phone, country, city, registration_number, categories, risk_status, status, review_note, reviewed_by, submitted_at, reviewed_at, created_at, updated_at FROM vendor_applications
WHERE LOWER(business_email) = LOWER(?) AND status = 'approved'
ORDER BY reviewed_at DESC
LIMIT 1
`

func (q *Queries) GetApprovedApplicationByBusinessEmail(ctx context.Context, lower string) (VendorApplication, error) {
	row := q.db.QueryRowContext(ctx, getApprovedApplicationByBusinessEmail, lower)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantName,
		&i.StoreName,
		&i.BusinessDescription,
		&i.Logo,
		&i.BusinessCertificate,
		&i.VendorPhoto,
		&i.BusinessPhoto,
		&i.BusinessEmail,
		&i.ContactPhone,
		&i.Country,
		&i.City,
		&i.RegistrationNumber,
		&i.Categories,
		&i.RiskStatus,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeaturedVendors = `-- name: GetFeaturedVendors :many
SELECT DISTINCT v.id, v.user_id, v.store_name, v.slug, v.description, v.logo, v.banner, v.contact_phone, v.business_email, v.country, v.city, v.social_links, v.commission_rate, v.rating, v.verified, v.suspended, v.is_featured, v.created_at, v.updated_at FROM vendors v
INNER JOIN vendor_subscriptions vs ON v.id = vs.vendor_id
WHERE v.suspended = false
  AND v.is_featured = true
  AND vs.active = true
  AND vs.expires_at > NOW()
ORDER BY v.rating DESC, vs.plan DESC
LIMIT ?
`

func (q *Queries) GetFeaturedVendors(ctx context.Context, limit int32) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, getFeaturedVendors, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.Slug,
			&i.Description,
			&i.Logo,
			&i.Banner,
			&i.ContactPhone,
			&i.BusinessEmail,
			&i.Country,
			&i.City,
			&i.SocialLinks,
			&i.CommissionRate,
			&i.Rating,
			&i.Verified,
			&i.Suspended,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestApplicationByBusinessEmail = `-- name: GetLatestApplicationByBusinessEmail :one
SELECT id, user_id, applicant_name, store_name, business_description, logo, business_certificate, vendor_photo, business_photo, business_email, contact_phone, country, city, registration_number, categories, risk_status, status, review_note, reviewed_by, submitted_at, reviewed_at, created_at, updated_at FROM vendor_applications
WHERE LOWER(business_email) = LOWER(?)
ORDER BY submitted_at DESC
LIMIT 1
`

func (q *Queries) GetLatestApplicationByBusinessEmail(ctx context.Context, lower string) (VendorApplication, error) {
	row := q.db.QueryRowContext(ctx, getLatestApplicationByBusinessEmail, lower)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantName,
		&i.StoreName,
		&i.BusinessDescription,
		&i.Logo,
		&i.BusinessCertificate,
		&i.VendorPhoto,
		&i.BusinessPhoto,
		&i.BusinessEmail,
		&i.ContactPhone,
		&i.Country,
		&i.City,
		&i.RegistrationNumber,
		&i.Categories,
		&i.RiskStatus,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestApplicationByUser = `-- name: GetLatestApplicationByUser :one
SELECT id, user_id, applicant_name, store_name, business_description, logo, business_certificate, vendor_photo, business_photo, business_email, contact_phone, country, city, registration_number, categories, risk_status, status, review_note, reviewed_by, submitted_at, reviewed_at, created_at, updated_at FROM vendor_applications WHERE user_id = ? ORDER BY submitted_at DESC LIMIT 1
`

func (q *Queries) GetLatestApplicationByUser(ctx context.Context, userID *types.BinaryUUID) (VendorApplication, error) {
	row := q.db.QueryRowContext(ctx, getLatestApplicationByUser, userID)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantName,
		&i.StoreName,
		&i.BusinessDescription,
		&i.Logo,
		&i.BusinessCertificate,
		&i.VendorPhoto,
		&i.BusinessPhoto,
		&i.BusinessEmail,
		&i.ContactPhone,
		&i.Country,
		&i.City,
		&i.RegistrationNumber,
		&i.Categories,
		&i.RiskStatus,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingApplicationByBusinessEmail = `-- name: GetPendingApplicationByBusinessEmail :one
SELECT id, user_id, applicant_name, store_name, business_description, logo, business_certificate, vendor_photo, business_photo, business_email, contact_phone, country, city, registration_number, categories, risk_status, status, review_note, reviewed_by, submitted_at, reviewed_at, created_at, updated_at FROM vendor_applications WHERE LOWER(business_email) = LOWER(?) AND status = 'pending' LIMIT 1
`

func (q *Queries) GetPendingApplicationByBusinessEmail(ctx context.Context, lower string) (VendorApplication, error) {
	row := q.db.QueryRowContext(ctx, getPendingApplicationByBusinessEmail, lower)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantName,
		&i.StoreName,
		&i.BusinessDescription,
		&i.Logo,
		&i.BusinessCertificate,
		&i.VendorPhoto,
		&i.BusinessPhoto,
		&i.BusinessEmail,
		&i.ContactPhone,
		&i.Country,
		&i.City,
		&i.RegistrationNumber,
		&i.Categories,
		&i.RiskStatus,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingApplicationByUser = `-- name: GetPendingApplicationByUser :one
SELECT id, user_id, applicant_name, store_name, business_description, logo, business_certificate, vendor_photo, business_photo, business_email, contact_phone, country, city, registration_number, categories, risk_status, status, review_note, reviewed_by, submitted_at, reviewed_at, created_at, updated_at FROM vendor_applications WHERE user_id = ? AND status = 'pending' LIMIT 1
`

func (q *Queries) GetPendingApplicationByUser(ctx context.Context, userID *types.BinaryUUID) (VendorApplication, error) {
	row := q.db.QueryRowContext(ctx, getPendingApplicationByUser, userID)
	var i VendorApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ApplicantName,
		&i.StoreName,
		&i.BusinessDescription,
		&i.Logo,
		&i.BusinessCertificate,
		&i.VendorPhoto,
		&i.BusinessPhoto,
		&i.BusinessEmail,
		&i.ContactPhone,
		&i.Country,
		&i.City,
		&i.RegistrationNumber,
		&i.Categories,
		&i.RiskStatus,
		&i.Status,
		&i.ReviewNote,
		&i.ReviewedBy,
		&i.SubmittedAt,
		&i.ReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByBusinessEmail = `-- name: GetVendorByBusinessEmail :one
SELECT id, user_id, store_name, slug, description, logo, banner, contact_phone, business_email, country, city, social_links, commission_rate, rating, verified, suspended, is_featured, created_at, updated_at FROM vendors WHERE LOWER(business_email) = LOWER(?) LIMIT 1
`

func (q *Queries) GetVendorByBusinessEmail(ctx context.Context, lower string) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByBusinessEmail, lower)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Slug,
		&i.Description,
		&i.Logo,
		&i.Banner,
		&i.ContactPhone,
		&i.BusinessEmail,
		&i.Country,
		&i.City,
		&i.SocialLinks,
		&i.CommissionRate,
		&i.Rating,
		&i.Verified,
		&i.Suspended,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, user_id, store_name, slug, description, logo, banner, contact_phone, business_email, country, city, social_links, commission_rate, rating, verified, suspended, is_featured, created_at, updated_at FROM vendors WHERE id = ? AND suspended = false LIMIT 1
`

func (q *Queries) GetVendorByID(ctx context.Context, id types.BinaryUUID) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Slug,
		&i.Description,
		&i.Logo,
		&i.Banner,
		&i.ContactPhone,
		&i.BusinessEmail,
		&i.Country,
		&i.City,
		&i.SocialLinks,
		&i.CommissionRate,
		&i.Rating,
		&i.Verified,
		&i.Suspended,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByIDAdmin = `-- name: GetVendorByIDAdmin :one
SELECT id, user_id, store_name, slug, description, logo, banner, contact_phone, business_email, country, city, social_links, commission_rate, rating, verified, suspended, is_featured, created_at, updated_at FROM vendors WHERE id = ? LIMIT 1
`

func (q *Queries) GetVendorByIDAdmin(ctx context.Context, id types.BinaryUUID) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByIDAdmin, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Slug,
		&i.Description,
		&i.Logo,
		&i.Banner,
		&i.ContactPhone,
		&i.BusinessEmail,
		&i.Country,
		&i.City,
		&i.SocialLinks,
		&i.CommissionRate,
		&i.Rating,
		&i.Verified,
		&i.Suspended,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByUserID = `-- name: GetVendorByUserID :one
SELECT id, user_id, store_name, slug, description, logo, banner, contact_phone, business_email, country, city, social_links, commission_rate, rating, verified, suspended, is_featured, created_at, updated_at FROM vendors WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetVendorByUserID(ctx context.Context, userID types.BinaryUUID) (Vendor, error) {
	row := q.db.QueryRowContext(ctx, getVendorByUserID, userID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Slug,
		&i.Description,
		&i.Logo,
		&i.Banner,
		&i.ContactPhone,
		&i.BusinessEmail,
		&i.Country,
		&i.City,
		&i.SocialLinks,
		&i.CommissionRate,
		&i.Rating,
		&i.Verified,
		&i.Suspended,
		&i.IsFeatured,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVendorCategory = `-- name: InsertVendorCategory :exec
INSERT IGNORE INTO vendor_categories (vendor_id, category_id) VALUES (?, ?)
`

type InsertVendorCategoryParams struct {
	VendorID   types.BinaryUUID `json:"vendor_id"`
	CategoryID types.BinaryUUID `json:"category_id"`
}

func (q *Queries) InsertVendorCategory(ctx context.Context, arg InsertVendorCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertVendorCategory, arg.VendorID, arg.CategoryID)
	return err
}

const listPendingApplications = `-- name: ListPendingApplications :many
SELECT id, user_id, applicant_name, store_name, business_description, logo, business_certificate, vendor_photo, business_photo, business_email, contact_phone, country, city, registration_number, categories, risk_status, status, review_note, reviewed_by, submitted_at, reviewed_at, created_at, updated_at FROM vendor_applications
WHERE status = 'pending'
ORDER BY submitted_at DESC
LIMIT ? OFFSET ?
`

type ListPendingApplicationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingApplications(ctx context.Context, arg ListPendingApplicationsParams) ([]VendorApplication, error) {
	rows, err := q.db.QueryContext(ctx, listPendingApplications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorApplication{}
	for rows.Next() {
		var i VendorApplication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ApplicantName,
			&i.StoreName,
			&i.BusinessDescription,
			&i.Logo,
			&i.BusinessCertificate,
			&i.VendorPhoto,
			&i.BusinessPhoto,
			&i.BusinessEmail,
			&i.ContactPhone,
			&i.Country,
			&i.City,
			&i.RegistrationNumber,
			&i.Categories,
			&i.RiskStatus,
			&i.Status,
			&i.ReviewNote,
			&i.ReviewedBy,
			&i.SubmittedAt,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorCategoryIDs = `-- name: ListVendorCategoryIDs :many
SELECT category_id FROM vendor_categories WHERE vendor_id = ?
`

func (q *Queries) ListVendorCategoryIDs(ctx context.Context, vendorID types.BinaryUUID) ([]types.BinaryUUID, error) {
	rows, err := q.db.QueryContext(ctx, listVendorCategoryIDs, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []types.BinaryUUID{}
	for rows.Next() {
		var category_id types.BinaryUUID
		if err := rows.Scan(&category_id); err != nil {
			return nil, err
		}
		items = append(items, category_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorsAdmin = `-- name: ListVendorsAdmin :many
SELECT id, user_id, store_name, slug, description, logo, banner, contact_phone, business_email, country, city, social_links, commission_rate, rating, verified, suspended, is_featured, created_at, updated_at FROM vendors ORDER BY created_at DESC LIMIT ? OFFSET ?
`

type ListVendorsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListVendorsAdmin(ctx context.Context, arg ListVendorsAdminParams) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, listVendorsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.Slug,
			&i.Description,
			&i.Logo,
			&i.Banner,
			&i.ContactPhone,
			&i.BusinessEmail,
			&i.Country,
			&i.City,
			&i.SocialLinks,
			&i.CommissionRate,
			&i.Rating,
			&i.Verified,
			&i.Suspended,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectApplication = `-- name: RejectApplication :exec
UPDATE vendor_applications
SET status = 'rejected', review_note = ?, reviewed_at = ?
WHERE id = ?
`

type RejectApplicationParams struct {
	ReviewNote sql.NullString   `json:"review_note"`
	ReviewedAt sql.NullTime     `json:"reviewed_at"`
	ID         types.BinaryUUID `json:"id"`
}

func (q *Queries) RejectApplication(ctx context.Context, arg RejectApplicationParams) error {
	_, err := q.db.ExecContext(ctx, rejectApplication, arg.ReviewNote, arg.ReviewedAt, arg.ID)
	return err
}

const searchVendors = `-- name: SearchVendors :many
SELECT id, user_id, store_name, slug, description, logo, banner, contact_phone, business_email, country, city, social_links, commission_rate, rating, verified, suspended, is_featured, created_at, updated_at FROM vendors
WHERE suspended = false
ORDER BY rating DESC, created_at DESC
LIMIT ? OFFSET ?
`

type SearchVendorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) SearchVendors(ctx context.Context, arg SearchVendorsParams) ([]Vendor, error) {
	rows, err := q.db.QueryContext(ctx, searchVendors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.Slug,
			&i.Description,
			&i.Logo,
			&i.Banner,
			&i.ContactPhone,
			&i.BusinessEmail,
			&i.Country,
			&i.City,
			&i.SocialLinks,
			&i.CommissionRate,
			&i.Rating,
			&i.Verified,
			&i.Suspended,
			&i.IsFeatured,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorProfile = `-- name: UpdateVendorProfile :exec
UPDATE vendors
SET store_name = COALESCE(?, store_name),
    description = COALESCE(?, description),
    logo = COALESCE(?, logo),
    banner = COALESCE(?, banner),
    contact_phone = COALESCE(?, contact_phone),
    business_email = COALESCE(?, business_email),
    country = COALESCE(?, country),
    city = COALESCE(?, city),
    social_links = COALESCE(?, social_links)
WHERE user_id = ?
`

type UpdateVendorProfileParams struct {
	StoreName     sql.NullString   `json:"store_name"`
	Description   sql.NullString   `json:"description"`
	Logo          sql.NullString   `json:"logo"`
	Banner        sql.NullString   `json:"banner"`
	ContactPhone  sql.NullString   `json:"contact_phone"`
	BusinessEmail sql.NullString   `json:"business_email"`
	Country       sql.NullString   `json:"country"`
	City          sql.NullString   `json:"city"`
	SocialLinks   *json.RawMessage `json:"social_links"`
	UserID        types.BinaryUUID `json:"user_id"`
}

func (q *Queries) UpdateVendorProfile(ctx context.Context, arg UpdateVendorProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateVendorProfile,
		arg.StoreName,
		arg.Description,
		arg.Logo,
		arg.Banner,
		arg.ContactPhone,
		arg.BusinessEmail,
		arg.Country,
		arg.City,
		arg.SocialLinks,
		arg.UserID,
	)
	return err
}

const updateVendorRating = `-- name: UpdateVendorRating :exec
UPDATE vendors SET rating = ? WHERE id = ?
`

type UpdateVendorRatingParams struct {
	Rating string           `json:"rating"`
	ID     types.BinaryUUID `json:"id"`
}

func (q *Queries) UpdateVendorRating(ctx context.Context, arg UpdateVendorRatingParams) error {
	_, err := q.db.ExecContext(ctx, updateVendorRating, arg.Rating, arg.ID)
	return err
}
